### ISSUE TITLE
Chrome 46 has a mousewheel bug that creates strange zoom in/out behavior

### ISSUE THREAD

**Issue by masedesign** [mbloch/mapshaper#104]
For some reason, in the latest version of Chrome (released a few weeks ago), the `mousewheel` event fires twice after completion (even though it shouldn't) with a `wheelDelta` of `0`. This causes some pretty jenky zoom behavior, especially when zooming out. As far as I can tell, it's most noticeable on a MacBook Pro. Even though you've stopped scrolling, it fires the `mousewheel` event twice as soon as you lift your fingers from the trackpad (which could be theoretically several seconds, minutes, hours after you've finished scrolling).

Wrapping the entire `handleWheel` method in `if (Math.abs(evt.wheelDelta))` ensures that the `wheelDelta` is an actual delta. and fixes this issue. 

Here is a link to the Chromium issue:

https://code.google.com/p/chromium/issues/detail?id=553732&thanks=553732&ts=1447117036

**Comment by mbloch** [comment]
I just pushed a fix for this and updated mapshaper.org... thanks :)

**Comment by masedesign** [comment]
Ha! Awesome :) Sorry about that!
