### ISSUE TITLE
CSV/TSV no longer supported

### ISSUE THREAD

**Issue by peteb4ker** [mbloch/mapshaper#107]
## Overview

Project documentation states that tsv and csv are recognized output formats.  The current version doesn't support these, throwing the following error when trying to export to csv.:

```
Error: [o] Unsupported output format: csv
```

It looks like mapshaper-file-types.js filters out those filetypes:

https://github.com/mbloch/mapshaper/blob/4044579fb7b9aab312c8986479e72afafe5f85cb/src/mapshaper-file-types.js#L79

## Acceptance criteria

* Either documents are updated to remove csv support, or csv support is re-added.

**Comment by mbloch** [comment]
Hi, could you double-check that you're using the current version (0.3.12). If you are, could you give the input command that resulted in the error?

I checked csv output a minute ago and it seemed to be working. This is the command that I ran, and the console output:

```
$ mapshaper test.shp -v -o format=csv out.txt
0.3.12
Wrote out.txt
```

**Comment by peteb4ker** [comment]
Hi Matthew, 

Apologies, it looks like I was running an old version.   It works great under 0.3.12.  

Keep up the great work - closing this issue as invalid.

**Comment by mbloch** [comment]
No worries, thanks for using mapshaper :)
