### ISSUE TITLE
Adding x and y coordinates using $.x and $.y doesn't work for point layers

### ISSUE THREAD

**Issue by spatialthoughts** [mbloch/mapshaper#109]
My use case is exporting a shapefile to a CSV while adding 2 new properties for X and Y coordinates. But the $.x and $.y in the expression results in null values. Trying the following command on  [ne_10m_airports.zip](https://github.com/mbloch/mapshaper/files/97256/ne_10m_airports.zip) results in 'undefined'. 

```
mapshaper ne_10m_airports.shp -each 'x=$.x' -info

Detected DBF text encoding: win1252
Sample text containing non-ascii characters:
  Rosario – Islas Malvinas Int'l  Martín Miguel de Güemes Int
  Cayenne – Rochambeau            Foz do Iguaçu Int'l
Name: ne_10m_airports
Geometry: point
Records: 891
Bounds: -175.135635 -53.7814746058316 179.19544202302 78.246717
Data table
  Field       First value
  abbrev      'LUH'
  featurecla  'Airport'
  gps_code    'VILD'
  iata_code   'LUH'
  location    'terminal'
  name        'Sahnewal'
  natlscale   8
  scalerank   9
  type        'small'
  wikipedia   'http://en.wikipedia.org/wiki/Sahnewal_Airport'
  x           undefined
```

Using $.coordinates works fine. I am on version 0.3.9

**Comment by mbloch** [comment]
Hi,

I added `$.x` and `$.y` in version 0.3.11, so updating should resolve this.

Here's a link to the change log: https://github.com/mbloch/mapshaper/releases

btw, thanks for the detailed report :)

**Comment by spatialthoughts** [comment]
Verified that it works in 0.3.11. Thanks!
