### ISSUE TITLE
mapshaper-cli claims to dissolve polygons, but it doesn't appear that it does

### ISSUE THREAD

**Issue by masedesign** [mbloch/mapshaper#110]
Using `mapshaper` via command line:

```
mapshaper -i sample.json  -o dissolved.json  -dissolve p
Wrote dissolved.json
[dissolve] Dissolved 5,230 features into 122 features
```

When opening `dissolved.json` back into mapshaper, it still appears to have 5,230 features and not the claimed 122.

Am I doing something wrong or is this a bug?

**Comment by mbloch** [comment]
Commands are run in sequence, you just need to rearrange your command line, like this:

```
mapshaper -i sample.json  -dissolve p  -o dissolved.json
```

**Comment by masedesign** [comment]
thank you!
