### ISSUE TITLE
Can mapshaper render multiple files on a single canvas?

### ISSUE THREAD

**Issue by amayne** [mbloch/mapshaper#111]
When I load in multiple files, they go to separate canvas'. Is it possible to render two files on the same canvas?

Thanks!!

**Comment by mbloch** [comment]
I suppose mapshaper could use a single canvas for drawing shapes. Are you worried about the Web UI using too much memory?

**Comment by amayne** [comment]
Not necessarily worried about the memory, I just have a few datasets that I'd like to see together visually on a single canvas. If you have any ideas on how that might be achieved please let me know!

**Comment by mbloch** [comment]
I see -- you'd like to be able to display more than one dataset at the same time, for comparison. That would be useful.

One option would be to add a button to each layer in the layers menu, which would set that layer to be visible all the time. A visible but unselected layer would appear behind the selected layer, and in a lighter color. 

That's one suggestion, we can brainstorm other ways to implement this feature as well.

**Comment by amayne** [comment]
Thanks @mbloch - that would be awesome! To be more specific, I'd like to be able to overlay the geography that corresponds with my dataset, simply as a background overlay. There are a lot that let you display data over Google maps but I would prefer to control the geography using something from a public database. For now, do you know if there's a place somewhere in `mapshaper-import.js` or another file to hook into rendering another file on a single canvas?

**Comment by mmase** [comment]
+1 to this one. Having a parent layer on a separate canvas would be awesome. Especially useful for states/counties/etc.

**Comment by pyrog** [comment]
> you'd like to be able to display more than one dataset at the same time, for comparison

👍

**Comment by mbloch** [comment]
The latest release (v0.4.14) has preliminary support for this feature. There's a new button next to each layer's close button in the layer menu. Clicking it "pins" that layer, so it appears when a different layer is selected.

**Comment by mbloch** [comment]
After commit 60a8c8bad71c4a51b9a2fa99794, support for displaying a reference layer in the background seems to work pretty well -- closing this issue.
