### ISSUE TITLE
Point aggregation

### ISSUE THREAD

**Issue by mbloch** [mbloch/mapshaper#116]
It might useful to aggregate a group of points into a single point location, with optional weighting.

I recently wanted to find points to approximate the center of population of a group of counties. This could be done by finding the centroids of the census tracts or census blocks in each county, then finding the population-weighted centroid for each county.

**Comment by nvkelso** [comment]
+1

**Comment by mbloch** [comment]
I added point aggregation to the `-dissolve` command in version 0.3.16. See the [command reference](https://github.com/mbloch/mapshaper/wiki/Command-Reference#-dissolve) for details.
