### ISSUE TITLE
syntax to merge or dissolve selected polygons, but retain others, in web console?

### ISSUE THREAD

**Issue by JackDougherty** [mbloch/mapshaper#117]
I love http://mapshaper.org and have learned several web console commands from the project wiki. But I'm still searching for the correct syntax to perform this common task, which would help my students and non-profit partners who do not have GIS skills.

Goal: Transform an existing statewide map of town polygons into one that includes some merged regional polygons

So far I'm following this partial approach, which is not sufficient:
1) Upload geojson layer of all Connecticut town polygons
https://github.com/JackDougherty/geojson/

2) Filter and dissolve selected polygons to create a regional polygon with this console command:
```
-filter 'Town=="Hartford" || Town=="West Hartford"' -dissolve
```

But the result is one merged polygon, and all of the other town polygons disappear. 

Instead, my goal is to merge/dissolve selected polygons, AND retain all of other polygons, in a new layer for the entire state. 

Suggestions?

**Comment by mbloch** [comment]
I can think of two ways to solve this problem.

[1] Replace the names of the towns that you want to merge with a group name, then dissolve. Example:

```
mapshaper towns.shp \
-each 'Town = "Hartford/West Hartford"' where='Town=="Hartford" || Town=="West Hartford"' \
-dissolve Town \
-o towns2.shp
```

[2] If there are many towns to merge, the above method quickly becomes unwieldy. You can export the data attributes to a csv file, edit this file in a spreadsheet, then use mapshaper to join your edited data to the original attributes and dissolve.

First, export attributes as csv
```
mapshaper towns.shp -o towns.csv
```
Next, add a "TownMerge" field, containing the original town names of unmerged towns and group names of the towns you want to merge.

Finally, join and dissolve
```
mapshaper towns.shp \
-join towns.csv keys=Town,Town \
-dissolve TownMerge \
-o towns2.shp

**Comment by mbloch** [comment]
Ah, I just noticed you want to use the web UI, and I've given you command line examples.... 

You should be able to use the same commands that I listed above in the web console. The only difference is that you'll have to import your files using the web UI.

**Comment by JackDougherty** [comment]
This is fantastic! Thank you

**Comment by JackDougherty** [comment]
Matthew, I added your advice into this open-access book-in-progress, Data Visualization For All.
http://www.datavizforall.org/shape/mapshaper/index.html

When you have a moment, would you please take a look and tell me if you spot any errors?

**Comment by mbloch** [comment]
Hi Jack,

Thanks for the write-up, looks good!

One comment... you wrote "Hint: To edit data fields for a few polygons,
convert to GeoJSON format, then import intohttp://GeoJSON.io, as described
in the GeoJSON.io chapter in this book."

You can actually edit data values in mapshaper by selecting the "i" tool
and then clicking on the feature you want to edit. This pins open the popup
attribute inspector, and the attribute values become editable.

Cheers,
Matt

**Comment by JackDougherty** [comment]
Thanks for your comment, which I incorporated into the revised tutorial. It now includes instructions on how to clip, join, and dissolve selected polygons (using your 2nd recommended method, which is easier than the 1st method for novices). When you have a moment, please take another look:
http://www.datavizforall.org/shape/mapshaper/index.html

Since you created this wonderful tool, I would be delighted if you granted permission for me to list you as a co-author at the top of this page, and therefore a contributor to this open-access book. For any off-line questions, feel free to email me at jack.dougherty@trincoll.edu

**Comment by mbloch** [comment]
I'd rather not be listed as a co-author, thanks for offering :)

I have a couple of comments on the current version of your tutorial:

1. You write, "For Shapefiles, import the .shp extension." This implies that you can't also import other Shapefile files; but if you want to import attribute data, you need to import the .dbf file. Mapshaper will also import .prj files (which it copies to the output Shapefile).

2. In the section on joining data, you mention Mapshaper's console message showing the number of unjoined records. The latest version has two new options to the join command that can help users troubleshoot imperfect joins. If you add the "unjoined" flag, Mapshaper saves a copy of each unjoined record from the source table to a layer named "unjoined." If you add the "unmatched" flag, Mapshaper saves of copy of each unmatched record from the target table to a layer named "unmatched."

**Comment by mbloch** [comment]
The Mapshaper tutorial looks great, I think it's time to close this issue.

**Comment by dimants** [comment]
> Thanks for your comment, which I incorporated into the revised tutorial. It now includes instructions on how to clip, join, and dissolve selected polygons (using your 2nd recommended method, which is easier than the 1st method for novices). When you have a moment, please take another look:
> http://www.datavizforall.org/shape/mapshaper/index.html
> 
> Since you created this wonderful tool, I would be delighted if you granted permission for me to list you as a co-author at the top of this page, and therefore a contributor to this open-access book. For any off-line questions, feel free to email me at [jack.dougherty@trincoll.edu](mailto:jack.dougherty@trincoll.edu)

The link should be updated to https://www.datavizforall.org/transform/mapshaper/
