### ISSUE TITLE
Erase option is missing Rhode Island

### ISSUE THREAD

**Issue by eflowbeach** [mbloch/mapshaper#118]
This command appeared to work on every state except for RI. Curious if you have any suggestions.

`mapshaper worldmask.json -erase RI.json -o format=geojson clipped.json`

[RI.txt](https://github.com/mbloch/mapshaper/files/159151/RI.txt)
[worldmask.txt](https://github.com/mbloch/mapshaper/files/159152/worldmask.txt)
[clipped.txt](https://github.com/mbloch/mapshaper/files/159153/clipped.txt)

**Comment by mbloch** [comment]
Thanks for filing this, I'll investigate.

**Comment by mbloch** [comment]
Ok, I can explain why this is happening.

I made an ill-considered decision to try to automatically filter out "splinter" polygons after clipping and erasing. In my work, I often clip one dataset with another very similar dataset, for example, using the coastline of a country to clip a layer of state or counties that extends beyond the coastline. This often results in a lot of very small slivers where the two layers almost-but-not-quite align.

Mapshaper thought that Rhode Island was a sliver and removed it. Obviously I need to improve sliver detection. I think I should also turn off sliver removal by default.

I'm planning to release a new version later this week that does a better job with sliver detection.

Meanwhile, you can disable sliver removal using the `no-cleanup` flag, like this:

```bash
mapshaper worldmask.json -erase RI.json no-cleanup -o format=geojson clipped.json
```

**Comment by eflowbeach** [comment]
Cool, that worked!  

I think highlighting the "no-cleanup" option in the "Command Reference" may be a good remedy for this. Like I said, it only failed on Rhode Island and other than that I've been very happy with all the results Mapshaper has generated.  Thank you very much for writing such a nice application!
