### ISSUE TITLE
need examples for cleanup, unjoined, unmatched flags

### ISSUE THREAD

**Issue by JackDougherty** [mbloch/mapshaper#120]
Thanks for continuing to add new features. As you previously suggested, I updated my tutorial (http://www.datavizforall.org/shape/mapshaper/index.html). But I have not figured out the correct syntax in the console to use the new "flags" you created: cleanup (for -clip and -erase) and unjoined/unmatched (for -join). Please point me toward, or provide, an example.

**Comment by mbloch** [comment]
Below I've pasted a real-life join example along with mapshaper's console output. In this example, I'm using the `unmatched` and `unjoined` flags to capture records from the target and source attribute tables. If you're familiar with the output of the `-info` command, you can see that 57 unjoined source records and 2227 unmatched target records have been copied into two new layers. These layers can be saved and examined to find out why some of the records failed to join.

The `cleanup` flag is a bit simpler. If you add it to a `-clip` or `-erase` command, mapshaper will remove tiny slivers that can form where the boundaries of the clipping layer and the target layer closely parallel each other. I used to do this automatically, but found that my automatic sliver detection function could fail in some uncommon cases. So I made sliver removal optional with the `cleanup` flag.

Command:
```bash
$  mapshaper metwp24s/metwp24p.shp -join ap.csv keys=TOWN,name unjoined unmatched -info
```

Output:
<pre>
[join] Joined 445 data records
[join] 2227/8422 target records received no data
[join] 52/497 source records could not be joined
Layer 1
Name: metwp24p
Geometry: polygon
Records: 8,422
Bounds: 336630.2812210694 4752815.499671124 667255.1873616241 5256292.499986611
Data table
  Field            First value
  BAXTER           'n'
  CIREG            ''
  CNTYCODE         '03'
  COUNTY           'Aroostook'
  DOT_REGION       'NORTHERN'
  DOT_REGNUM              5
  GEOCODE          '03832'
  GEOCODENUM           3832
  ISLAND           'n'
  ISLANDID         '0'
  LAND             'y'
  LURC             'y'
  Shape_area       96397282.6375
  Shape_len           39294.4104868
  TAG              'y'
  TOWN             'T10 R8 WELS'
  TYPE             ''
  precincts_total  null

Layer 2
Name: unmatched
Geometry: [none]
Records: 2,227
Data table
  Field       First value
  BAXTER      'n'
  CIREG       ''
  CNTYCODE    '03'
  COUNTY      'Aroostook'
  DOT_REGION  'NORTHERN'
  DOT_REGNUM         5
  GEOCODE     '03832'
  GEOCODENUM      3832
  ISLAND      'n'
  ISLANDID    '0'
  LAND        'y'
  LURC        'y'
  Shape_area  96397282.6375
  Shape_len      39294.4104868
  TAG         'y'
  TOWN        'T10 R8 WELS'
  TYPE        ''

Layer 3
Name: unjoined
Geometry: [none]
Records: 52
Data table
  Field            First value
  name             'Bancroft'
  precincts_total  1
</pre>

**Comment by JackDougherty** [comment]
Thanks! I updated the [Clip section](http://www.datavizforall.org/shape/mapshaper/index.html#clip-a-map-to-match-an-outline-layer) and the [More about Joins](http://www.datavizforall.org/shape/mapshaper/index.html#more-about-joins) section of the tutorial.
