### ISSUE TITLE
Polygon geometry should always be a (closed) linear ring

### ISSUE THREAD

**Issue by floledermann** [mbloch/mapshaper#125]
Some libraries like the Google Maps API take the GeoJSON spec quite literal about specifying the geometry field of polygons:

> For type "Polygon", the "coordinates" member must be an array of LinearRing coordinate arrays. 

([2.1.6 Polygon](http://geojson.org/geojson-spec.html#polygon))

> A LinearRing is closed LineString with 4 or more positions. The first and last positions are equivalent (they represent equivalent points).

([2.1.4. LineString](http://geojson.org/geojson-spec.html#linestring))

This means if the last coordinate is not equal to the first one, the polygon is not rendered but the whole file rejected as invalid GeoJSON. I couldn't believe it myself but this is what happens in the Google Maps API!

Could there be an option to fix polygon geometries to adhere to such to-the-letter readings of the spec (i.e. adding a last coordinate pair equal to the first)? (It could be argued that this should even be on by default)

**Comment by mbloch** [comment]
This seems like a reasonable suggestion.

Just to be clear, you would like mapshaper to repair invalid polygons in an imported dataset (by closing open paths), correct?. If mapshaper ever converts valid polygons into open paths, that would be a serious bug that should be fixed right away.

I'm inclined to check for ring closure when a polygon dataset is imported. This check would be applied to all the relevant file types (TopoJSON, GeoJSON and Shapefile).

Perhaps mapshaper should automatically close open rings and print a warning, so users know that their source data has a problem.

There are other kinds of geometry problems that mapshaper doesn't currently check for. I'll think a bit about which problems can be handled automatically and which ones would be better handled in a separate repair command.

**Comment by floledermann** [comment]
Yes, that error was already in the data, though if it is coming from a shape file I am not sure if it would be valid in there. I am not sure if mapshaper is the correct place to deal with this - I just haven't found any other GeoJSON-focused tool that could fix/indicate the error.

**Comment by mbloch** [comment]
All the relevant specs require that polygon rings be closed, meaning that the coordinates of the first and last points of each ring are the same.

I'll get this added when I have a chance, probably within a few days.

**Comment by mbloch** [comment]
I added automatic ring closing for Shapefiles and GeoJSON files to the latest version (0.3.21), just published.

**Comment by floledermann** [comment]
Amazing! I can confirm this fixes my testcase :+1:

**Comment by ralyodio** [comment]
how do i use it?
