### ISSUE TITLE
Select by ID in mapshaper GUI console

### ISSUE THREAD

**Issue by danvk** [mbloch/mapshaper#128]
I can filter to features which have some property in the mapshaper GUI console via:

```
filter 'propertyname == "value"'
```

If my GeoJSON file has an [`id` field][1], though (which is not in `properties`), it's not clear to me how to select based on that. Either a separate `select` command or a way to access the ID in a `filter` statement would be really helpful.

[1]: http://geojson.org/geojson-spec.html#feature-objects

**Comment by danvk** [comment]
Oh, does `id` just become `FID`? That's easy enough!

**Comment by danvk** [comment]
Hmm, I hadn't realized that `filter` irrevocably deletes features. Let's change this issue to be a feature request to add a `select` method in the console, then. This would be the same as clicking the "i" button on the right, then clicking on the feature with that ID.

**Comment by mbloch** [comment]
`-filter`, like some other commands, modifies the target layer by default. Instead, you can copy the output to a new layer, using the `+` option. For example:

`-filter 'name == "Oregon"' + name=oregon`

Here I'm also using the `name=` option to assign a name to the output layer.

**Comment by danvk** [comment]
Creating a new layer seems like overkill to select an element, though. Is the "i" button implemented this way?

**Comment by mbloch** [comment]
The 'i' button doesn't create a new layer.

I think I misunderstood what you would like to do... so do you envision a `select` command that would highlight a feature and open up the attribute inspector when run in the gui?

**Comment by danvk** [comment]
Sorry, my initial question really made that confusing. Yes, I'm asking for a `select` command.

**Comment by mbloch** [comment]
What about extending the `-info` command by adding an optional argument for selecting a particular feature (or perhaps also a collection of features). Currently running `-info` shows attributes for the first feature in a data layer. Being able to choose an arbitrary feature seems like a natural extension of this behavior.

**Comment by danvk** [comment]
Sure, so long as `-info` also visually highlights the relevant feature. That's my primary need here. ("where is this feature?")

**Comment by mbloch** [comment]
It makes sense to me to add an optional argument to `-info`, which would be a JS expression, with the same context as the expressions used by the "each" and "filter" commands. In the command line program, this would give you a textual display of attributes and other properties of the selected feature. In the GUI, it would highlight the selected feature (or features) and pop up the inspector window.

Currently the inspector only shows one feature at a time... it should be able to show multiple features.

I've thought about a selection tool for the GUI (It's issue #91), but it would work a bit differently than what you're describing.

**Comment by mbloch** [comment]
... or maybe instead of repurposing `-info`, maybe the command should be called `-inspect`, which also has a nice association with the "i" button (I go back and forth about whether the button stands for "inspect" or "info")

**Comment by danvk** [comment]
I'd be fine with either approach. Does there need to be a 1-1 mapping between console commands and `mapshaper` CLI args? I'm not sure what `-inspect` would mean on the CLI.

**Comment by mbloch** [comment]
There doesn't need to be a 1-1 mapping... but in the past I've wanted to get information about a particular feature when using the cli... I think this proposal can work well in both contexts

**Comment by mbloch** [comment]
I just published version 0.3.23, which has the new `-inspect` command. `-inspect` takes a JS expression for selecting a feature, similar to the expressions used by the `-each` and `-filter` commands. It should work in the web UI and the command line script (although the command line output could be improved)...

**Comment by mbloch** [comment]
v0.3.25 adds geometry information to the console output of -inspect.

You may have noticed that in the gui, when multiple features are selected via the `-inspect` command, the feature that is displayed in the popup inspector is highlighted in pink, and the other features are orange.

The multiple-feature highlight is kind of a precursor to a future planned "select" command that will let users create a selection (either interactively or via the console) and then do something with the selected features. For example, you could delete them from the active layer, copy them to a new layer or move them to a new layer.
