### ISSUE TITLE
 snap vertices and line intersections in web interface

### ISSUE THREAD

**Issue by JackDougherty** [mbloch/mapshaper#131]
Thanks again for continuing to improve this very useful tool. I did not see an answer to this question in your wiki, so am posting it here.

I wish to correct some hand-drawn GeoJSON historical map boundaries that have small errors (intersecting lines).

In the web interface, checking the "snap vertices" box fixes most of these errors, but I still see warnings such as "1 line intersection"

Are there console commands to fix these line intersection errors? For example, is there any way to change "snap-interval" after the GeoJSON has already been uploaded in the web interface?

**Comment by mbloch** [comment]
Hi Jack,

Currently there's no way to snap vertices after data has been imported.

Applying a snapping interval to all the vertices in a dataset is a pretty crude way to fix topology errors. Often, if you apply an interval that is large enough to fix the worst intersections or gaps, then other, clean features are affected.

I wonder if  a function for removing small gaps and overlaps might be more broadly useful.

Do you know of other techniques for cleaning up messy datasets? What kind of methods do ArcGIS and QGIS have? I'd like to consider all the options before adding this kind of functionality.

**Comment by JackDougherty** [comment]
Thanks for your helpful response. I will look more closely at QGIS to see if it fits my needs, since importing/exporting GeoJSON in ArcGIS has been more challenging than it needs to be.

**Comment by JackDougherty** [comment]
Yes, QGIS allows me to edit GeoJSON files, with good topology control to snap vertices and add/delete/move nodes, and export directly to GeoJSON. (Oddly, QGIS allows import but not live editing of GeoJSON files. You need to save as in Shapefile format before editing is enabled.) My problem is solved with QGIS, so I'm closing this issue. Thanks.

**Comment by Stophface** [comment]
@JackDougherty could you share what algorithm you used in QGIS?

**Comment by JackDougherty** [comment]
@Stophface Sorry, I barely have any memory of this 6-year-old comment, and I certainly did not use an algorithm in QGIS for this task, which I would have done manually.

**Comment by Stophface** [comment]
@JackDougherty That is alright. I thought I try anyway ;)
