### ISSUE TITLE
Serialize property objects as JSON

### ISSUE THREAD

**Issue by danvk** [mbloch/mapshaper#133]
There's no reason values in a feature's properties need to be scalars. If they're sub-objects, mapshaper shows them as "[Object object]", both on the command line and in the web UI:
![object object](https://cloud.githubusercontent.com/assets/98301/15690564/18abca4c-2752-11e6-907a-a4592a54b41e.png)

It would be better if it serialized the contents of these sub-objects as JSON, e.g.`{"a": 123}` instead of `[Object object]`.

**Comment by mbloch** [comment]
This is a good suggestion, I'll start working on it.

**Comment by mbloch** [comment]
I just released v0.3.26, which uses JSON to display objects and arrays.

**Comment by danvk** [comment]
Just upgraded and it works perfectly. Thanks @mbloch!
