### ISSUE TITLE
New R package rmapshaper

### ISSUE THREAD

**Issue by ateucher** [mbloch/mapshaper#134]
Hi, 
Thank you so much for your work on this amazing tool, and for making it open source. 

I've wrapped mapshaper into an R package (called rmapshaper) so R users can access the command-line functionality from within R.

My github developmenta page is [here](/ateucher/rmapshaper), and it is available to users on CRAN (central repository for R packages) [here](https://cran.r-project.org/web/packages/rmapshaper/index.html).

I really hope I've acknowledged your work sufficiently and correctly. Please let me know if you have any comments or concerns.

Thanks again,
Andy

**Comment by mbloch** [comment]
Thanks for the heads-up, sounds like a good thing.
