### ISSUE TITLE
Web-GUI: Load Shapefile on open

### ISSUE THREAD

**Issue by brooksbl** [mbloch/mapshaper#135]
Not an issue per se, but a request for guidance.

I am  very impressed with this tool. I want to link to the web interface of mapshaper from another site. I  would like to load a shapefile from the server automatically on load based on a query string I can add to the URL.

I've added a line at the end of index.html (within  a script tag):
`mapshaper.runCommands("-i " + URLtoShapefileasZIP);` 

This doesn't work and returns "file not found: shapefile.zip"

Is this possible? I've been working on it for a few days now and I'm not getting anywhere.

Thank you for any guidance you can provide.

**Comment by mbloch** [comment]
I'll consider loading online sources if it seems like something that would be broadly useful, could you explain why you're interested in adding this feature?

As an alternative, if you've installed mapshaper on your own computer, you could first download the Shapefile that you want to edit and then it in the web UI by running `mapshaper-gui path/to/file`. This way you don't have to drag-and-drop the file or select it from the "open file" dialog.

**Comment by brooksbl** [comment]
I'm working with a shapefile library of over 400GGB. There are over 50 users who access this library. We have a tool we are in the process of implementing that will allow users to search through the shapefiles. We want to add the mapshaper functions to this online library. Then when they find a resource, they can open it immediately in the browser and manipulate it with mapshaper and then export it to their desktop.

**Comment by timelyportfolio** [comment]
I hacked it to work in these lines https://github.com/timelyportfolio/mapshaper_htmlwidget/blob/master/inst/htmlwidgets/mapshaper.js#L25.  Perhaps it will help.

**Comment by mbloch** [comment]
One solution would be to fork mapshaper and make a few edits to get the web UI to load one of the Shapefiles from your library on startup. You'd host your modified version of mapshaper on your own site.

On line 84 of  `src/gui/mapshaper-import-control.js`, the variable `mapshaper.manifest` can  contain an array of filenames to be loaded into the web GUI when it first opens.

You could a bit of code to populate the manifest from a variable in the URL query string.

You would also need to edit the asset path to point to your library of Shapefiles (see line 316 of the same file).

**Comment by brooksbl** [comment]
That did the trick. I was unaware of `mapshaper.manifest`. That was all I needed to make it work. Thank you so much. That really helps a ton.

**Comment by mbloch** [comment]
I'm glad we found a solution.

I don't think this should to be added as a feature to the master branch, partly because you have a special-purpose application, and partly because it isn't possible to load files across domains via AJAX unless the remote server has set [CORS headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) to allow it.
