### ISSUE TITLE
Export multiple attributes to svg file

### ISSUE THREAD

**Issue by megharajdeepak** [mbloch/mapshaper#138]
Hi,
Firstly thank you so much for such a great tool. I had some shape files(shp, dbf, shx). I was planning to use those files to generate svg so that I could plot offline maps and your tool has been of great help till now.

I was able to get svg file and it gets plotted beautifully on the browser as well. Only thing I need is to pass the data (like region-id, region-code, region-name, region-parent etc) which are available in dbf file, to svg's path(each path is a region). I looked into the docs and came across id-field. But this exports only one Id per path. How do I pass multiple Ids in each path? 

For ex, right now this is what i get(when i use id-field=regionId and then export to svg):
<path d="M 368.5807 101.7469 367.3892 10 101.7469 Z id="1"/>
<path d="M 392.667 88.0661 389.61  86.4943 392.667 88.0661 Z" id="2"/>

But I need this:
<path d="M 368.5807 101.7469 367.3892 10 101.7469 Z" desc="REGION DESC 1" regionId="1"/>
<path d="M 392.667 88.0661 389.61   88.0661 Z" desc="REGION DESC 2" regionId="2"/>

While exporting, i tried giving following options 
id-field=regionId,desc
id-field=regionId, id-field=desc
id-field=regionId|desc

None of them worked. 

I'm sure i am missing something here, as it works as expected when I import the file in mapshaper and click on 'i' icon on top right corner. I can hover on each region and it displays all the attributes of that region as tooltip. Like this: https://snag.gy/3I7dnJ.jpg

Kindly let me know how to get it working.

-Deepak

**Comment by mbloch** [comment]
Mapshaper doesn't currently have a good way to add data properties to SVG. This could be added in the future.

You can probably find a solution using the current version of mapshaper.

I see that you were trying to use the "id" property to stash data values. This could work if you use the '-each' command to concatenate multiple values and use the concatenated values as your ids, like in the following snippet:

```
-each 'id = regionId + "|" + desc' -o id-field=id format=svg
```

Another solution would be to use the `id` property in the usual way, as a unique identifier for each feature. You would export your data as a separate file (e.g. using `-o format=json`) and use your feature ids to lookup the corresponding data values at run time.

**Comment by megharajdeepak** [comment]
Thanks Mathew.

-each 'id = regionId + "|" + desc' -o id-field=id format=svg

That can do the trick for me. I can use that. 

But I'm not able to get it work. I entered that in Export Menu's command line and selected 'SVG' and clicked on 'Export' button. I got this error:
"Unable to parse command line options"

Screenshots:
https://snag.gy/0Rskvu.jpg
https://snag.gy/6rROWv.jpg

am I missing something there?

**Comment by mbloch** [comment]
In the web UI, you have to use mapshaper's "console" to run the `-each` command.

If you paste the string I gave you (`-each 'id = regionId + "|" + desc' -o id-field=id format=svg`) in the console and hit enter, your browser should spit out an svg file with the path ids that you want. 

Or you could run `-each 'id = regionId + "|" + desc'` in the console and then use the export menu to generate your output file, remembering to add `id-field=id` to the "command line options" input box.

**Comment by megharajdeepak** [comment]
Awesome! that was neat and sweet. Worked like charm. Thank you so much.

**Comment by mbloch** [comment]
Seems that this issue was resolved, so closing (although we will probably want to revisit svg attribute data in the future)
