### ISSUE TITLE
Attribute names limited to 10 characters when saving dbf files

### ISSUE THREAD

**Issue by Ardibee** [mbloch/mapshaper#139]
When saving a dbf file, a max length of 10 characters is hard-coded in dbf-writer.js:
`var uniqFields = MapShaper.getUniqFieldNames(fields, 10);`

This means that attribute names longer than this get truncated, even though the rest of mapshaper handles longer attribute names just fine.  For example, using `-join` with a csv file of long-named attributes works if I look at the output with `-info`; however if I replace `-info` with `-o testfile.shp` I get truncated attribute names.  Can this limit be increased (to, say, 255 characters) or even removed?  Thanks.

**Comment by mbloch** [comment]
The 10-character limit is imposed by the DBF format.

See:
http://www.digitalpreservation.gov/formats/fdd/fdd000326.shtml
https://en.wikipedia.org/wiki/Shapefile#Limitations

**Comment by Ardibee** [comment]
Ah, fair enough :-)  
A good time for me to switch to GeoJSON or TopoJSON.
