### ISSUE TITLE
Command Line topojson overextends linestrings; GUI does not

### ISSUE THREAD

**Issue by andest01** [mbloch/mapshaper#140]
## Description
I have two `geojson` files that represent a a river and a subsection of the same river.
![image](https://cloud.githubusercontent.com/assets/1424223/17996606/8c748fb0-6b2f-11e6-8776-9512a8967d33.png)

![tworivers](https://cloud.githubusercontent.com/assets/1424223/17996397/3c5ea4ee-6b2e-11e6-8fc2-78962a75d440.png)
You can see that the blue subsection occupies the southern 80% of the green stream.

Running `mapshaper` in the command line sometimes causes odd behavior when saving to topojson. When simplifying two linestring geojson files, sometimes a smaller linestring is overextended to fit the entirety of its parent. This does not occur when using the GUI.

## Steps to Reproduce
1. Download these test files: [mapshaper test.zip](https://github.com/mbloch/mapshaper/files/438662/mapshaper.test.zip)
1. Run this command: `mapshaper -i  river.json river_section.json combine-files -o result.topo.json format=topojson`

## Observed Behavior
![image](https://cloud.githubusercontent.com/assets/1424223/17996544/3e9a4848-6b2f-11e6-8bdb-bb3ccf928838.png)
The blue subsection is over extended.

## Expected Behavior
The subsection remains in the southern 80% of the river.json file.

## Environment
`mapshaper --version`
`$ 0.3.30`

Operating System: Windows 10

## Notes
This works fine when adding these two files to the Mapshaper.org GUI and exporting as topojson. Also, this issue does not occur on the command line when exporting as geojson.

**Comment by andest01** [comment]
Behavior is consistent on OS X Yosemite.

**Comment by mbloch** [comment]
Thanks for reporting this :) 

I'll try to publish a fix later today.

**Comment by mbloch** [comment]
This problem should be fixed in v0.3.32

There was a bug in a function for merging adjacent lines without affecting topology -- it wasn't correctly handling the case of partially overlapping line features.

**Comment by andest01** [comment]
Updated to v0.3.32 yesterday. I was wrist deep in some refactoring and didn't get a chance to see the results of your work until just now.

I'm thrilled.

## BEFORE v0.3.32
<img width="946" alt="screen shot 2016-08-27 at 1 07 10 pm" src="https://cloud.githubusercontent.com/assets/1424223/18029235/415871f2-6c58-11e6-819f-02647e10435e.png">
Note the discrepency between the "ring" river indicator on the 265th Ave bridge at Mile 19 vs the Stream at Mile 19. The stream line suffered from the bug above.

## AFTER v0.3.32
<img width="898" alt="screen shot 2016-08-27 at 1 12 54 pm" src="https://cloud.githubusercontent.com/assets/1424223/18029249/84545278-6c58-11e6-9750-e3a7a45c49ae.png">
Absolutely perfect.

This project wouldn't have been possible without your project. 
❤️ Thank you so much.
