### ISSUE TITLE
Mapshaper outputs empty `geometries` array

### ISSUE THREAD

**Issue by tdooner** [mbloch/mapshaper#141]
Hey, thanks for making such a great general-purpose tool for dealing with shapefiles/geometry files. I've found it very helpful.

However, while rendering a lot of GeoJSON, I noticed that a few GeoJSON files that are output are GeometryCollections with an empty `geometries` array.

[Here is a Gist demonstrating this behavior.](https://gist.github.com/tdooner/8d0093535d10f5c7d67534a61c871cd2)

It appears that the bug appears for a particular value of the `precision` output option -- changing the precision option's value even slightly results in a valid simplified file.

Do you have any ideas why this might happen? Cheers!

**Comment by mbloch** [comment]
I see what's happening...

Some values of the `precision=` parameter can result in self-intersections in the output lines. Mapshaper tries to convert self-intersecting polygons to clean polygons, but the output from your sample dataset shows that the cleanup function is a bit buggy. When cleanup fails, mapshaper appears to generate null shapes.

If I disable the cleanup pass, your sample dataset looks like this after exporting with `precision=0.005`:
![image](https://cloud.githubusercontent.com/assets/1232222/18105774/b9e9ab36-6ece-11e6-9357-a8bcaee41e65.png)

If I export with `precision=0.01`, I get this:
![image](https://cloud.githubusercontent.com/assets/1232222/18105824/f2665b6c-6ece-11e6-90b6-dfe4a5b8983d.png)

You can see the tangle of intersecting lines in the first example -- that's what is causing the problem.

I should probably remove the cleanup pass, at least until I can make it more robust. Does that sound reasonable to you?

**Comment by tdooner** [comment]
Thanks for the quick reply. I suppose the top polygon (pre-simplification) would be better than nothing, but I feel like most people seeing a shape like that would still consider it buggy.

Unfortunately, I don't have a better suggestion. Right now, I am working around the problem by adding a bit of bruteforcing into my script to try different precision values.

Perhaps there is some kind of polygon math that can be added to the simplification step that removes those interior voids around the intersections? 😕

**Comment by mbloch** [comment]
Just to be clear, `precision` belongs to the `-o` (output) command -- it gets applied after simplification. Its purpose is to reduce the size of GeoJSON files by rounding the output coordinates. I generally use a value for precision that is small enough that map viewers can't see the difference between rounded and non-rounded coordinates.

Unless you really need to squeeze your files down to the smallest possible size, I would recommend using less rounding (or a smaller value for `precision`). If you want simpler-looking shapes, you can apply more simplification. The simplification command does a better job of avoiding self-intersections and other kinds of shape corruption than the rounding function used by `precision`.

**Comment by tdooner** [comment]
Okay, I think you have convinced me that I will manage to avoid this and have a better looking map by using more precise coordinates and a smaller percent of retained features. Thanks.

Though, I think this still is a bit of a gotcha for some users, so maybe worth at least adding the debug log like `[precision] Removed 1 self-overlapping polygon`, coupled with some documentation in the wiki? I'd be happy to write this if you think that is the best approach.

**Comment by mbloch** [comment]
I agree, there shouldn't be gotchas like this. I'll think a bit more about how best to handle this one.

Simplification can be tricky, with a lot of parameters to consider... better documentation is needed, for sure.

**Comment by christian-weiss** [comment]
When executing your statement with a more up-to-date version:
``` 
mapshaper -v
0.4.140
```
I no longer get an empty geometry:
```
{"type":"GeometryCollection", "geometries": [
{"type":"Polygon","coordinates":[[[-85.265,34.975],[-85.265,34.985],[-85.245,34.985],[-85.235,34.985],[-85.23,34.985],[-85.22,34.985],[-85.21,34.985],[-85.2,34.985],[-85.195,34.985],[-85.185,34.985],[-85.175,34.985],[-85.16,34.985],[-85.15,34.985],[-85.14,34.985],[-85.105,34.985],[-85.095,34.985],[-85.085,34.985],[-85.065,34.985],[-85.055,34.985],[-85.04,34.985],[-85.025,34.985],[-84.995,34.99],[-84.98,34.99],[-84.98,34.975],[-84.995,34.97],[-85,34.945],[-85,34.94],[-85,34.935],[-85.005,34.93],[-85.005,34.925],[-85.005,34.92],[-85.01,34.92],[-85.005,34.92],[-85.01,34.92],[-85.01,34.915],[-85.01,34.91],[-85.015,34.91],[-85.015,34.9],[-85.02,34.9],[-85.025,34.9],[-85.03,34.9],[-85.035,34.895],[-85.04,34.9],[-85.045,34.9],[-85.05,34.9],[-85.055,34.9],[-85.055,34.905],[-85.06,34.905],[-85.065,34.905],[-85.07,34.905],[-85.075,34.905],[-85.08,34.905],[-85.09,34.91],[-85.09,34.915],[-85.09,34.91],[-85.095,34.91],[-85.095,34.905],[-85.09,34.91],[-85.085,34.91],[-85.085,34.905],[-85.08,34.905],[-85.08,34.9],[-85.08,34.895],[-85.085,34.9],[-85.09,34.905],[-85.1,34.905],[-85.105,34.905],[-85.105,34.9],[-85.105,34.895],[-85.11,34.895],[-85.11,34.89],[-85.11,34.885],[-85.12,34.89],[-85.125,34.89],[-85.12,34.89],[-85.125,34.89],[-85.135,34.89],[-85.14,34.885],[-85.14,34.875],[-85.145,34.87],[-85.145,34.865],[-85.145,34.86],[-85.15,34.86],[-85.15,34.865],[-85.155,34.865],[-85.16,34.865],[-85.165,34.865],[-85.165,34.87],[-85.17,34.87],[-85.175,34.87],[-85.175,34.875],[-85.18,34.875],[-85.185,34.875],[-85.185,34.88],[-85.185,34.885],[-85.19,34.885],[-85.19,34.89],[-85.195,34.895],[-85.2,34.895],[-85.205,34.895],[-85.21,34.9],[-85.215,34.9],[-85.22,34.9],[-85.225,34.9],[-85.225,34.905],[-85.23,34.905],[-85.23,34.91],[-85.235,34.91],[-85.24,34.91],[-85.24,34.905],[-85.245,34.905],[-85.25,34.905],[-85.25,34.9],[-85.255,34.9],[-85.255,34.905],[-85.26,34.905],[-85.26,34.9],[-85.265,34.9],[-85.265,34.92],[-85.265,34.945],[-85.265,34.97],[-85.265,34.975]]]}
]}
```
Looks like first diagram in https://github.com/mbloch/mapshaper/issues/141#issuecomment-243572271 - better then an empty geometry, without forcing the user to experiment on precision value.

So the original problem of this ticket is solved. I think we should close this ticket.
Feel free to file a ticket about "self-overlapping".

**Comment by tdooner** [comment]
Great, thanks!
