### ISSUE TITLE
SVG export issue

### ISSUE THREAD

**Issue by nlemsieh** [mbloch/mapshaper#143]
Hi,
I got some missing regions when exporting a map to SVG, see screenshot:

![screen shot 2016-09-16 at 11 14 24 am](https://cloud.githubusercontent.com/assets/4103319/18582789/c8d48426-7bfe-11e6-92d5-c9cffae7f34a.png)

thanks

**Comment by mbloch** [comment]
Hi @nlemsieh, in order to investigate this issue, I'll need to be able to reproduce it myself. Can you send me a sample dataset and instructions for how to generate output that shows the missing path problem?

**Comment by mbloch** [comment]
Empty `<g>` tags could be the result of shapes being removed during simplification. Or it could be something else. Without more information, I'm closing this issue.
