### ISSUE TITLE
Map on the globe

### ISSUE THREAD

**Issue by OnkelTem** [mbloch/mapshaper#144]
First, I want to thank you for the great tool. Have discovered it only today and was really impressed on its console and transformation abilities. Now I have a question which is most likely has no any relation to mapshaper but I hope you folks may provide some help :) While all those projections serve their purposes good, I wish to display my custom json (which is actually data from Natural Earth) on a globe. Could you point me to an online tool which can do this AS EASY as mapshaper.org does. Simplification is another great option of mapshpaer so I'd dream of the same feature when working with a globe.

Thanks in advance!

**Comment by mbloch** [comment]
I don't know of such a tool... you might have to build it yourself! This demo could be a starting point:
http://bl.ocks.org/johan/1392966
