### ISSUE TITLE
Compatibility with new GeoJSON spec

### ISSUE THREAD

**Issue by mbloch** [mbloch/mapshaper#151]
https://tools.ietf.org/html/rfc7946

Mapshaper's GeoJSON output has a couple of areas of incompatibility with RFC7946:
1. The spec states that the winding order of Polygon rings must be counterclockwise for space-enclosing rings and clockwise for holes.
2.  In bounding boxes that cross the antimeridian, RFC7946 requires that `bbox[0] > bbox[2] == true`.

Item 2 represents a breaking change with the previous (2008) spec...  might be a good idea to see how other software handles the new bounding boxes before switching.

**Comment by tormi** [comment]
Also, according to [section 4](https://tools.ietf.org/html/rfc7946#section-4),

> The coordinate reference system for all GeoJSON coordinates is a
   geographic coordinate reference system, using the World Geodetic
   System 1984 (WGS 84) [WGS84] datum, with longitude and latitude units
   of decimal degrees.

**Comment by mbloch** [comment]
Good point, @tormi, there's also the WGS84 thing....

Currently, mapshaper will not automatically reproject into WGS84. You can reproject manually by running the command `-proj wgs84`, which is an alias for `-proj +proj=longlat +datum=WGS84`.

Mapshaper also does not perform antimeridian cutting (yet), which is included in the new spec as something that "should" be done.

In spite of what the spec says, some users will want to generate GeoJSON files in coordinate systems other than WGS84, so mapshaper is not going to force RFC7946 compliance.

Eventually, RFC7946 compliance will probably be the default option for GeoJSON output (including automatic reprojection if needed).

As a first step, I may add a flag to the output command, e.g. `-o rfc7946`, for generating compliant output.

**Comment by mbloch** [comment]
v0.4.41 adds the `-o rfc7946` option. Instead of automatically reprojecting non-WGS84 datasets, this update prints a warning and suggests running `-proj wgs84`. CCW outer/CW inner ring wrapping, antimeridian-spanning bboxes and default 6-decimal coordinate precision are used.

**Comment by nvkelso** [comment]
Well played

**Comment by ralyodio** [comment]
i get an error when using `-o rfc7946`

```
$ mapshaper World_Countries_Generalized.shp -o rfc7946 countries.geojson
Error: [o] Command takes one file or directory argument. Received: rfc7946 countries.geojson
Run mapshaper -h to view help
```

please update docs on how to generate rfc7946 compliant geojson

**Comment by mbloch** [comment]
RFC 7946 refers to the current GeoJSON specification. The output option `rfc7946` is no longer supported, or needed. Mapshaper generates RFC 7946 compliant GeoJSON by default. According to the Wiki: 
```
Mapshaper's default GeoJSON output is now compatible with the current specification (RFC 7946)
```
How would you like me to update the docs?

**Comment by ralyodio** [comment]
I get an error about right hand something or other when I validate the geojson mapshaper produces. It’s not working with surrealdb- Anthony(408) 656-2473 On Dec 22, 2023, at 9:28 AM, Matthew Bloch ***@***.***> wrote:﻿
RFC 7946 refers to the current GeoJSON specification. The output option rfc7946 is no longer supported, or needed. Mapshaper generates RFC 7946 compliant GeoJSON by default. According to the Wiki:
Mapshaper's default GeoJSON output is now compatible with the current specification (RFC 7946)

How would you like me to update the docs?

**Comment by mbloch** [comment]
I'll need some more information from you to investigate this. I generated several GeoJSON output files using the latest version of the CLI and the web UI (`v0.6.59`) and they all passed validation using [this tool](https://github.com/mapbox/geojsonhint), which checks the "right hand rule", among other things. Can you send me a GeoJSON file that causes validation errors and problems with surrealdb? It would also help if you sent me the mapshaper commands that you used to generate the file. Thanks!

**Comment by ralyodio** [comment]
well now its validating. Thanks. I must have created it incorrectly.
