### ISSUE TITLE
mapshaper-cli doesn't accept zipped shapefiles as input

### ISSUE THREAD

**Issue by amenadiel** [mbloch/mapshaper#152]
It says 

> Error: Unkown file type

However, the web-ui explicitly states that they are supported.

I meant to transform several zipped shapefiles into geojson, and they have not only geometries but properties as well (DBF files), so I wanted to keep them zipped.

I don't know if I should unzip them, feed them to mapshaper-cli, or make a script to use the web-ui from the command line.

**Comment by mbloch** [comment]
I'm not eager to build support for unzipping into the cli...  I expect that most people who do command line GIS work already will already have a good program for opening .zip files installed on their systems. Have you considered writing a shell script or Makefile that first unzips and then mapshaperizes your data files?

**Comment by mbloch** [comment]
Since no one else has chimed in to argue for Zip file support in the cli, I'm closing this issue. Thanks for your feedback, @amenadiel, I'll remember your vote for .zip support if the question comes up again.
