### ISSUE TITLE
Simplification of a set of polygons with a super-set of polygons and keeping topology

### ISSUE THREAD

**Issue by mhabets** [mbloch/mapshaper#153]
I have 2 polygon shapefiles: 1 for district level and 1 for province level (which is a super-set of the former with different attribute).
I would like to simplify both and keep the topology between the 2 files.
I first thought the `combine-files` option would be the solution:
```
mapshaper -i polygon_set.shp polygon_superset.shp combine-files -simplify 2% -o
```

Unfortunately the resulting simplified files don't respect topology between them. I guess I don't quite understand the aim of the `combine-files` option.

BTW: is there any easy way to simplify 2 files and keeping the topology between the 2?
I know I still can create back the province level geometries by dissolving the simplified district level geometries. Isn't there any more straightforward way?

**Comment by mbloch** [comment]
I just fixed a bug that was introduced on Nov. 11. The `combine-files` option caused topology to be ignored. Could you try running your command again, after updating to v0.3.40? If one file is an exact superset of the other, your output should be correct now. Thanks for reporting this!

--mbloch

**Comment by mhabets** [comment]
It works like a charm now!
many thanks
