### ISSUE TITLE
Feature request: conditional simplification values

### ISSUE THREAD

**Issue by roberthorn** [mbloch/mapshaper#154]
Would it be possible to conditionally apply simplification percentages based on a feature field value? 

Example: if I'm simplifying shapes from OSM in a single file and want to simplify country level shapes (admin_level = 2) keeping 20% of removable vertices, state level shapes (admin_level = 4) 50%, and not simplify county/city level shapes at all.

**Comment by mbloch** [comment]
Hi, sorry about the slow reply... I've been going back and forth on this... on the one hand, it seems a bit niche ... and you could accomplish the same thing by splitting your source file into temp files by feature type, simplifying these files separately and then re-combining the files (guessing you're currently doing it this way). On the other hand, it's a fun feature that could be supported directly. Are you still interested in this feature?

**Comment by nvkelso** [comment]
I also find this interesting.

**Comment by ARSimmons** [comment]
I have been working on this problem specifically (in python - using shapely/fiona instead of mapshaper). I am nearly complete (just have to finish the interior rings code). Prelim testing has been going well.

If you are curious. 

https://github.com/ARSimmons/Simplify_with_Topology

**Comment by roberthorn** [comment]
@mbloch I don't explicitly need this feature anymore, but I think it would be cool to see implemented. I was splitting my source files and simplifying each, just thought this would be more convenient if a lot of other people are also dealing with this problem.

**Comment by mbloch** [comment]
I have one question about this feature -- if there are two adjacent polygons with different levels of simplification, which metric should be applied to the shared boundary between the shapes ? Would it make sense to apply the lower of the two simplification metrics to the shared boundary?

**Comment by roberthorn** [comment]
That sounds good to me.

Looking at the repo @ARSimmons shared above, seems she's doing the average for shared boundaries, may be a better compromise for adjacent polygons with a larger difference in simplification level.

**Comment by nvkelso** [comment]
> Would it make sense to apply the lesser of the two simplification levels to the shared boundary?

Yes. If it's a member of a shape that should be simplified _less_ than it's neighbour, the smaller simplification amount should be used.

**Comment by mbloch** [comment]
Commit 917d5830c4376afb4bc32d25498 adds variable simplification amounts. To use this feature, add the `variable` flag to the `-simplify`, and pass an expression as the value of `resolution=`, `percentage=` or `interval=` instead of a literal value. The expression could be the name of a data field that contains the simplification value for each feature, a ternary expression, or another expression of the kind used by the `-each` command. This feature will be included in the next release.

**Comment by mbloch** [comment]
added in v0.4.100

**Comment by asimmonsAF** [comment]
> Commit [3dc93da](https://github.com/mbloch/mapshaper/commit/3dc93da71bb557e37b58b38e3ba7672a8e54a7de) adds variable simplification amounts. To use this feature, add the `variable` flag to the `-simplify` command, and pass an expression as the value of `resolution=`, `percentage=` or `interval=` instead of a literal value. The expression could be the name of a data field that contains the simplification value for each feature, a ternary expression, or another expression of the kind used by the `-each` command. This feature will be included in the next release.
> 
> Example
> 
> ```
> -simplify variable resolution='this.area < 1e8 ? 20000 : 10000'
> ```

![image](https://github.com/mbloch/mapshaper/assets/146278369/6a1b3985-42

I'm not able to figure out how to run this command properly...my field with 500 or 1000 or 2000 (type = long) data is called 'simp_perc'...does that go where 'this.area ' goes? Can you maybe give me a full example?
