### ISSUE TITLE
Copy attributes for different output geometries

### ISSUE THREAD

**Issue by imelnych** [mbloch/mapshaper#157]
Is there a way I could copy attributes when using `-lines`? I have seen a workaround in [this issue](https://github.com/mbloch/mapshaper/issues/138) for other geometries, but lines (obviously) can't get their ids directly from attributes. 

It would be great to have an option to copy attributes (to any destination geometry), because with SVGs for example I loose all attributes except style.

**Comment by mbloch** [comment]
Polygon attributes currently aren't copied because the output from the `-lines` can contain boundary lines between polygons with different attributes. Which attribute values would you assign to a line if it represents the boundary between two polygons?

Can you give some more details about the problem that you are working on? That would help me to think about possible solutions.

**Comment by imelnych** [comment]
I want to build a map with bezier curves instead of polylines. If I had attributes available in some way, I could generate the svg and the do some processing to turn polyline paths into path with curves, and then restore polylines them based on attribute values. E.g. qgis makes adds suffixes when there are duplicate attributes. 

Apart from this (hacky) solution for smooth borders, I also have some other data which I want to have in my SVG.

**Comment by mbloch** [comment]
Haven't heard back from @imelnych, so closing.

**Comment by imelnych** [comment]
I am not working on anything that requires this feature anymore, but what I needed was to generate an SVG with various metadata in path attributes to be able to use it from JS and CSS. 

Say you have a map with subdivisions of some sort and some unchanging data like postal codes, area or rough population per each subdivision. So when the user hovers over them I would have a tool tip with that data. I wanted to store those values in attributes, but there was apparently no way of passing them.

**Comment by mbloch** [comment]
This sounds similar to issue #199. There, I suggested adding an option to the `-o` command that would add one or more data attributes to SVG paths and point symbols. I plan to add this kind of feature at some point.
