### ISSUE TITLE
feature request: -quiet

### ISSUE THREAD

**Issue by fitnr** [mbloch/mapshaper#158]
It would be great to have a `-quiet` option that suppressed logging to stderr except for errors.

I'm using mapshaper on the command line as part of a pipeline that processes tens of thousands of files. It works great! However since mapshaper prints the names of all the files it creates, I have to choose between an overloaded logging window or redirecting stderr to `/dev/null`. Then I miss any errors (which are my fault, mapshaper is great).

**Comment by mbloch** [comment]
Good suggestion, I'll plan to add `-quiet` for the next release.

**Comment by mbloch** [comment]
I added a `-quiet` command to v0.4.0 (just published). It inhibits normal logging messages but still displays errors.
