### ISSUE TITLE
Is it possible to pass buffer directly to MapShapper programmatically?

### ISSUE THREAD

**Issue by TehNrd** [mbloch/mapshaper#159]
I looked through the source code where it does all the input type detection and I think the answer to this question is no, but I figured it couldn't hurt for a quick confirmation as I could have missed something.

If I pull a Shape File form a remote source (S3) and that result comes back as a raw buffer stored in a variable, can I pass this directly into the node interface of mapshapper? Or must I write this buffer/file to disk and then pass in a command to map shaper to read the file from disk? Preferably I'd never write to disk for performance reasons.

Thanks.

**Comment by mbloch** [comment]
Currently there's no way to avoid writing to disk, but I'm working on addressing this for v0.4.0...  hope to have the new release ready in about a week, so stay tuned :)

**Comment by TehNrd** [comment]
Oh wow! Cool, keep up the great work! I know people in the geo space really appreciate this tool.

**Comment by mbloch** [comment]
The just-released v0.4.2 supports importing Buffer objects (typically, the contents of .shp and .dbf files).

You can use the `applyCommands()` api function (see my comment [here](https://github.com/mbloch/mapshaper/issues/95#issuecomment-274526208)).

**Comment by TehNrd** [comment]
API changes make sense and looks great. Is it a matter of simply setting the dbf and shp file as `-i` inputs. Is mapshapper smart enough to know those go together? Or shoud `-i` be a zip file with the buffer being a buffer of a zip file containing all components of a shapefile?

**Comment by mbloch** [comment]
Ah, good question, I'll have to document this more clearly. Currently only the web UI supports Zip files. You should only give the shp as input to `-i`. If a matching dbf file is available, mapshaper will also import that. Without a dbf file, you'll get shapes but no attribute data.

**Comment by TehNrd** [comment]
But if the Shapefile is a buffer in memory how will mapshapper know where to look for the dbf, and perhaps the other dependent shape files?

**Comment by mbloch** [comment]
Add the dbf buffer to the object containing input data that you use as the second argument to `applyCommands()`. Here's an example adapted from one of mapshaper's tests:

```
var fs = require('fs');
var shpBuf = fs.readFileSync('test/test_data/three_points.shp');
var dbfBuf = fs.readFileSync('test/test_data/three_points.dbf');
var input = {
   'points.shp': shpBuf,
   'points.dbf': dbfBuf
};

// convert Shapefile to GeoJSON
api.applyCommands('-i points.shp -o format=geojson', input, function(err, output) {
   // output is {'points.json': <GeoJSON>}
});

```

**Comment by mbloch** [comment]
This behavior is analogous to the way that the command line program works -- you give the name of the `.shp` file to the `-i` command, and mapshaper checks for a dbf, prj and .cpg file and loads these auxiliary files if present.

**Comment by TehNrd** [comment]
Ah, perfect! Thanks so much for the little example.
