### ISSUE TITLE
filtered .shp output "empty" files

### ISSUE THREAD

**Issue by pyrog** [mbloch/mapshaper#165]
```
mapshaper -i test.shp -filter 'ID=="FR3300003"' -o data/test.geojson
[filter] Retained 1 of 14 features
Wrote data/test.geojson
```
Work fine 😄 

```
$ mapshaper -i N_ENP_PN_S_000.shp -filter 'ID_MNHN=="FR3300003"' -o data/test.shp
[filter] Retained 1 of 14 features
Wrote data/test.shp
Wrote data/test.shx
Wrote data/test.dbf
Wrote data/test.prj
```
Generate binary files (containing `[object ArrayBuffer]`) 😞 
Only `.prj` is valid 

node v7.5.0
macOS Sierra 10.12.3 (16D32)

**Comment by mbloch** [comment]
Thanks for reporting this...  I made a small mistake with big consequences ;)

I just published v0.4.3, which should fix the problem.
