### ISSUE TITLE
Add support for GPX files

### ISSUE THREAD

**Issue by niroyb** [mbloch/mapshaper#167]
GPX is a common format of GPS devices.
There are existing tools that convert gpx to geojson like https://github.com/mapbox/togeojson
It could then follow the same ingestion code path.

**Comment by mbloch** [comment]
Hi, just to be clear, are you suggesting that mapshaper should add support for importing GPX directly and use `togeojson` internally to perform the conversion?  Would this be much more convenient that using `togeojson` externally to convert GPX to GeoJSON before importing?

**Comment by mbloch** [comment]
I'm going to vote "no" on this feature... thanks for contributing this suggestion, I'll remember it if the question of GPX support comes up again.
