### ISSUE TITLE
SHP to GeoJSON - string length error

### ISSUE THREAD

**Issue by nitrag** [mbloch/mapshaper#170]
First off, fantastic work here and thank you for the effort in making a great tool for the GIS community!

I'm getting an error which I can't seem to troubleshoot to the source. It comes down to a string formatting issue and I'd just like it to be skipped.

```
wget -N <file>
unzip -o <file>.zip

#using max_old_space_size to boost ram and not kill the program on hitting memory limit
node --max_old_space_size=1500 `which mapshaper` -i <file>.shp -simplify dp 33% -verbose -o format=geojson <fileout>.geojson

- 16149ms -i
[simplify] Repaired 1,203 intersections; 4,309 intersections could not be repaired
- 44123ms -simplify
Detected DBF text encoding: win1252
Sample text containing non-ascii characters:  PELOTÓN DE FUSILAMIENTO
Skipping a collapsed polyline path
Skipping a collapsed polyline path
Skipping a collapsed polyline path
Skipping a collapsed polyline path
Skipping a collapsed polyline path
Skipping a collapsed polyline path
Skipping a collapsed polyline path
Skipping a collapsed polyline path
Skipping a collapsed polyline path
Skipping a collapsed polyline path
- 1130577ms -o
/home/nitrag/.nvm/versions/node/v4.3.2/lib/node_modules/mapshaper/mapshaper.js:1575
    throw err;
    ^

RangeError: Invalid string length
    at Array.join (native)
    at Object.MapShaper.exportGeoJSONCollection (/home/nitrag/.nvm/versions/node/v4.3.2/lib/node_modules/mapshaper/mapshaper.js:10279:72)
    at /home/nitrag/.nvm/versions/node/v4.3.2/lib/node_modules/mapshaper/mapshaper.js:10212:26
    at Array.map (native)
    at MapShaper.exportGeoJSON (/home/nitrag/.nvm/versions/node/v4.3.2/lib/node_modules/mapshaper/mapshaper.js:10210:25)
    at Object.MapShaper.exportFileContent (/home/nitrag/.nvm/versions/node/v4.3.2/lib/node_modules/mapshaper/mapshaper.js:12720:11)
    at /home/nitrag/.nvm/versions/node/v4.3.2/lib/node_modules/mapshaper/mapshaper.js:12672:28
    at Array.reduce (native)
    at Object.MapShaper.exportDatasets (/home/nitrag/.nvm/versions/node/v4.3.2/lib/node_modules/mapshaper/mapshaper.js:12671:20)
    at Object.MapShaper.exportTargetLayers (/home/nitrag/.nvm/versions/node/v4.3.2/lib/node_modules/mapshaper/mapshaper.js:12644:20)
```

**Comment by nitrag** [comment]
Dangit, just saw https://github.com/mbloch/mapshaper/issues/97

Will look into a solution based on this.

**Comment by mbloch** [comment]
I haven't prioritized output of GeoJSON, partly because I generally use the Shapefile format for really large datasets.

There are a few more things that you can do to get the size of your output GeoJSON down, in addition to line simplification.

One is to reduce the precision of the output coordinates. You should be fine with 5 decimal digits of precision (the default output has 14 or 15 digits, which is way more than you need).

If you don't need all of the data fields in your input Shapefile, you can drop unneeded fields using the `-filter-fields` command.

Using a combination of simplification, reduced coordinate precision and filtering fields, I got the size of your file down to about 125 MB.

Here's the command I used... hope this helps!
```bash
mapshaper S_USA.Road_MVUM.shp -simplify dp 33% no-repair -filter-fields NAME -o roads.geojson precision=0.00001
```

**Comment by nitrag** [comment]
Oh excellent, this is much better.

Only suggestion is in the docs make the filtering examples a little clearer. You say "Javascript Expressions" but I see single `=` and `,` between commands (which I'm still not sure what those do. I used `==` and `!=` as needed and used `||` for an OR statement. Works great!:
```
-filter 'col1=="abc" || col2!="xyz"'
```

Such a great tool, thanks again!

**Comment by mbloch** [comment]
I've counted your vote for better documentation ;)

When I get a chance, I'll add a couple of examples to the `-filter` entry in the command reference, instead of just referring to `-each` (I'm assuming you saw the `=` and `,` operators in the `-each` examples).
