### ISSUE TITLE
svg MultiPolygon becomes <g>, but I prefer <path>

### ISSUE THREAD

**Issue by adamhooper** [mbloch/mapshaper#173]
Hi there! Fantastic tool -- probably my new go-to.

I have a nit with the SVG output, though. `Polygon` transforms to `<path>`, which is great. But `MultiPolygon` becomes `<g>`. That's annoying because a typical Shapefile contains objects such as "regions" -- and when I'm thinking of "regions" I don't care whether they're Polygons or MultiPolygons.

Practically:

* I'd like to write selectors like `path`. But I end up needing to write `path, g` or `g#layername>*` (which are more verbose than I'd like) or `.className` (which isn't what I'm going for).
* I'd like a minimal DOM, so I can manipulate it quickly and with less code.
* And I'd maybe want to write JavaScript that parses the `d` attribute on a `path`.

Don't get me wrong: `<g>`s don't prohibit these tasks. They just make these tasks take more brainpower, and they make testing harder. Can't mapshaper just nix all the `<g>`s and concatenate the `d` attributes into a single `<path>`?

I'm willing to make a pull request, but I worry about backwards compatibility: perhaps some users rely on these `<g>` elements I so despise. How should I proceed?

**Comment by mbloch** [comment]
I agree that it is preferable to convert MultiPolygons to single SVG path elements, as long as they get rendered correctly. I checked Chrome, Firefox and Adobe Illustrator, and didn't see any problems. Commit 447e08c43b16b23 has the update. This change should be included in the next release, in a day or two.

**Comment by gagan-bansal** [comment]
@adamhooper You can try [geojson2svg](https://github.com/gagan-bansal/geojson2svg) this converts to path as well as. 
But mapshaper is complete framework, suitable for many purpose. Please check how you can fit geojson2svg in your workflow.

**Comment by mbloch** [comment]
v0.4.10 includes the requested change.

**Comment by adamhooper** [comment]
Wow, that was fast! Thanks, @mbloch.
