### ISSUE TITLE
-proj fails

### ISSUE THREAD

**Issue by Monduiz** [mbloch/mapshaper#176]
I have a GeoJSON with a proj4 like so: +proj=longlat +datum=WGS84

I am trying to convert it to webmercator with: 
    mapshaper <file.geojson> -proj webmercator -o <newfile.geojson>

I am getting a proj4: unknown.

Is there something I am missing? The file is an extract from OSM and converted with osmtogeojson.

**Comment by mbloch** [comment]
Hi, thanks for getting in touch.

Could you email me some more details about the error you're seeing?  I'd like to know what version of mapshaper you're using, how you installed mapshaper, your version of Node and your OS. Also, could you attach a screenshot of your terminal, showing the error?

When I tried to replicate the error using a GeoJSON file generated by osmtogeojson, mapshaper ran your command correctly, so I'll need more information in order to find out what happened.

**Comment by Monduiz** [comment]
Hello, 

I am running version 0.4.2.  I installed it with node version 7.4.0. I am on macOS 10.11.6

I don't get an error per se. When I run the command it completes but when I use -info, the projection is unknown. When I import the file into R, I have problems there and  I have to fix it. In R, the file has an original projection of longlat.

![screen shot 2017-02-26 at 9 27 04 pm](https://cloud.githubusercontent.com/assets/8759714/23346686/72cb15c6-fc6a-11e6-887a-fe994cca6bdf.png)

**Comment by mbloch** [comment]
I think I see what's happening.... Mapshaper doesn't save projection data in the output GeoJSON file, so when you re-open the projected file in mapshaper, the -info command displays "Proj.4: unknown". If you run "-info" after "-proj", you will see a Proj.4 string for the new projection (Like this: "mapshaper MutBuildW.geojson -proj webmercator -info").

If you want to use a projected GeoJSON file in R or other software, you'll need to find another way to tell your software what projection you're using.

**Comment by Monduiz** [comment]
Thanks for looking into this. I thought I could change the projection and save as a new projected file this way. I can do it in R with rgeos though.

**Comment by mbloch** [comment]
I will have a look at `rgeos` and see how it handles projected data. It may use the (deprecated) GeoJSON "crs" property to associate projection information with a GeoJSON file. I considered adding "crs" support to mapshaper, but changed my mind after the GeoJSON spec was updated to remove support for projected datasets.

Thanks for calling attention to this issue :)

**Comment by Monduiz** [comment]
Matt, with rgeos, I do this to change the projection:

    spTransform(Mut, CRS("+init=epsg:3857"))
