### ISSUE TITLE
Split GeoJSON file to it's underlying geometry layers

### ISSUE THREAD

**Issue by terranceteoh** [mbloch/mapshaper#177]
Hi,

I have a test.geojson file with the following geometry in it:

1. "type": "Polygon",
2. "type": "LineString",
3. "type": "Point",

Is there a way to to extract just one geometry type out into a new geojson file?
e.g.  

1. test_Polygon.geojson, or
2. test_LineString.geojson, or
3. test_Point.geojson, or

My best try is using:  mapshaper test.geojson -split -o format=geojson
But I got a whole bunch of outputs.
I am hoping to get a specific geometry type.

Thanks !

**Comment by mbloch** [comment]
Here's one way you can separate different geometry types. Make sure you're using the current version -- support for GeoJSON with multiple types is fairly new.
```
# Example: split test.geojson into three files: polygons.json, linestrings.json and points.json
mapshaper test.geojson -rename-layers polygons,linestrings,points -o
```
Explanation: mapshaper imports each geometry type into a separate layer, each with the same name ("test" in this example). The `-rename-layers` commands assigns meaningful names to the imported layers. You have to make sure that names you give are assigned to the correct layers. Run the `-info` command to find out the order in which mapshaper imported each feature type.

**Comment by mbloch** [comment]
If you want to extract just one type, you can do it this way:
```bash
mapshaper test.geojson -o polygons.json target=1
```
Here, `target=1` selects the first layer, so you need to find out the number of the layer you want using `-info`.

**Comment by terranceteoh** [comment]
Thank you.  
It is working great !

I am using the following options:

1. mapshaper test.geojson -o test_polygons.geojson target=1
2. mapshaper test.geojson -o test_lines.geojson target=2
3. mapshaper test.geojson -o test_points.geojson target=3

**Comment by terranceteoh** [comment]
Looks like I can't do this:

mapshaper test.geojson -o test_polygons.geojson target=1
mapshaper test.geojson -o test_lines.geojson target=2
mapshaper test.geojson -o test_points.geojson target=3

As terget=1 might sometimes be lines or points, not always polygons.
Likewise for target=2 and target=3.

Any fix where I can extract only for polygons for example ?

Thanks !

**Comment by mbloch** [comment]
The output from `-info` tells you the type and number of each layer. (Usage: `mapshaper test.geojson -info`).

**Comment by mbloch** [comment]
Re-reading this issue, I can see that it would be useful to be able to know the geometry type of imported GeoJSON layers without using `-info`, for users who want to script their GeoJSON processing. We can keep this issue open until we find a good solution.

**Comment by terranceteoh** [comment]
Thanks, that sould help alot!  
Currently I am writing a Shell script to grep for the geometry type and rename my files after the split.

**Comment by mbloch** [comment]
v0.4.32 adds a `type=` option to the `-target` command, which could be used to solve the problem  we were discussing above. As an example, to export just points from a GeoJSON file containing multiple geometries, you could do this:

```
mapshaper test.geojson -target type=point -o test_points.geojson
```

**Comment by terranceteoh** [comment]
Cool !  Thanks !
