### ISSUE TITLE
Data column being parsed as numerical despite -field-types:field_name:str tag

### ISSUE THREAD

**Issue by LoneElectron** [mbloch/mapshaper#178]
In trying to join two files on zip code keys, one of these key fields is being parsed as a numerical value, while the other is being parsed as a string. This causes every record with a leading zero in the zip code to fail to join, as the leading zero is being deleted in one of the files, but not in the other. Even when using -field-types:field_name:str , mapshaper is still parsing the column as an integer.

Using -field-types:field_name:num on the fields doesn't seem to have an affect on how the files are being parsed either.

**Comment by mbloch** [comment]
Hi,
The `field-types` option should be used like this: `field-types=field_name:str`. You wrote `field-types:field_name:str` above. Could you check to see if this is the issue? If not, could you send me the text of the full command that you were using?

I noticed that mapshaper doesn't trigger an error if you use `field-types:field-name:str`, but it should. I'll get that fixed.

**Comment by mbloch** [comment]
Commit b417f9917a743dcf49bc  improves command line validation a bit. This particular issue would trigger a useful error message. In the future, I'd like to do a better job of checking command line syntax...
