### ISSUE TITLE
GeoJSON to SHP - Feature Order

### ISSUE THREAD

**Issue by tjb8907** [mbloch/mapshaper#183]
I am using you program to convert a GeoJson to shapefile and have a couple questions. 

First, is there a way to reorder the features? Say I have a square with 2 circles laid on top the square (my actual shapes are more complex). If i do it a certain way (draw the square last) in the program that is generating the GeoJson it works and the circles show on top of the square in the shapefile however sometimes I cant draw them in the same order. So i need to do 1 of two things. Somehow i need to reorder them, or have the area of the square removed that is behind the circles. 
Hopefully that makes sense...

Are either of these possible to do with console commands now?

Also, is there anyway to add attributes to each feature? When I import the GeoJSON it shows up with 1 attribute names FID (Feature ID I assume) and starts at 0 and goes up for each feature. I want to add another attribute (or column in shapefile terms) and manually add a value for each feature. I figured out how

Before I attempt to modify any code I figured I'd see if I was missing something.

**Comment by mbloch** [comment]
You can reorder features using the `-sort` command. Sort by area: `-sort 'this.area'`. Run `mapshaper -h sort` to see all the options or read the wiki: https://github.com/mbloch/mapshaper/wiki/Command-Reference#-sort

One way to add a property to a particular feature is to target the feature using the `where=` option of the `-each` command, like this:
`-each 'shape="square"' where='this.id == 0'` See the wiki for more info.

**Comment by tjb8907** [comment]
Perfect! I will read up some more! Thanks much!

**Comment by mbloch** [comment]
If you can imagine a more useful command line syntax, please share your ideas :)
