### ISSUE TITLE
Extact Lat-Long from a ShapeFile

### ISSUE THREAD

**Issue by inderz** [mbloch/mapshaper#190]
Hi I created a TopoJSON file from the Shapefile attached as places.zip.

It worked fine but the Lat Long coordinates of each location, though visible in Mapshaper window, I can't seem to extract for my use ! The screenshot is attached.

Pl guide me.

Thx
Inder

![2017-07-02 12_16_16-mapshaper](https://user-images.githubusercontent.com/16438356/27767832-b2438660-5f21-11e7-9815-decbbe00ad62.png)

[places.zip](https://github.com/mbloch/mapshaper/files/1117652/places.zip)

**Comment by inderz** [comment]
Got it ! Used QGIS for the same to extract the coordinates.

Thx 
Inder

**Comment by mbloch** [comment]
if you click the map, the coordinates should get highlighted. You can save the coords to the clipboard using the standard keyboard shortcut while the coords are highlighted.

**Comment by inderz** [comment]
Thx. But with over 5000 coordinates, clipboard wasn't an option.

I used the shapefile in QGIS.

Used Geometry Tools and saved a new Shapefile with Lat & Long ! Nice !

Thx
Inder

**Comment by mbloch** [comment]
Since you found a solution, I won't go into detail... but you could use the mapshaper `-each` command to do this as well. There is documentation in the command reference page of the wiki.

**Comment by inderz** [comment]
Thx Mathew, I'll certainly go through the solution. Seems to be a very
useful one.

Cheers
