### ISSUE TITLE
Clipping a large SHP file breaks on `Cannot read property 'reduce' of null`

### ISSUE THREAD

**Issue by wilson428** [mbloch/mapshaper#192]
I'm trying to determine which U.S. roads are in the umbra zone of the upcoming eclipse. NASA has [SHP files of the eclipse zone](https://svs.gsfc.nasa.gov/vis/a000000/a004500/a004518/eclipse2017_shapefiles.zip) (You want `upath17.shp`) and the DOT has a [large SHP file of all roads](https://www.fhwa.dot.gov/planning/processes/tools/nhpn/2015/nhpnv14-05shp.zip).

When I try a simple `-clip` command, I get an error on line 8534 of mapshaper.js:

`node --max_old_space_size=4096 $(which mapshaper) NHPNLine.shp -clip upath17.shp -o umbra_roads.shp`
```
TypeError: Cannot read property 'reduce' of null
    at clipPolyline (/Users/cwilson1130/mapshaper/mapshaper.js:8534:22)
    at /Users/cwilson1130/mapshaper/mapshaper.js:8530:12
    at Array.map (native)
    at Object.internal.clipPolylines (/Users/cwilson1130/mapshaper/mapshaper.js:8529:23)
    at Object.internal.clipLayerByLayer (/Users/cwilson1130/mapshaper/mapshaper.js:9137:30)
    at /Users/cwilson1130/mapshaper/mapshaper.js:9099:26
    at Array.reduce (native)
    at Object.internal.clipLayersByLayer (/Users/cwilson1130/mapshaper/mapshaper.js:9092:23)
    at Object.internal.clipLayers (/Users/cwilson1130/mapshaper/mapshaper.js:9073:27)
    at Object.api.clipLayers (/Users/cwilson1130/mapshaper/mapshaper.js:9009:19)
```
I tried reducing the roads file to just the states through which the eclipse passes, with no luck. When I load the NHPNLine.shp file on mapshaper.org, I do see a fair number of intersections. But I'm reluctant to simplify this file since I don't want to adulterate official government data.

Are the intersections likely causing the problem? Any way to fix them with minimal change to the source file?

**Comment by mbloch** [comment]
Thanks for the detailed report -- I'll check it out.

**Comment by wilson428** [comment]
Thanks, Matthew!

**Comment by mbloch** [comment]
@wilson428, I just published v.0.4.28, which fixes the clipping bug (it affected line layers containing one or more null geometries).

You'll have to add an `encoding=` option to get the command to run successfully, like this: `mapshaper NHPNLine.shp encoding=ascii -clip upath17.shp -o umbra_roads.shp`

Without the `encoding=` option, mapshaper tries to auto-detect the text encoding of the .dbf file. One of the values in the `LNAME` field of the `NHPNLine.dbf` file is corrupted, which causes mapshaper's encoding detection to fail.

Thanks for reporting this bug :)

**Comment by wilson428** [comment]
Works brilliantly! Thanks so much for the fast response. Closing.
