### ISSUE TITLE
how to use "-proj  from=" commond

### ISSUE THREAD

**Issue by yancongwen** [mbloch/mapshaper#194]
I have a geojson file,and I know its proj, I want to get shpfiles includ .proj. I commonded such as this:
`mapshaper wuhan_ejdl.json -proj +proj=longlat +datum=WGS84 +no_defs from= +proj=tmerc +lat_0=0 +lon_0=114 +k=1.000000 +x_0=500000 +y_0=0 +ellps=krass +units=m +no_defs -o`

but i get:
`Error: [proj] Unable to project -- source coordinate system is unknown`

how can I defined the source coordinate system? how to use "-proj  from=" commond?

**Comment by mbloch** [comment]
You just need to add quotes the `from=` argument, like this:
```
mapshaper wuhan_ejdl.shp -proj +proj=longlat +datum=WGS84 +no_defs from='+proj=tmerc +lat_0=0 +lon_0=114 +k=1.000000 +x_0=500000 +y_0=0 +ellps=krass +units=m +no_defs'
```

**Comment by yancongwen** [comment]
Thanks! Your project have give me a great help!

**Comment by mbloch** [comment]
Glad this helped :)

**Comment by kennycason** [comment]
I spent over a day trying to figure this out. Thanks a lot. I think this example (or something similar) would be super helpful on the README. Particularly, projecting to `+proj=longlat +datum=WGS84 +no_defs`, from some projection seems like something would be a common use-case for projections. 
also, i love your tool!
