### ISSUE TITLE
Can mapshaper be used as library? 

### ISSUE THREAD

**Issue by kochizufan** [mbloch/mapshaper#196]
Hi, I tried http://mapshaper.org/ and surprised how quick this tool found self-intersection points in large geojson files.

I want to use this function in my codes, but is this function can be used not as web GUI or command line but as library?
If can, are there any sample?

Regards,
Kohei

**Comment by mbloch** [comment]
The file `test/segment-intersection-test.js` shows how to use several internal functions to generate intersection data from arrays of [x, y] coordinates.

https://github.com/mbloch/mapshaper/blob/master/test/segment-intersection-test.js

I've thought about adding an option to the `-points` command to generate a layer containing line intersections that you could output as GeoJSON or another format... would that be useful to you? That would be more dependable that calling internal functions (which might change without warning between versions).

**Comment by mbloch** [comment]
Question answered, closing
