### ISSUE TITLE
Import error for mapshaper.org

### ISSUE THREAD

**Issue by mtdukes** [mbloch/mapshaper#200]
I'm getting an import error trying to upload a geojson file on the mapshaper.org site:

`internal.svg.findPropertiesBySymbolType is not a function`

Got the same error trying to upload a shapefile of counties from the U.S. Census. Any idea what's going on?

**Comment by mbloch** [comment]
Thanks for reporting this right away. It's fixed now on mapshaper.org (although my browser cache held on to the buggy version of mapshaper.js for a while).

**Comment by mtdukes** [comment]
Wow. Thanks for taking care of this so quickly!

**Comment by mbloch** [comment]
You're welcome, it was a pretty big emergency ;)
