### ISSUE TITLE
Objects may disappear when output precision is provided

### ISSUE THREAD

**Issue by Snack-X** [mbloch/mapshaper#219]
While working with some Shapefile data, I found few objects are disappearing when output precision is provided.

I used basic command:

```
mapshaper \
  -i N03-17_170101.shp encoding=shiftjis \
  -o output-no-precision.json format=topojson \
  -o output-with-precision.json format=topojson precision=0.0001
```

Then using QGIS, I compared two outputs.

![qgis-bin_2017-09-16_02-26-47](https://user-images.githubusercontent.com/1373527/30495529-48164678-9a87-11e7-8a9d-cfdac3a78098.png)

`output-no-precision.json` is placed at the bottom and colored in red. `output-with-precision.json` is placed above red layer and colored in white.
If two data are exactly same, red object should not be visible. But I can definitely see red objects, which means few objects disappeared.

By further test, I found `precision=0.00001` seems okay while `precision=0.0001` is not. I have not tested for larger precisions.

FWIW, data is made by *Ministry of Land, Infrastructure, Transport and Tourism of Japan*. You can download it from [here(English page)](http://nlftp.mlit.go.jp/ksj-e/gml/datalist/KsjTmplt-N03-v2_3.html), or [here(Japanese page)](http://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-N03-v2_3.html).
I'm using 2017's data and English page does not have 2017 data, so you might need to download it from Japanese page for better reproduction.
If you are having trouble while downloading these data, I've also uploaded the data on my Google Drive.
```
https://drive(dot)google(dot)com/file/d/0B62jB-6KncH4XzZBQlBjcGY5TDQ/view
```

**Comment by mbloch** [comment]
Thanks for the detailed report, I'll look into this later today, when I'm finished working at my day job :)

**Comment by mbloch** [comment]
I just published an update that seems to solve the problem of disappearing polygons. The fix was to stop trying to remove spikes and collapsed shapes after rounding coordinates to the desired precision. I suspect that the post-rounding cleanup pass is not useful to most users, and in any case, it evidently doesn't work well enough to keep using it.

I'll use this Shapefile as a test case as I work on improving polygon geometry repair.

Thanks for filing this issue :)

**Comment by Snack-X** [comment]
I can confirm that my issue is fixed with the commit. Thank you!

You may close this issue if you want to.

**Comment by mbloch** [comment]
Closing, thanks.
