### ISSUE TITLE
Samples for Coloring

### ISSUE THREAD

**Issue by FlashMapper** [mbloch/mapshaper#222]
I've had trouble figuring out how to color a map based on data values. For both -colorizer and -svg-style commands I think some code samples would be very helpful, similar to some of the "Example" blocks like with -join.

**Comment by mbloch** [comment]
I will add examples, thanks for the suggestion.

**Comment by mbloch** [comment]
Hey,
Sorry I haven't had a chance to document `-colorizer` beyond what's in the command reference. I added a colorizer example to issue #264 that should clarify usage. The `-colorizer` command doesn't take a field name, it defines a function that you can use in later commands to convert values to colors. You can use a colorizer function in the `-svg-style` command or the `-each` command.

**Comment by mbloch** [comment]
Hi, sorry this took a while... I added two examples to the Command Reference wiki page and one to the command line help for -colorizer.
