### ISSUE TITLE
Status of -clean command

### ISSUE THREAD

**Issue by ateucher** [mbloch/mapshaper#225]
I found the `-clean` command today in `mapshaper —help` - it seems to work well but noticed it’s not documented in the wiki. Is there a reason for that (is it still in development; would you advise against using it?).  Thanks!

**Comment by mbloch** [comment]
I'd forgotten to add `-clean` to the wiki -- thanks for the reminder! It's there now.

The current version has one problem that I've noted in the wiki: it assigns gap and overlap areas to the largest-area adjacent polygon. A better rule would be to assign gaps and overlaps to whichever polygon would create a more compact shape. I'm planning to make this and other improvements to the `-clean` command in the future. Nevertheless, I think it currently works well enough to be useful for many datasets.

**Comment by ateucher** [comment]
Fantastic, thanks very much!
