### ISSUE TITLE
Make OGC compliant polygons during clean

### ISSUE THREAD

**Issue by nvkelso** [mbloch/mapshaper#227]
When I run `ne_50m_admin_0_scale_rank.shp` thru MapShaper clean it resolves many but not all geometry errors that QGIS complains about. QGIS claims the shape still has 10 geometry errors. Some of these errors are due to null geoms or geoms that have 3 instead of 4 vertices. 

See: https://github.com/nvkelso/natural-earth-vector/issues/231

OGC and GEOS are the bane of my existence, they are extremely fussy on the geometry structure :\

**Comment by mbloch** [comment]
Thanks for the report, I'll look into this over the weekend :)

**Comment by christian-weiss** [comment]
I think your request is out of scope for mapshaper.

A valid "ring" in a "polygon" must consist out of >= 4 points. If not, then this file is not valid.

If our shapefile is broken/not valid, then you should file a ticket to the vendor of the shapefile producer (software). You should use linters and validators from the shapefile ecosystem to find problems in your shapefile. It is not the job of mapshaper to do or fix it for you. It is not a validator, not a linter or a fix-all-broken-stuff tool. It should expect to get valid GeoJSON (valid agains GeoJSON schema), shapefile (.shp; valid against specification: https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf), etc.

Mapshaper is a tool that operates on valid files. 

JustMy2Ct on it.
I request to close this ticket and focus on other issues/tickets.

**Comment by christian-weiss** [comment]
The < 4 points think should be fixed outside of mapshaper.
But apply OGC Standards on top of a valid GeoJSON / valid shapefile, could be interesting. Implementing support for OGC standards would increase the interoperability with other tools.

@mbloch what do you think about OGC? Do you want to support it? Full or community track? Which Stanard? Which quality level (Implementing Products vs Compliant Products)?

**Comment by mbloch** [comment]
@nvkelso I think that the clean command has improved somewhat since you filed this issue. The output from simplifying  `ne_50m_admin_0_scale_rank.shp` now  passes QGIS's "Check Validity" test (QGIS v3.8.3). 

I tested on the version of the file that was current when you filed this issue:
[Archive.zip](https://github.com/mbloch/mapshaper/files/3964589/Archive.zip)

I can't guarantee that `-clean` output will always pass QGIS's geometry test. But if there are future interoperability problems with ogr or QGIS, I definitely want to hear about it.

**Comment by mbloch** [comment]
@christian-weiss I'm not sure I have time to work on guaranteeing strict OGC compliance. If there are interoperability problems with other software, we can deal with them one case at a time, via GitHub issues.

**Comment by nvkelso** [comment]
Yes, works for me now. Thanks!!

**Comment by mbloch** [comment]
btw, I've gotten some more requests for OGC compliant output from -clean, so I've changed the output a bit to be more compliant. As of v0.4.149, all of the OGC polygon problems that I'm aware of should be fixed.
