### ISSUE TITLE
keep_shapes option doesn't always keep shapes

### ISSUE THREAD

**Issue by jlaamanen** [mbloch/mapshaper#228]
In some cases, all polygons to be simplified will collapse, even though `keep_shapes` is set to `true` in options (using `mapshaper` programmatically). I tried to trace the error, and figured out that if 3 vertices are added instead of 2 in function [`internal.protectIslandRing`](https://github.com/mbloch/mapshaper/blob/bbf8aba9906223f77303bff06adf735b39819e11/src/simplify/mapshaper-keep-shapes.js#L45-L55), the polygons aren't collapsed anymore.

Do you have ideas why this would happen, and would adding 3 vertices instead of 2 be a proper solution to this issue? Sorry that I can't provide data for reproducing this for now.

Thanks!

**Comment by jlaamanen** [comment]
I forked this repo trying to find out if the change would work, but the tests started to fail and I don't have enough expertise to easily find out what's wrong. However, do you think there would be side-effects for calling `internal.protectMultiRing` instead of `internal.protectIslandRing` [https://github.com/mbloch/mapshaper/blob/bbf8aba9906223f77303bff06adf735b39819e11/src/simplify/mapshaper-keep-shapes.js#L39](here)? This also seems to solve my problem.

**Comment by mbloch** [comment]
Thanks for catching this issue and reporting it. Adding two points is usually enough to convert a collapsed ring into a triangle, but I can imagine some situations where it might not work. The solution may be to switch to protectMultiRing() or something similar.

I can generate test cases if you can't provide data. I've got my hands full this week, but I'll try to have this fixed sometime next week.

**Comment by jlaamanen** [comment]
Thanks for the fast response! If using protectMultiRing() isn’t likely to have unwanted side effects, I can switch to using that in my fork until a proper solution is out.

**Comment by mbloch** [comment]
I can't be absolutely confident without doing some testing, but from looking at the code, `protectMultiRing()` should work correctly.

**Comment by mbloch** [comment]
Hi, I just released v0.4.57 to address this issue. The basic solution was to switch to protectMultiRing() for all polygons. Thanks!
