### ISSUE TITLE
process out of memory

### ISSUE THREAD

**Issue by meetirfan** [mbloch/mapshaper#230]
hi,

I am trying to simplify OS Open Roads from UK on command line.

Data is in shapefile (660 MB) and I am getting the following error message.

==================================================
<--- Last few GCs --->

   85084 ms: Scavenge 1421.8 (1479.6) -> 1421.8 (1479.6) MB, 1.3 / 0 ms (+ 172.0
 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying
 mark-sweep].
   86020 ms: Mark-sweep 1421.8 (1479.6) -> 1402.1 (1459.9) MB, 937.9 / 0 ms (+ 4
21.0 ms in 15 steps since start of marking, biggest step 172.0 ms) [last resort
gc].
   87034 ms: Mark-sweep 1402.1 (1459.9) -> 1402.1 (1459.9) MB, 1011.3 / 0 ms [la
st resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000002D5432B4639 <JS Object>
    1: addEdge [C:\Users\inlati\AppData\Roaming\npm\node_modules\mapshaper\mapsh
aper.js:~11212] [pc=000001F82D4D4096] (this=000001A90811EF41 <JS Global Object>,
start=5962694,end=5962697)
    2: convertPath [C:\Users\inlati\AppData\Roaming\npm\node_modules\mapshaper\m
apshaper.js:~11113] [pc=000001F82D4D4E20] (this=000001A90811EF41 <JS Global Obje
ct>,start=5962694,end=5962702)
    3: convertPat...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
=======================================================

I am using node arch:'X64', platform 'win32' and available RAM is 32 GB.

Any suggestions?

Irfan

**Comment by mbloch** [comment]
I have a suggestion for Mac OS and Linux, you'll have to do a bit of online research to adapt it to your Windows environment.  In the project README, i suggest allocating more memory to Node like this: 

```
$ node  --max-old-space-size=8192 `which mapshaper` <mapshaper commands>
```

This example increases the v8 heap to 8GB.

If you find an equivalent command for the Windows command shell, please post it here, I'll add it to the README.

Thanks :)
--mbloch

**Comment by meetirfan** [comment]
I will also chose Linux rather then windows for this processing. In Linux it work perfectly.

Thanks for your help.
