### ISSUE TITLE
Access feature properties with bracket notation?

### ISSUE THREAD

**Issue by bcamper** [mbloch/mapshaper#231]
When applying a filter or other JS expression, is it possible to access properties with bracket notation for those that can't use dot notation?

e.g. for [Who's on First](whosonfirst.mapzen.com) records, properties are name-spaced with `:`, such as `wof:placetype`. I tried a few syntax combinations but couldn't get them to work, so I wasn't sure if this was currently supported.

**Comment by mbloch** [comment]
Hi Brett,

Yes, there is a way, like this:  `-filter 'this.properties["wof:placetype"] == "country"'`

`this.properties` is not well documented (it's briefly mentioned in the wiki entry for `-each`) -- I'll think about how to document JS expressions better.

**Comment by bcamper** [comment]
Perfect, thank you!
