### ISSUE TITLE
Filtering shapes based on an imported csv file

### ISSUE THREAD

**Issue by JSDiamond** [mbloch/mapshaper#232]
Is it possible to filter on the values in a csv that has been imported into a script?
In this case it's a shapefile with NUTS level 2 & 3 regions, and I have an external csv that lists all the regions we want to use. Does the scope of `-filter` some how allow for this: 

```
./node_modules/.bin/mapshaper \
  ./NUTS_2013_01M_SH/data/NUTS_RG_01M_2013.shp name=nuts \
  -i ../src/data/vote-share.csv name=votes \
  -filter target=nuts \
    'votes.map(function(v){return v["NUTS CODE"]}).indexOf(NUTS_ID) > -1 ' target=nuts \
```

The error with this script is that `votes` is not defined

```
ReferenceError in expression [votes.map(function(v){return v["NUTS CODE"]}).indexOf(NUTS_ID) > -1]: votes is not defined
```

Is there some way to access data that is not the target of the filter?

**Comment by mbloch** [comment]
Currently, the only way (that I know) to access data from an external dataset is to use the `-join` command to join the records in the external dataset to the target layer.

Here is some example code. I'm using the `calc=` option to count the number of external records that join to each target record.

```
mapshaper NUTS.shp \
	-join vote-share.csv keys='NUTS_ID,NUTS CODE' calc='COUNT = count()' \
	-filter 'COUNT > 0'
```

**Comment by JSDiamond** [comment]
That should work. Thanks!
