### ISSUE TITLE
Add -remove-layers option

### ISSUE THREAD

**Issue by simonepri** [mbloch/mapshaper#234]
Allows to remove intermediate layers decreasing the memory usage of the command.

**Comment by mbloch** [comment]
I recently added the `-drop` command, which is a multi-purpose delete command that can remove layers as well as individual fields and/or geometry.

If you call `-drop` without any options, it will delete the current target layer. The target layer gets reset to an arbitrary layer.

If you use `-drop` with the `target=` option, it will delete the specified target layer(s). The target layer gets reset to an arbitrary layer, whether or not the previous default target layer is among the deleted layers.

I think I should add an explicit `layers=` option to the `-drop` command, to avoid resetting the default target layer if it is not among the layers being dropped.

**Comment by simonepri** [comment]
I've tried to search for 'delete' inside the command reference wiki but evidently I missed it.

Thank you!
