### ISSUE TITLE
Failing to export GeoJson files

### ISSUE THREAD

**Issue by tonywr71** [mbloch/mapshaper#236]
I loaded the geojson file from here: [Victoria, Australia geojson](https://data.gov.au/geoserver/vic-suburb-locality-boundaries-psma-administrative-boundaries/wfs?request=GetFeature&typeName=ckan_af33dd8c_0534_4e18_9245_fc64440f742e&outputFormat=json) and then immediately tried to export it, and it failed with "Export Failed for an Unknown Reason"

Next I clicked Simplify, selected the defaults, then dropped it to 10%, clicked Repair, then tried Export GeoJson, Export, and it also fails, as above, "Export Failed for an Unknown Reason".

**Comment by mbloch** [comment]
I see what's happening. This WFS service is serving slightly non-standard GeoJSON. The last object in the FeatureCollection is not a GeoJSON Feature, it is:
```
{
    type: 'name',
    properties: { name: 'urn:ogc:def:crs:EPSG::4283' }
}
```

I'll update mapshaper's GeoJSON importer to handle this kind of input. You can expect a fix later this evening.

**Comment by mbloch** [comment]
v0.4.58 fixes this issue.
