### ISSUE TITLE
point-symbol=square disables label-text

### ISSUE THREAD

**Issue by cedricsam** [mbloch/mapshaper#240]
In effect, when the `point-symbol=square` option is used on the `-o` command with SVG output type, the label text is ignored...

So, if I understand correctly, setting to `point-symbol=square` [converts](https://github.com/mbloch/mapshaper/blob/66a10e17b917e3caa596103650e06c6898dddb22/src/geojson/geojson-points.js#L4-L22) the GeoJSON type of the Point to Polygon, which in turn makes the feature use [`importPolygon`](https://github.com/mbloch/mapshaper/blob/53b2f5f2f4596bdb762f8e9a0e30ab6fa8fe9ea6/src/svg/geojson-to-svg.js#L198-L206) when converting to SVG? And at that point of the process, there's no way to know that this “polygon”/path is in fact a square point that could be enclosed in a `g` with a text label, which makes it a harder problem to solve...

I’ll continue to poke around and (try to) work on a solution. Any insights on previous attempts?

**Comment by mbloch** [comment]
Fixed after merging p.r. #241
