### ISSUE TITLE
null geom throws error on point-symbol=square

### ISSUE THREAD

**Issue by cedricsam** [mbloch/mapshaper#242]
When `point-symbol=square` is set, a null geometry will fail when passed to [`convertPointFeatureToSquare`](https://github.com/mbloch/mapshaper/blob/master/src/geojson/geojson-points.js#L4-L22).

One solution would be to check if the geometry is null (will provide a fix in a pull request). Otherwise, is it possible [upstream](https://github.com/mbloch/mapshaper/blob/master/src/svg/mapshaper-svg.js#L49-L53) to avoid passing all feature collections, but only the ones for label layers?

**Comment by mbloch** [comment]
PR #241 fixes this.
