### ISSUE TITLE
Output insanely slow

### ISSUE THREAD

**Issue by simonepri** [mbloch/mapshaper#245]
## Problem
The output operation is considerably slow on small file.

## How to reproduce the problem
Run this on [earth-lands.geo.json](https://file.io/uWs0Nu)
```
mapshaper -i earth-lands.geo.json
-simplify dp interval=1
-o precision=0.000001 format=geojson
```
Then wait some hours...

Same problem also if the same is done on [mapshaper's web interface](http://mapshaper.org/).

See also [this](https://github.com/mbloch/mapshaper/issues/233#issuecomment-346674300)

**EDIT**
Also doing just this led to really long waiting...
```
mapshaper -i earth-lands.geo.json -o
```
The map has a single feature with an huge number of polygons.

**Comment by simonepri** [comment]
I was able to reconduct the problem to this line:
https://github.com/mbloch/mapshaper/blob/master/src/io/mapshaper-export.js#L53

![image](https://user-images.githubusercontent.com/3505087/33397312-96654b54-d54b-11e7-8caf-62e0299b042e.png)

**Comment by simonepri** [comment]
I was able to reconduct the problem to this line:
https://github.com/mbloch/mapshaper/blob/master/src/io/mapshaper-export.js#L55

![image](https://user-images.githubusercontent.com/3505087/33397665-a3ce1c16-d54c-11e7-8313-67d14e504970.png)

**Comment by simonepri** [comment]
Then to this one:
https://github.com/mbloch/mapshaper/blob/master/src/io/mapshaper-export.js#L107

![image](https://user-images.githubusercontent.com/3505087/33397857-47c6741c-d54d-11e7-93de-8a047f2a1cd8.png)

**Comment by simonepri** [comment]
Then this:
https://github.com/mbloch/mapshaper/blob/master/src/geojson/geojson-export.js#L42

![image](https://user-images.githubusercontent.com/3505087/33398182-632f5042-d54e-11e7-8775-04ccad9ebd44.png)

**Comment by mbloch** [comment]
There are better ways to track down performance bottlenecks. Recent versions of node have a built-in profiler, see this introduction:  https://nodejs.org/en/docs/guides/simple-profiling/

Example (on Mac or Linux):
```
$ node --prof `which mapshaper` earth-lands.geo.json
$ node --prof-process *log | less
```

**Comment by simonepri** [comment]
Thank you to point me out the profile.
By the way, I enjoyed doing it manually 😂

I isolated the problem to these nested cycles:
https://github.com/mbloch/mapshaper/blob/master/src/utils/mapshaper-path-utils.js#L280

![image](https://user-images.githubusercontent.com/3505087/33400307-ef6ff834-d555-11e7-9122-9318bc201789.png)

**Comment by simonepri** [comment]
I'm working on an improvement, I'm getting good results.
I will open a PR soon.

**Comment by mbloch** [comment]
Thanks for the pull request. It's not ready to merge as-is, but I'm grateful for your work and I will incorporate it after a few adjustments have been made (which I'm happy to do when I get the time). I have a couple of comments:

[1]
Your method is a big performance win if you're generating a MultiPolygon containing a very large number of both holes and space-filling rings. In my experience that's a very unusual case. The function that you rewrote runs once for each polygon feature. For more typical datasets containing many relatively simple polygons, it may impact performance to create an R-tree for each polygon. If that's the case, I'd prefer switching to your function when `N * P` (from your analysis) becomes large.

[2]
You included a bunch of changes to dependency versioning and a mapshaper version bump in your pull request. I'd rather handle that stuff on my end.

**Comment by simonepri** [comment]
> It may impact performance to create an R-tree for each polygon

What do you mean by "for each polygon" ?
The R-tree is created once using the [bulk insertion algorithm](https://github.com/mourner/rbush#bulk-inserting-data).

Anyway your idea to combine the two solutions is not bad. But you have to find (benchmarking) for which values is suitable your solution.

The `O(N * P)` solution performs better only in some edge cases that you can see [here on wolfram](https://www.wolframalpha.com/input/?i=Plot%5BN*P+%3C+N*Log%5B2,+N%5D+%2B+P*Log%5B2,+P%5D+%2B+P*Log%5B2,+N%5D,+%7BN,+0,+100%7D,+%7BP,+0,+100%7D%5D). Practically when one of N or P are particularly small. (Please note the absence of the O notation in this _simple_ analysis).

## Complexity analysis of the actual solution:
### Precomputation:
`O(N + P)` while creating **neg** and **pos** arrays
### Algorithm:
`O(N * P)` we always have to iterate all elements of **pos** times for each element of **neg**
### Additional Space:
`O(N + P)` for **neg** and **pos**

## Complexity analysis of the new solution:
### Precomputation:
`O(N + P)` while creating **neg** and **pos** arrays
`O(N * log2(N))` while creating the R-Tree of **neg** polygons
`O(P * log2(P))` while sorting the **pos** array
### Algorithm:
`O(P * log2(N))` for each element of **pos** we search all **neg** contained in it using the R-Tree
### Additional Space:
`O(N + P)` for **neg** and **pos**
`O(N)` for the R-Tree

**Comment by mbloch** [comment]
Your complexity analysis is interesting. Big O notation can be so useful for comparing performance for large N. (When N is relatively small, a higher-complexity solution may be preferable for one or another reason, e.g. good enough, simpler implementation, lower cost per operation).

You're working with a dataset that has more rings and holes in a single polygon feature than I've every seen before. I agree that it's worth optimizing for this case, and your proposed solution is effective.

There are two ways to apply the R-tree optimization -- indexing the holes or indexing the containing rings.

In your PR, you indexed the holes, which works as long as you sort the containers from small to large and make sure you don't add the same hole to multiple containers (e.g. by deleting holes from the tree after they are used).

Indexing container rings is closer to my original implementation and is a bit simpler than the alternative. You don't have to sort and you don't have to delete from the tree. (I doubt pruning the tree is a performance win).

I rewrote my original function to use container ring indexing and pushed to the `issue245` branch. I tested with a few challenging datasets, including the 150MB `earth-lands.geo.json` file, and it performed well.

I appreciate your work on this, and I hope you don't mind if I ultimately decide to go with the container-indexing implementation.

See: https://github.com/mbloch/mapshaper/blob/issue245/src/utils/mapshaper-path-utils.js#L261

**Comment by simonepri** [comment]
Hello @mbloch Thank You for your work!!
I'm glad you liked the analysis.

The original implementation I wrote was the "container indexed" then i switch to the "hole indexed" version since i saw it was performing better on my specific data set.

The complexity with the "hole based" approach should be
`O(N + P + P * log2(P) + N * log2(P) * K) `
with K that goes up to P in the worst case (All the holes are contained in all the rings).
I think that in general should be better than the "container based" approach, but the worst case is more likely to happen with this approach.

The prune of the tree in "container based" can be avoided using some additional space to keep the holes already fitted cutting down the complexity to
`O(N + P + P * log2(P) + N * log2(N) + P * log2(N) * K))`
But without pruning this time K has the same problem of the "hole based" approach.
The pruning of the tree was only implemented to avoid this sad worst case.

<hr/>
Anyway talking about your solution I think you can avoid this:

https://github.com/mbloch/mapshaper/blob/issue245/src/utils/mapshaper-path-utils.js#L287

by simply doing it directly here:
https://github.com/mbloch/mapshaper/blob/issue245/src/utils/mapshaper-path-utils.js#L270

```js
if (path.area * sign > 0) {
  ringIndex.push({
    minX: path.bounds.xmin,
    minY: path.bounds.ymin,
    maxX: path.bounds.xmax,
    maxY: path.bounds.ymax,
    ring: path,
    idx:  output.length
  });
  output.push([path]);
}
```

Then here:
https://github.com/mbloch/mapshaper/blob/issue245/src/utils/mapshaper-path-utils.js#L315
Just do this:
```js
ring = candidates[i].ring;
```

**Comment by mbloch** [comment]
One version of the optimization that we discussed was added in v0.4.59, so I'm closing this issue. Thanks for your help @simonepri
