### ISSUE TITLE
`dissolve` refuses to accept `name` as a name of the field to merge on

### ISSUE THREAD

**Issue by kapooostin** [mbloch/mapshaper#251]
I'm trying to use it in web-console. It always returns this error: **Missing value for name option**.

**Comment by mbloch** [comment]
When the field you want to dissolve has the same as a command line option, you have to use an alternate way to specify the dissolve field: `-dissolve field=name`.

This is not well documented... sorry about that.

**Comment by kapooostin** [comment]
Thank you, it works now!

Maybe it would be better to put in command help the full syntax for this option.  And use a shortcut one as an alternative.

**Comment by mbloch** [comment]
There are quite a few commands that have both a long form and a short form (or shortcut) for the main option (e.g. -simplify, -filter, -split, -i, -o, -proj).  I put the shortcuts in the inline help, but I agree, it would be good to be explicit about the long form.

I also want each help line to fit in 80 characters if possible (a few lines go over).

I could wrap the line, like this:

```
  <percentage>,
  percentage=    percentage of removable points to retain, e.g. 10%
```

Do you have some thoughts on how to reformat these options?

**Comment by kapooostin** [comment]
It looks fine, now that I know what exactly `<some_option>` means.

I'm not very experienced command line user. Is it common way to designate a shortcut that omits a name of an option? If it is, than that formatting is self-explanatory enough.

**Comment by mbloch** [comment]
I think its pretty common to use angle brackets as a placeholder for a value in command line usage docs. The `percentage=` notation is less standard, but seems fairly clear to me. Ideally there would be at least one example for each command -- that should help users understand the docs better.

**Comment by mbloch** [comment]
I updated the command line help a bit for the next release... the new format shows all forms of an argument, like this:

```
Command
  -dissolve     merge features within a layer

Options
  <field>       (optional) name of a data field to dissolve on
  field=        equivalent to <field>
  calc=         use a JS expression to aggregate data values
  ...
```

Does this seem like an improvement?

**Comment by kapooostin** [comment]
Yes, it definitely does. Thank you!

**Comment by mbloch** [comment]
The wiki and command line help are now both updated with both versions of these options, so closing...
