### ISSUE TITLE
Embedding mapshaper in another site

### ISSUE THREAD

**Issue by nyurik** [mbloch/mapshaper#252]
Hi, I would like to add Mapshaper's capabilities to my site.  I could either fully host it (I'm still unclear if I need to run node for that), or I could use an iframe.  My site generates a URL for a large map dataset. Is there an easy way to tell mapshaper to load a URL via an API? Or if I have to host all of the mapshaper files, any embedding and integration strategy tips?  Thanks!

**Comment by mbloch** [comment]
Yes, you can host mapshaper on your own site. It is not necessary to run Node. First, clone or download the mapshaper source code files from GitHub, then copy the contents of the `www` subfolder to your website's root directory or a subfolder of the document root.

You will be missing one file, `mapshaper.js`. This can be copied from `http://mapshaper.org/mapshaper.js`. Or you can generate it by cloning mapshaper from GitHub, installing with `npm install` and then running the `build` script.

One way to load datasets from a url is documented here, under "loading files via query string": https://github.com/mbloch/mapshaper/wiki/Web-Interface

If this doesn't meet your needs, please tell me a bit more about how you want to use mapshaper.

**Comment by nyurik** [comment]
@mbloch thanks, it worked like a charm.  [This query](https://sophox.org/sophox/embed.html#%23defaultView%3AMapRegions%0ASELECT%20%0A%20%20%3Fid%0A%20%20%28SAMPLE%28%3Flabel_en%29%20as%20%3Flabel_en%29%0A%20%20%28SAMPLE%28%3Flabel_fr%29%20as%20%3Flabel_fr%29%0A%20%20%28SAMPLE%28%3Fiso_3166_2%29%20as%20%3Fiso_3166_2%29%0A%20%20%28SAMPLE%28%3Fflag%29%20as%20%3Fflag%29%0AWHERE%20%7B%0A%20%20%23%20List%20of%20regions%2C%20whose%20sub-regions%20we%20want%0A%20%20VALUES%20%3Fentity%20%7B%20wd%3AQ16%20%7D%20%0A%0A%20%20%23%20P150%20%3D%20%22contains%20administrative%20territorial%20entity%22%0A%20%20%23%20but%20must%20not%20have%20a%20P582%20%28end%20date%29%20qualifier%0A%20%20%3Fentity%20p%3AP150%20%3Fstatement%20.%0A%20%20%3Fstatement%20ps%3AP150%20%3Fid%20.%0A%20%20FILTER%20NOT%20EXISTS%20%7B%20%3Fstatement%20pq%3AP582%20%3Fx%20%7D%0A%0A%20%20%23%20Get%20labels%2C%20ISO%20code%2C%20and%20flag%20image%0A%20%20%23%20for%20each%20sub-region%2C%20if%20available%0A%20%20OPTIONAL%20%7B%20%3Fid%20rdfs%3Alabel%20%3Flabel_en%20.%20FILTER%28LANG%28%3Flabel_en%29%20%3D%20%22en%22%29%20%7D%0A%20%20OPTIONAL%20%7B%20%3Fid%20rdfs%3Alabel%20%3Flabel_fr%20.%20FILTER%28LANG%28%3Flabel_fr%29%20%3D%20%22fr%22%29%20%7D%0A%20%20OPTIONAL%20%7B%20%3Fid%20wdt%3AP300%20%3Fiso_3166_2%20%7D%0A%20%20OPTIONAL%20%7B%20%3Fid%20wdt%3AP41%20%3Fflag%20%7D%0A%7D%0A%23%20remove%20possible%20ID%20duplicates%0AGROUP%20BY%20%3Fid) gets you all Canadian regions into Mpashaper.  For docs, see [here](https://wiki.openstreetmap.org/wiki/Sophox_query_service#Generating_Polygon_Files).
