### ISSUE TITLE
split to topojson output writes only one layer to original file

### ISSUE THREAD

**Issue by jheeffer** [mbloch/mapshaper#255]
I have a topojson file with multiple features in one layer.

I use split to create separate layers and want to output those to separate files.

**Actual behaviour**

`mapshaper .\mycountrymap.json -split province -o format=topojson`

results in

```
[o] Wrote mycountrymap.json
```

While 

`mapshaper .\mycountrymap.json -split province -o format=geojson`

results in

```
[o] Wrote mycountrymap-1235.json
[o] Wrote mycountrymap-2475.json
[o] Wrote mycountrymap-2455.json
[o] Wrote mycountrymap-1110.json
[o] Wrote mycountrymap-1240.json
[o] Wrote mycountrymap-2413.json
[o] Wrote mycountrymap-2470.json
[o] Wrote mycountrymap-1120.json
[o] Wrote mycountrymap-1101.json
[o] Wrote mycountrymap-2465.json
[o] Wrote mycountrymap-1125.json
[o] Wrote mycountrymap-1350.json
[o] Wrote mycountrymap-1230.json
[o] Wrote mycountrymap-1105.json
[o] Wrote mycountrymap-1115.json
[o] Wrote mycountrymap-1345.json
```

**Expected behaviour**
I'd expect the topojson format to work the same as the geojson output format

**Comment by mbloch** [comment]
There is an undocumented option that does what you want: `-o singles`. Example:

```
mapshaper .\mycountrymap.json -split province -o format=topojson singles
```

I'd appreciate it if you left gave some feedback on `singles`, before I add it as a documented option. Does it work the way you would expect?

Thanks,
--mbloch

**Comment by mbloch** [comment]
Commit 2fbb9c3bf36a1e1fef1701133  adds documentation and a test for the `-o singles` option. It will be included in the next release.

**Comment by jheeffer** [comment]
@mbloch I tested it and it indeed does exactly what I wanted : ).

Thanks!
