### ISSUE TITLE
Improve display of multiple layers (currently limited to two)

### ISSUE THREAD

**Issue by mbloch** [mbloch/mapshaper#259]
It should be possible to display more than two layers at once (currently the selected layer is black and the reference layer is green).

**Comment by Mystiry** [comment]
How can I show both reference layers(My version is to show the other one and the last one will cancel the show)?Which file is the js code that triggers the reference layer?
thank you .

**Comment by Mystiry** [comment]
> It should be possible to display more than two layers at once (currently the selected layer is black and the reference layer is green).

How can I show both reference layers(My version is to show the other one and the last one will cancel the show)?Which file is the js code that triggers the reference layer?
thank you .

> It should be possible to display more than two layers at once (currently the selected layer is black and the reference layer is green).

How can I show both reference layers(My version is to show the other one and the last one will cancel the show)?Which file is the js code that triggers the reference layer?
thank you .

**Comment by Mystiry** [comment]
> It should be possible to display more than two layers at once (currently the selected layer is black and the reference layer is green).

How can I show both reference layers(My version is to show the other one and the last one will cancel the show)?Which file is the js code that triggers the reference layer?
thank you .

**Comment by mbloch** [comment]
Hi, are you using the current version of the mapshaper gui (online at mapshaper.org)? You should be able to display multiple reference layers by clicking on the "eye" icons next to each layer in the layers menu. Here's a screenshot:

![image](https://user-images.githubusercontent.com/1232222/46873833-9ed94e80-ce05-11e8-81ca-4932cabdb66c.png)
