### ISSUE TITLE
dissolve2 still incorrect

### ISSUE THREAD

**Issue by fran2a** [mbloch/mapshaper#261]
Hi,
I try to dissolve polygons with dissolve2 but get some unwanted holes...
Here the file I try to dissolve with the command line : mapshaper  -i 3G.shp -dissolve2 -o 3Gd.shp
[3G.zip](https://github.com/mbloch/mapshaper/files/1807106/3G.zip)

What am I doing wrong?
Thanks.

**Comment by mbloch** [comment]
Mapshaper is unable to generate correct output for this dataset. `-dissolve2` generally works well for polygons that have small overlaps around the edges. It doesn't correctly dissolve polygons that have large overlapping areas and holes inside the overlaps, like in your dataset.

I'd like to improve the dissolve algorithm to handle this kind of input. I'll use your Shapefile as test data... thanks!

**Comment by yfjd01** [comment]
Hi,

I've basically ran into the exact same problem, while -dissolve2 works really well with polygon with small overlap around the edges. 

But generating a polygon that encompasses all polygons with primarily overlapping areas results in very very small under-coverage (area that is covered by the -i but not completely covered in the -o) in the generated polygon.

**Comment by mbloch** [comment]
I just published an update that improves `-dissolve2`. Now it can handle polygons that overlap each other in complex ways. The new version appears to work correctly on the test file attached above ("3G.zip"). I'm closing this issue, but feel free to reopen if there are further problems.
