### ISSUE TITLE
Why not use regular modules?

### ISSUE THREAD

**Issue by jdesboeufs** [mbloch/mapshaper#263]
Hi @mbloch 

I really love your work and I use mapshaper nearly every day.

But why don't you use regular modules in your codebase?
The benefit would be huge: more contributors, more reuses…

Would you accept a massive PR in this direction?

**Comment by mbloch** [comment]
Are you proposing converting all of mapshaper's source code files to be ES6 modules, or maybe Node-style modules?

My feeling is that to be more developer-friendly, mapshaper should have a more thorough working-over than just switching to JS modules.

One challenge is that mapshaper stores data in a custom format, similar to the TopoJSON format, but with path coordinates packed into ArrayBuffers. Working with the data is a bit awkward and error-prone.

Also, there's no API for adding new commands.

I wonder if there should be an API aimed at developers, with functions for adding new commands and for accessing data in an easier-to-use format.

**Comment by jdesboeufs** [comment]
I'm proposing a step-by-step migration.
Converting to Node-style modules won't break anything since you are already using `browserify`.
It's a good starting point since it brings some usual conventions. It is easier to contribute to a bunch of Node-style modules requiring themself than to understand a homemade dependency tree.

I'm OK to do this adaptation in a PR if you are interested in :)

**Comment by mbloch** [comment]
Thank you for offering to convert mapshaper to use Node modules :)

I'm not convinced about the benefits. I don't have much time to work on mapshaper. More developers means more pull requests to review and comment on. I'd rather spend the time writing my own code.

If there were a few other maintainers working with me, who understood the codebase well and wanted to share the burden of maintaining the project, I would have a different attitude. If you have that kind of time and interest, perhaps you could first do a more thorough code review and talk with me some more before diving into refactoring.

Also please feel free to fork the project or pull out bits that you think would be useful to other developers as individual modules, if you're interested in that.

**Comment by jdesboeufs** [comment]
OK no problem! 👍
