### ISSUE TITLE
use mapshaper-xl with mapshaper.applyCommands?

### ISSUE THREAD

**Issue by ateucher** [mbloch/mapshaper#265]
Is it currently possible to use `mapshaper-xl` with `mapshaper.applyCommands`? Or is there another way to set `--max-old-space-size` when using `mapshaper.applyCommands`?

Thanks very much!

**Comment by mbloch** [comment]
If you're using `mapshaper.applyCommands()`, then you're requiring the mapshaper module in a Node script, right? One way to set the `max-old-space-size` parameter is by adding it to the command line, like this:
```
node ----max-old-space-size=4000 script.js
```

**Comment by ateucher** [comment]
Thanks @mbloch! It's a bit more complicated than that... I'm using it in my [rmapshaper](https://github.com/ateucher/rmapshaper) R package.  It uses the [v8](https://github.com/jeroen/v8) R package which provides an interface to `v8` in R. I have a feeling that that's actually where I need to tackle the setting of `--max-old-space-size` (issue [here](https://github.com/jeroen/V8/issues/33))... just thought I would try to see if there was an out-of-the-box solution ;)

**Comment by mbloch** [comment]
No out-of-the-box solution, but you may be able to adapt the code in the `mapshaper-xl` script, which  runs mapshaper in a sub-process using Node's built-in "child_process" module.

**Comment by ateucher** [comment]
I believe `v8` is a subset of Node, and it doesn't look like it has the "child_process" module. I'll keep digging, but thanks for your help, and thanks again for mapshaper!
