### ISSUE TITLE
Use mapshaper to convert shapefile to geojson in browser

### ISSUE THREAD

**Issue by jaltin** [mbloch/mapshaper#267]
Hi,

I would like to build a page with the following functionality:

1) User selects a shapefile from their computer (either as .zip or the individual shapefiles)
2) The shapefile is converted to geojson on the client
3) The user sees a preview of the converted geojson on a custom background map (in my case mapbox)
4) The user presses "Upload" and this sends the geojson file to my api

Would it be possible to use mapshaper for step 2 above, or can this only be done on server via node?

**Comment by mbloch** [comment]
You can use mapshaper in a browser, but it wasn't designed to be modular, so you're loading a bunch of code that you don't need for converting from Shapefile to GeoJSON.

To use mapshaper, you need two JS files:
```
<script src="modules.js" type="text/javascript"></script>
<script src="mapshaper.js" type="text/javascript"></script>
```

You can get them from the mapshaper.org website. "mapshaper.js" adds mapshaper to the page as a global variable.

Then you can use the `applyCommands()` function to do your conversion. There's some documentation on the wiki: https://github.com/mbloch/mapshaper/wiki/Using-mapshaper-programmatically#option-three-applycommands
