### ISSUE TITLE
-join results in alphabetically sorted field output

### ISSUE THREAD

**Issue by nvkelso** [mbloch/mapshaper#269]
I'm using `-join` to rebuild Natural Earth topology ( 🎉❗️) but the end result is alphabetically sorted field output.  Instead I expected the resulting joined output file to respect the original field order in the joined attribute table when appending it to the original table (and **after** the original table columns, not before like is currently performed).

If I have:

- source geography **file 1** with columns `Z`, `D`, `Q`, and 
- join **table 2** with columns `C`, `B`, `A`, then I expect 
- output of **file 3** with have columns `Z`, `D`, `Q`, `C`, `B`, `A` in that order. 
  - Instead I see `A`, `B`, `C`, `Z`, `D`, `Q` (note initial `A`, `B`, `C` order).

And a nitpick: DBF files generally preserve the casing of the column names but tooling (as in QGIS and ArcGIS) are casing insensitive on joins. MapShaper is currently case sensitive on joins.

**Comment by nvkelso** [comment]
For example:

- https://github.com/nvkelso/natural-earth-vector/blob/191d2735e51649c7954df362966cbe49423efe49/Makefile#L546-L554

```
build_c3_ne_110m_admin_0_sov: 110m_cultural/ne_110m_admin_0_scale_rank.shp \
	housekeeping/ne_admin_0_details_level_1_sov.dbf
	mkdir -p intermediate
	mapshaper -i 110m_cultural/ne_110m_admin_0_scale_rank.shp \
		-dissolve 'sr_sov_a3' copy-fields=featurecla,scalerank,min_zoom \
		-filter 'scalerank !== null' + \
		-join housekeeping/ne_admin_0_details_level_1_sov.dbf encoding=utf8 keys=sr_sov_a3,SOV_A3 \
		-each 'featurecla="Admin-0 sovereignty", delete sr_sov_a3' \
		-o intermediate/ne_110m_admin_0_sovereignty.shp \
```

Add fields are at the beginning in A-Z sort order (should be at end in original sort order):

<img width="930" alt="screen shot 2018-05-04 at 23 40 39" src="https://user-images.githubusercontent.com/853051/39660470-95f1f0e0-4ff4-11e8-8f8e-f16aaa82f22a.png">

And the original fields are at the end in original sort order (should be at beginning in original sort order):

<img width="431" alt="screen shot 2018-05-04 at 23 42 07" src="https://user-images.githubusercontent.com/853051/39660481-cd7a9e18-4ff4-11e8-8e05-30bbbdb06015.png">

**Comment by nvkelso** [comment]
I'd be fine with an option to either preserve original field sort order, or changing the default behaviour and then adding option to A-Z sort resulting fields. But current sorting is just weird o_O.

**Comment by mbloch** [comment]
It looks to me as though mapshaper is using case-sensitive sort order(uppercase before lowercase) in the DBF output. That explains why in your example, the original fields (l.c.) are getting sorted after the joined fields (all u.c.).

Some options are:

1. preserve original field order
2. switch to case-insensitive sorting
3. keep using case-sensitive sorting

I'd be ok with switching to option 1, if that's what you prefer.

**Comment by nvkelso** [comment]
Yes, I prefer original field sort order, please. That way I can curate important fields to the left where they are easier to find in default attribute table views in GIS apps like QGIS. Thank you!

(Like gdal users could specify which fields to keep in what order if a new order is desired, or add new option to a-z sort them.)

**Comment by nvkelso** [comment]
This is working for me, thank you so much!

Two followup issues filed for completeness so their discussion doesn't hold up closing this issue:

- https://github.com/mbloch/mapshaper/issues/270 - reorder fields on export
- https://github.com/mbloch/mapshaper/issues/271 - join with case insensitive field names
