### ISSUE TITLE
Add -o option to order fields

### ISSUE THREAD

**Issue by nvkelso** [mbloch/mapshaper#270]
This is a followup to https://github.com/mbloch/mapshaper/issues/269 which changed the output field order behavior in v0.4.70 to respect the input field order.

In some cases it's useful to re-order the fields in the output. @mbloch proposed a few options in https://github.com/mbloch/mapshaper/issues/269#issuecomment-386838960.

> I'll think about adding an option for sorting field names (maybe `-o sorted-fields`? `-o field-order=ascending`? `-sort field-names`?).

I personally prefer `-o field-order=ascending` so it's flexible for other sort orders in the future (like `descending`).

**Comment by nvkelso** [comment]
Verified this locally, closing. Thanks!

**Comment by mbloch** [comment]
I see that you filed mapshaper's very first GitHub issue on Feb 25, 2013...  glad that you're still using the program ;)

**Comment by nvkelso** [comment]
The pleasure is mine :)
