### ISSUE TITLE
Joins are field name case sensitive

### ISSUE THREAD

**Issue by nvkelso** [mbloch/mapshaper#271]
A minor nitpick: DBF files generally preserve the casing of the column names but tooling (as in QGIS and ArcGIS) are casing insensitive on joins. MapShaper is currently case sensitive on joins.

Suggest adding a -join option to be case insensitive on field names.

See https://github.com/mbloch/mapshaper/issues/269 for an example.

**Comment by mbloch** [comment]
Hey, could you be a bit more specific about what you mean by "casing insensitive on joins"? I'm not getting enough guidance from #269.

**Comment by nvkelso** [comment]
> -join housekeeping/ne_admin_0_details_level_1_sov.dbf encoding=utf8 keys=sr_sov_a3,SOV_A3 \

In ArcGIS (and I think in QGIS) from where I ported the ArcPy script it was

>  sr_sov_a3,sov_a3 and worked just fine.

**Comment by mbloch** [comment]
I'd prefer to stick with case-sensitive field names. Trying to match QGIS and Arc's behavior with respect to field naming would be a pain in the neck.
