### ISSUE TITLE
Add option to include join field in property export

### ISSUE THREAD

**Issue by nvkelso** [mbloch/mapshaper#275]
In the `-join` documentation it states:

`fields= A comma-separated list of fields to copy from the external table. If fields= option is absent, all fields except the key field are copied.`

In the Natural Earth build process I build polygons out of lines, then use a spatial join to add a temporary attribute to the resulting polygons, and then do a data property join (`left_prop`) on the tmp result to the final set of properties that are maintained in table form (`right_prop`). 

Currently MapShaper drops the `right_prop` preferring the `left_prop`... but the problem is the property on the right is named something important, and in a deliberate order in the right table. 

Perhaps add a `fields=*` option to include all fields that different than the default of all but the join field? Or is there a better workflow for me to use?

(I drop the left join property and a few others after the join, there are just a handful of those but dozens on the right.)

**Comment by mbloch** [comment]
I think `fields=*` is good, it's consistent with the syntax of other commands.  v0.4.74 changes the behavior `fields=*` to include the key field in the source table. I also updated the wiki.

**Comment by nvkelso** [comment]
Verified this is working, thank you!
