### ISSUE TITLE
mapshaper.org: export fails

### ISSUE THREAD

**Issue by lordfuoco** [mbloch/mapshaper#281]
Hello,
As of this morning the export functionality is broken after clicking export and selecting geoJSON this is the message in the chrome console:

Os: macOS High Sierra 10.13.4 (17E199)
Browser: Version 66.0.3359.181 (Official Build) (64-bit)

```
mapshaper-gui.js:2406 Uncaught TypeError: Cannot read property 'allow_saving' of undefined
    at canSaveToServer (mapshaper-gui.js:2406)
    at Object.internal.writeFiles (mapshaper-gui.js:2415)
    at exportMenuSelection (mapshaper-gui.js:2584)
    at mapshaper-gui.js:2558
canSaveToServer @ mapshaper-gui.js:2406
internal.writeFiles @ mapshaper-gui.js:2415
exportMenuSelection @ mapshaper-gui.js:2584
(anonymous) @ mapshaper-gui.js:2558
setTimeout (async)
onExportClick @ mapshaper-gui.js:2557
Handler.trigger @ mapshaper-gui.js:28
EventDispatcher.dispatchEvent @ mapshaper-gui.js:64
(anonymous) @ mapshaper-gui.js:1367
```

Same otuput in the console:
```
$ mapshaper -o
Cannot read property 'allow_saving' of undefined
```

Attached the imported geojson (in zip format)

[exportBoundaries (1).zip](https://github.com/mbloch/mapshaper/files/2038547/exportBoundaries.1.zip)

**Comment by mbloch** [comment]
Thanks for reporting this! fixed now.

**Comment by lordfuoco** [comment]
@mbloch Than you for the quick fix!
