### ISSUE TITLE
Ability to import dxf files?

### ISSUE THREAD

**Issue by donnyv** [mbloch/mapshaper#284]
This library is amazing. A lot of times people have to create parcels from CAD files. So being able to import from a dxf file would be a great addition. Have you given any thought to maybe adding that?

You may be able to use [Dxf-Parser](https://github.com/gdsestimating/dxf-parser) to get the data into a more manageable state.

**Comment by mbloch** [comment]
Thanks for getting in touch :)   dxf import isn't something that I or my colleagues would use, so i'll have to say "no" to this request. It looks like you can use `ogr2ogr` to convert dxf to GeoJSON or Shapefile as an intermediate step (see https://stackoverflow.com/questions/39214367/how-can-i-convert-my-caddwg-file-to-geojson/39262958)
