### ISSUE TITLE
Handling multiple feature types in a single GeoJSON

### ISSUE THREAD

**Issue by paulana** [mbloch/mapshaper#291]
Hello!

I was wondering if there had been progress made to handle multiple feature types in a single GeoJSON like lines, points, and polygons.  This is still a great feature that I'd love to see!  Let me know if I can help contribute to getting it done, I've actually extended your library pretty extensively to handle a custom project and would love to help however I can.

Thanks for the awesome library!

Paulana

**Comment by mbloch** [comment]
Mapshaper already has limited support for mixed GeoJSON feature types.

If a GeoJSON file contains mixed geometry types, the file gets converted to several mapshaper layers  on import. To export multiple layers as a single GeoJSON file, add the `combine-layers` flag to the `-o` command.

Many of mapshaper's commands assume a single geometry type as input. Allowing different geometry types in a single layer seems complicated to me... can you give a bit more detail about how you would handle this?

**Comment by paulana** [comment]
Sure,

After combing through the API, I can understand why it seems difficult.  Most of it would likely be accomplished with type loops and perhaps an initial scan of the file to detect all of the geometry types and to store them in the info about the dataset. 

 The most important feature to result from this would be to be able to draw both feature types on the same canvas layer.  For example identifying points of interest within a building geometry has come up routinely in projects that I've worked on.  While I'm definitely not an expert on your API yet, I would like to try to combine the ability to draw both geometries on a single layer and send that to you for you to review.  May be a few days, but I'll let you know.

Thanks again,

Paulana

**Comment by mbloch** [comment]
Hi,

You mentioned wanting to draw different feature types on the same canvas layer....  I recently added the ability to display multiple layers at the same time (using the eye icons on the layers menu).

Using the `-style` command, you can style the objects on each layer the way you want.

So you might consider whether you can accomplish what you want to do without putting points of interest and building outlines on the same layer.

**Comment by paulana** [comment]
Hi,

So I tried it out, sorry for the latent response.  I had to upgrade my version of the library.  While I get the separate layers, when I try to display them together programmatically or using the UI, it still defaults to one layer or the other (whichever was the initially selected layer), which I would assume is the results of the multiple geometry types.  Attached is a sample json for you to see what I mean and this short snippet that I use in my code:

```
model.forEachLayer(function(layer, dataset) {
          if(layer.name.indexOf("samples") > -1) {
            var cb = map.addReferenceLayer.bind(map);
            cb(layer, dataset);
            building.samples.layers.push({layer, dataset});
          }
        });
```

sample json: https://gist.github.com/paulana/1cf2a47b22302d8e0427cfc027f9cfc9

**Comment by paulana** [comment]
Sorry about the unnecessary notifications.

I think I've nearly gotten the layers to draw, but what I've concluded is that when I combine the geojson files, the style of the points is lost because the building is styled.  When I separate the json files and import them separately, the point geojson draws fine, but the polygon json then doesn't add as a reference layer properly.  The point layer, when the files are combined, returns a drawable layer (getDrawableLayers) without a style (null) and causes the js to fail before drawing.  When the files are not combined, the point layer has its proper style.

Still scratching my head, but getting closer to a reasonable cause, I hope.

**Comment by paulana** [comment]
Hi, thanks for the update!

That's definitely something I can fix, but I've been pulled into another project in the short term and don't have this code available right now.  Such is life.  Thank you for the feedback and I'll let you know if it works!

**Comment by mbloch** [comment]
Feel free to re-open this issue if you want to continue our discussion later :)
