### ISSUE TITLE
Centriods (innerX, innerY) as point file.

### ISSUE THREAD

**Issue by meetirfan** [mbloch/mapshaper#295]
I am now using mapshaper to get the inner X and inner Y for the polygon. Here is my workflow.
1. Convert polygon inner X/Y to csv 
(mapshaper-xl ca_blcks.shp -each "x=this.innerX,y=this.innerY"  -o ca_blcks_pnt.csv)
2. Then convert this csv to point
(mapshaper-xl ca_lbs.csv -points x=x y=y -o ca_blcks_pnt.shp)

It will be very nice if there is option available to export directly from the polygon like we have --rectangle for bounding box extraction.

**Comment by mbloch** [comment]
Can you just use `-points inner`?

**Comment by meetirfan** [comment]
Thanks for pointing it out, it works perfectly.
