### ISSUE TITLE
Polygon spikes as point.

### ISSUE THREAD

**Issue by meetirfan** [mbloch/mapshaper#296]
There are few cases where after simplification, I would to see the spikes in polygons. It will be very nice if we can some how extract the spikes from the polygon as point with angle value.

**Comment by mbloch** [comment]
If you send me an example dataset and instructions for how to reproduce, I'll be happy to investigate this. Also, what do you mean by "point with angle value," and how would you use that information?

**Comment by meetirfan** [comment]
Here you will find the sample data of Canada blocks and required out put point file of spikes.
I have extracted the spikes point file from the blocks where angle of spikes is less 5 degree.
I hope this will help you to understand the problem.
[CA_blocks.zip](https://github.com/mbloch/mapshaper/files/2301418/CA_blocks.zip)

**Comment by mbloch** [comment]
I understand what you're asking for, but I don't see how this will help typical users with their map making projects, so I'm going to close the issue. Thanks for the suggestion!
