### ISSUE TITLE
-points inner or centroid 

### ISSUE THREAD

**Issue by meetirfan** [mbloch/mapshaper#304]
hi, 

I am calculating centroid of polygon with -points command: 
mapshaper -i test.shp -points inner  -o test_pnt.shp 
I have found in few polygons points are way outside the polygons. These are really small polygons representing islands.

Attached you will find the test polygons with output points.

[test_data.zip](https://github.com/mbloch/mapshaper/files/2378538/test_data.zip)

**Comment by mbloch** [comment]
Thanks for reporting this...  this looks to be caused by floating-point rounding errors, I'm looking into how to fix...

**Comment by mbloch** [comment]
I just published v0.4.96, which fixes this issue.
