### ISSUE TITLE
Partially OT: remove duplicate geometries

### ISSUE THREAD

**Issue by aborruso** [mbloch/mapshaper#305]
Hi,
is there a way to remove duplicate geometries in mapshaper?

I think no, it's not its job, but probably there is some magic tip :)

Thank you

**Comment by aborruso** [comment]
> If there's no id field, you'll have to look at geometry to find the dupes... if this is your situation, there might be a way to do it in mapshaper... is your geometry points, polygons or lines?

My geometry is points and I have no id field.

Thank you very much

**Comment by mbloch** [comment]
If you have one point per feature (as opposed to "multi-point" features), then the following method should work: 

* generate an identifier for each point based on the point's coordinates
* use `-uniq` to remove the dupes.

Like this:
```
mapshaper points.json -each 'key = this.x + "," + this.y' -uniq key -o unique_points.json

```

If you have multi-points, then insert the `-explode` command before your `-each` command.

**Comment by aborruso** [comment]
@mbloch you are a master, thank you
