### ISSUE TITLE
Unfortunately, mapshaper can't run in this web browser:  Chrome (70)

### ISSUE THREAD

**Issue by jparish3** [mbloch/mapshaper#311]
I am getting the error message below after latest Chrome update

Unfortunately, mapshaper can't run in this web browser
For best results, try Google Chrome or Mozilla Firefox.

Google Chrome is up to date
Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by mbloch** [comment]
Mysterious... I just upgraded to the same version (Version 70.0.3538.110 (Official Build) (64-bit)) and I don't see that error. Could you provide a bit more info?

* Are you using mapshaper on the public website (https://mapshaper.org)?
* What OS are you using?
* Can you paste a screenshot of the error?
* Are there any JavaScript errors in the web developer console?

Thanks!

**Comment by jparish3** [comment]
- Are you using mapshaper on the public website (https://mapshaper.org)?
   yes
   - What OS are you using?macOS  Mojave 10.14.1
   - Can you paste a screenshot of the error? attached
   - Are there any JavaScript errors in the web developer console?
   yes...see below

GET https://mapshaper.org/page.css net::ERR_CONTENT_DECODING_FAILED 200
(index):250 GET https://mapshaper.org/zip.js
net::ERR_CONTENT_DECODING_FAILED 304
(index):256 Uncaught ReferenceError: zip is not defined
    at (index):256

Joe Parish
Managing Partner
SPATIALytx
101 South Tryon St
Suite 2700
Charlotte, NC 28280
704.458.4798

**Comment by mbloch** [comment]
Thanks for the info, I'll investigate.

**Comment by jparish3** [comment]
thanks. let me know. your tool is a highly valued resource.
BTW; I am able to use your site on Chrome Canary on the mac


Google Chrome is up to date
Version 72.0.3622.0 (Official Build) canary (64-bit)




Joe Parish
Managing Partner
SPATIALytx
101 South Tryon St
Suite 2700
Charlotte, NC 28280
704.458.4798

**Comment by mbloch** [comment]
I tried and failed to reproduce this problem last year. Now that Chrome is on version 78, I'm going to go ahead and close this issue. If this happens again, I'd like to know about it. Thanks :)
