### ISSUE TITLE
Ability to add a bbox to each feature, not just the entire collection

### ISSUE THREAD

**Issue by rdmurphy** [mbloch/mapshaper#312]
Hello! 👋

Was curious if it is possible to add a `bbox` to each Feature in a collection, not just to the collection itself? I know it's possible to do so against the entire collection with the `bbox` flag. AFAICT that's technically kosher [according to the spec](https://tools.ietf.org/html/rfc7946#section-3). I know I could work it into the properties, but wanted to check and see if I had perhaps missed that it's already possible! If not, would that be a worthwhile feature?

Either way, thanks for Mapshaper! It's a wonderful tool to have.

**Comment by mbloch** [comment]
Hi,

I just took another look at the spec, which says that any "GeoJSON object" can have a bbox. That seems to mean any object with a "type" member, per the spec.

Nobody's requested feature-level bboxes yet and I haven't needed them myself, so I never added it.

For a feature, would you add bbox to the "Feature" object or to its geometry? The spec doesn't specify.

Could you describe your use case briefly? If it's something that many people could use, I can add it.

**Comment by mbloch** [comment]
This feature needs more discussion before it can be implemented... feel free to re-open if you have further suggestions.

**Comment by rdmurphy** [comment]
Hello @mbloch! Finally spinning back around to this (as you may notice my interest in this is pinned to political seasons 🙃).

As you mentioned [Section 5](https://tools.ietf.org/html/rfc7946#section-5) suggests this is also valid on `Feature` objects, and the example it gives is to put it adjacent to the `type` and `geometry` fields:

```
   Example of a 2D bbox member on a Feature:

   {
       "type": "Feature",
       "bbox": [-10.0, -10.0, 10.0, 10.0],
       "geometry": {
           "type": "Polygon",
           "coordinates": [
               [
                   [-10.0, -10.0],
                   [10.0, -10.0],
                   [10.0, 10.0],
                   [-10.0, -10.0]
               ]
           ]
       }
       //...
   }
```

I do see how this is a little funky when compared to the other `bbox` applications, but I think having it adjacent to the `type` is functionally consistent across collections and Features.

My original (and now!) use case is to be able to quickly do a rough filter on a collection of Features without having to go full "point in polygon." In other words, I want the ability to check whether a point is within the `bbox` of a Feature at all before doing the more intensive check.

It's very easy for me to alter my GeoJSON to do this after exporting from Mapshaper so there's no blocker here, but because it's endorsed as valid by the GeoJSON spec I could see some value in having this be an option like `bbox-feature` or something similar to complement the current `bbox` parameter that creates one for the entire collection.

Thank you!
