### ISSUE TITLE
it is not obvious that -style can be used many times to apply multiple stylings

### ISSUE THREAD

**Issue by matkoniecz** [mbloch/mapshaper#313]
I tried

```
mapshaper -i polygon.geojson -lines target=1 -style "stroke=red, stroke-width=10" -o polygon_double.svg
mapshaper -i polygon.geojson -lines target=1 -style "stroke=red; stroke-width=10" -o polygon_double.svg
mapshaper -i polygon.geojson -lines target=1 -style "stroke=red stroke-width=10" -o polygon_double.svg
```

before discovering 

`
mapshaper -i polygon.geojson -lines target=1 -style "stroke=red" -style "stroke-width=10" -o polygon_double.svg
`

As documentation is on Wiki, not in repo I created issue rather than a PR.

I looked at https://github.com/mbloch/mapshaper/wiki/Command-Reference https://github.com/mbloch/mapshaper/wiki/Introduction-to-the-Command-Line-Tool

**Comment by mbloch** [comment]
Hi, I just added an example to the wiki to show the most concise way to add multiple style properties to a layer:
https://github.com/mbloch/mapshaper/wiki/Command-Reference#-style

**Comment by matkoniecz** [comment]
Thanks!
