### ISSUE TITLE
Unhelpful "[dissolve2] Error: 1"

### ISSUE THREAD

**Issue by matkoniecz** [mbloch/mapshaper#314]
I tracked it to being caused by mix of polygons and points in merged data.

```
{
"type": "FeatureCollection",
"features": [
{
  "type": "Feature",
  "id": "way/52004195",
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          19.9275616,
          50.0560056
        ],
        [
          19.9274007,
          50.055978
        ],
        [
          19.9275616,
          50.0560056
        ]
      ]
    ]
  }
},
  "geometry": {
    "type": "Point",
    "coordinates": [
      19.9282914,
      50.0558418
    ]
  }
}
]
}
```

**Comment by mbloch** [comment]
Hi, the snippet you pasted above is not valid JSON (the second Feature is malformed).

Mapshaper layers have a single geometry type, unlike GeoJSON collections. If you import GeoJSON with more than one kind of geometry (point, line, polygon), then a separate layer will be created for each geometry type.

Mapshaper's `-info` command can help you understand how your data was imported. For example:
```bash
mapshaper data.geojson -info
```

**Comment by matkoniecz** [comment]
I solved it for me (I added `osmfilter` that drops unused parts of input data so point geometries are not created).

I still think that "Error: 1" is not a good warning message.

> (the second Feature is malformed).

What is wrong with it?

> mapshaper data.geojson -info

Thanks,I will use it if in future I will be again confused by what happens.

**Comment by mbloch** [comment]
When I checked your pasted snippet at http://geojsonlint.com/, I got a JSON parse error:
![image](https://user-images.githubusercontent.com/1232222/50361631-407dca00-0532-11e9-8076-d372b0e124d1.png)

I agree that "Error: 1" is not a good message. I'll improve it as soon as I'm able to reproduce it.

--mbloch :)

**Comment by mbloch** [comment]
Ok, I reproduced the "Error: 1"  after fixing your snippet by adding the line `{ "type": "Feature",`. I'll work on improving that message now.

**Comment by mbloch** [comment]
I just released a new version with a fix for the error message bug. Now you should see the message:
`[dissolve2] Error: Expected a polygon layer, received a point layer`

Thanks for reporting this :)

**Comment by matkoniecz** [comment]
So it is fixed and can be closed, right?

Thanks for fixing! I am processing OpenStreetMap data into files that can be send to a laser cutter and Mapshaper is currently one of the most important tools that I use (I am making 3D map of a traffic crossing for blind people).
