### ISSUE TITLE
consider listing preferred option before deprecated option

### ISSUE THREAD

**Issue by matkoniecz** [mbloch/mapshaper#315]
https://github.com/mbloch/mapshaper/wiki/Command-Reference#-i-input

> merge-files and combine-files change this behavior.

and

> merge-files (Deprecated) Merge features from multiple input files into as few layers as possible. Preferred method: import files to separate layers using -i combine-files, then use the -merge-layers command to merge layers.

>combine-files Import multiple files to separate layers with shared topology. Useful for generating a single TopoJSON file containing multiple geometry objects.

In both cases listing `combine-files` first would be preferable as it is not deprecated version of doing this

**Comment by mbloch** [comment]
ok, done
