### ISSUE TITLE
feature request: quick map viewer

### ISSUE THREAD

**Issue by mroswell** [mbloch/mapshaper#32]
As we make various files, it would be great to have a quick command line for a browser-based viewer. Something like:

bin/mapshaper-gui ../maps/output1/cong133b.json
 or 
bin/json-viewer ../maps/output1/cong133b.json

which:
- just loads the file (or maybe offers the option to modify it)
- doesn't error out because the port is already taken
- (maybe even works for shapefiles?)

In the meantime, what's the fastest way you use to view files? I do have a copy of QGIS open, but just wonder if there's somehow a quicker view option.

**Comment by danvk** [comment]
I assume I'd be able to run

```
mapshaper-gui path/to/features.geojson
```

I'd be happy to take a crack at implementing this if there's interest.

**Comment by danvk** [comment]
Worth noting: The `geojsonio ` command line tool often works great. But because it uses gists, it's limited to GeoJSON files that are <1MB.

**Comment by mbloch** [comment]
I like `mapshaper-gui path/to/features.geojson`

If you want to load a Shapefile,  `mapshaper-gui path/to/features.shp` should probably also bring in the *.dbf and *.prj files (if they exist).

**Comment by danvk** [comment]
Sent out #127 to fix this. It works pretty well for GeoJSON and TopoJSON!

**Comment by mbloch** [comment]
The newly published version 0.3.22 adds support  to `mapshaper-gui` for loading one or more files (thanks @danvk for the pull request and interface suggestions).

**Comment by danvk** [comment]
Just installed and gave it a try. Works perfectly. Thanks @mbloch!
