### ISSUE TITLE
unable to load shapefile without explanation what went wrong - probably caused by mapshaper unable to parse given file type

### ISSUE THREAD

**Issue by matkoniecz** [mbloch/mapshaper#320]
`mapshaper -i water-polygons-split.zip -info` gives

`[i] Error: Unable to import water-polygons-split.zip
Run mapshaper -h to view help`

-----

`ls -l | grep water-polygons-split.zip`

gives

`-rw-r--r-- 1 mateusz rvm 530812489 gru 28 22:50 water-polygons-split.zip`

I obtained file from http://openstreetmapdata.com/data/water-polygons (the first download option)

**Comment by matkoniecz** [comment]
On additional debug - it turned out to be necessary to extract zip and take `water_polygons.dbf` and `water_polygons.shp` and specify `water_polygons.shp` as the input file.

**Comment by mbloch** [comment]
Currently only the web version of mapshaper can read and write .zip files. I'll add a more informative error message.

I never added .zip file support to the command line tool -- it's up to the user to run `unzip` or the equivalent utility.

**Comment by matkoniecz** [comment]
Not using .prj file is also intentional, right? It is certainly not complaining if `.prj` file is not present and it seems that my current mismatch problems is projection related.

> I'll add a more informative error message.

That would be great, thanks!

**Comment by mbloch** [comment]
Mapshaper will load a .prj file if its present. If there is no .prj file and the coordinates are in the lat-long range, WGS84 is assumed.

**Comment by mbloch** [comment]
I improved the error message when trying to read unsupported file types... will be included in the next release.
