### ISSUE TITLE
project bbox parameter in clip command

### ISSUE THREAD

**Issue by matkoniecz** [mbloch/mapshaper#321]
`mapshaper -i water_polygons.shp -clip source=1 bbox=18.53,54.32,18.69,54.48 -o test.geojson`

results in `[clip] Error: Unable to combine projected and unprojected datasets`. From what I see at https://github.com/mbloch/mapshaper/wiki/Command-Reference#-clip there is no way to manually project bbox specified as a parameter.

I also think that in this case automatic projection is reasonable.

source is 3857 projected shapefile from http://openstreetmapdata.com/data/water-polygons 

If that would be useful I can try reproducing it with a smaller dataset.

**Comment by mbloch** [comment]
Automatic reprojection would be useful in some situations, but I don't have the time to implement it. There are workarounds that you can use. You can create a rectangle using the `-rectangle` command, reproject the rectangle and use that to clip your shapes. (This will work well for Mercator but not most other projections). 

```
mapshaper input.shp \
-rectangle bbox=<coords> \
-proj match=input.prj \
-target 1 \
-clip 2 \
-o clipped.shp
```

You could also unproject your data to wgs84, clip with a lat-long bbox, then project back to the original data (which would be slower).

**Comment by matkoniecz** [comment]
Thanks! I will try this solution (thank you very much for providing it!).

Should I close this issue?
