### ISSUE TITLE
warn that .shp to .geojson conversion is not supported

### ISSUE THREAD

**Issue by matkoniecz** [mbloch/mapshaper#322]
per https://github.com/mbloch/mapshaper/issues/82#issuecomment-122708037 it is recommended to use rather `ogr2ogr` rather than mapshaper.

Based on docs I expected that I can mix input and output data formats.

Maybe it would be a good idea to warn users that input shapefile with geojson output is likely to result in problems?

(in my case [produced geojson](https://gist.githubusercontent.com/matkoniecz/fc9d1a602a26fe792ca14aa8e4cdaed9/raw/a8855c5f468aa831663a33d9b848e19fce01d67a/borked.geojson) has order-of-magnitude coordinate error like `2066320.213864947,7258354.896209966` with broken right-hand rule according to http://geojsonlint.com/)

**Comment by mbloch** [comment]
geojsonlint checks for GeoJSON that conforms to the [rfc7946](https://tools.ietf.org/html/rfc7946) specification, which specified "right hand rule" winding order and WGS84 coordinates.

If RFC7946-compliant GeoJSON is important to you, then you can project to WGS84 using `-proj wgs84` and apply the winding rule by adding `rfc7946` as a flag to the `-o` command.
