### ISSUE TITLE
feature request: command line generator

### ISSUE THREAD

**Issue by mroswell** [mbloch/mapshaper#33]
Would be nice if after using the mapshaper-gui, we could generate a command line that reflects the same settings that were just applied.

(I'm curious, too, how to reflect the shapefile + dragged-to-GUI dbf, on the command line.)

**Comment by mbloch** [comment]
This feature has been requested by several people. I think it will be even more useful now that the web ui has a built-in command line with many editing functions. Being able to export an entire session as a sequence of command line arguments would be useful for documentation. You could also put the generated commands into a Makefile and apply the exact same sequence of tasks again, say, when an input dataset gets updated.

I can envision this as a console command. The output would be written to the console. Users could select and copy the output from there. Any other ideas?

**Comment by blacki** [comment]
Great idea! This would be very helpful.

**Comment by mbloch** [comment]
v0.4.141 has an initial implementation of this feature. Run `history` in the browser console to see a command line version of the current mapshaper session.
