### ISSUE TITLE
drifiting centroids with quite small polygons

### ISSUE THREAD

**Issue by burritojustice** [mbloch/mapshaper#330]
Hey Matt-

I've been having trouble with mapshaper and centroids of quite small polygons (specifically buildings) -- they seem to drift in random directions. Here is a GIF of the polygons, their actual centroids, and what results from `-points inner`. (Same issue with `-points centroid`)

![uncentroids](https://user-images.githubusercontent.com/3979711/54330535-65cf2100-45d3-11e9-849b-ab3fcb74176d.gif)

I saw https://github.com/mbloch/mapshaper/issues/304 but while those were really small, these polygons are really quite small.

Maybe some more rounding and floating point errors?

Here are some buildings to test with. 
[kamloops.geojson.zip](https://github.com/mbloch/mapshaper/files/2964828/kamloops.geojson.zip)

Thanks!

**Comment by mbloch** [comment]
Hi,

I wasn't able to reproduce this problem. I tested as follows:
* Imported kamloops.geojson using the mapshaper.org web UI.
* Ran `points inner +` in the web UI console.
* Turned on visibility for both layers and looked for misplaced points.
* Exported the point layer as GeoJSON and re-imported
* Looked for misplaced points in the re-imported points layer.

I have a couple of questions:
* If you used the command line tool, do you have the current version? (0.4.107)
* Can you send me your output file containing shifted point coordinates, along with the exact commands you used to generate it?

Thanks :)

P.S. here is a screenshot showing part of the original layer and the derived points:
![image](https://user-images.githubusercontent.com/1232222/54394766-35938b00-4684-11e9-89e4-6291acce8a78.png)

**Comment by burritojustice** [comment]
So... turns out I was running 0.4.67 -- apologies. Thought I was on a much much more recent build of the CLI, and upgrading obviously fixed it. Sorry for the runaround.
