### ISSUE TITLE
Add Patterson projection

### ISSUE THREAD

**Issue by kapooostin** [mbloch/mapshaper#331]
Current version of Proj includes it https://proj4.org/operations/projections/patterson.html.
I tried `+proj=patterson`in mapshaper but it fails with `unknown projection id`.

Information about projection http://cartographicperspectives.org/index.php/journal/article/view/cp78-patterson-et-al/1362

**Comment by mbloch** [comment]
I just added the "Patterson" projection and published a new version, 0.4.110.

**Comment by kapooostin** [comment]
Thank you!

**Comment by kapooostin** [comment]
The projection works fine, but exporting the resulting file to `Shapefile` warns that Mapshaper was `Unable to generate .prj file`.

**Comment by mbloch** [comment]
Hi @kapooostin,
I'm looking into the best way to generate a .prj file for Patterson. It appears the QGIS and gdal support Patterson by adding the following property to the WKT text: `EXTENSION["PROJ4","+proj=eqearth +datum=WGS84 +wktext"]`. I could do the same, which should allow Mapshaper to interoperate with these other software packages. I'm pretty sure that ArcGIS would not be able to interpret this kind of .prj file. I guess we can probably live with that.

**Comment by kapooostin** [comment]
@Hi @mbloch,
I certainly can, because i'm on mac. How could I test it?

**Comment by mbloch** [comment]
I just released v0.4.135 with support for generating .prj files for Patterson and other projections that don't have predefined WKT definitions. You can test it by running the latest version of mapshaper.

**Comment by kapooostin** [comment]
Thank you! QGIS opens it without any problems and successfully reprojects the data I add.
