### ISSUE TITLE
Strange bejavior newly

### ISSUE THREAD

**Issue by morenj96** [mbloch/mapshaper#332]
![image](https://user-images.githubusercontent.com/19172238/55228308-70c2bc00-5237-11e9-9811-3517de597454.png)

Since shown in the screenshot, I cant work with the site, even buttons don't work

**Comment by mbloch** [comment]
I haven't seen this problem before... does it occur if you use a different browser? Also, is there an error in the browser's developer tools console? Also, what version of Firefox are you using? 
Thanks
--mbloch

**Comment by morenj96** [comment]
Really not different browser, but since I updated Firefox, I hadn't use MapShaper.
Firefox Quantum 65.0.2
Can new update be my problem reason?

**Comment by mbloch** [comment]
I can't tell what the problem is without more information. Does the problem occur when you import different files? Can you try importing just one .shp file? If the problem is related to a particular set of files, I'd like you to send them to me, so I can replicate the issue.

Also, can you check the console for error messages?

Thanks :)

**Comment by morenj96** [comment]
Yes, I've imported different files, even with different extensions (shp, zip, ...)
No I can, I see same problem.
No, I don't know what's console

**Comment by mbloch** [comment]
To view the console, click on the settings menu in the upper right corner of the browser window, then select "Web Developer", then click on "Web Console".  Sometimes, an error on a website will be displayed in the console.

**Comment by morenj96** [comment]
I did want to check again and view the console, but seems the problem doesn't exist anymore. I could upload and export well.
thank you for your website

**Comment by mbloch** [comment]
Please let me know if the problem occurs again.
