### ISSUE TITLE
How do I use `merge-layers` in the web interface?

### ISSUE THREAD

**Issue by amandabee** [mbloch/mapshaper#334]
#172 is related but seems to predate the `merge-layers` function. #268 also seems related but the issue appears to be resolved and I'm still hitting walls. 

I'm using mapshapers web interface and it looks like I should be able to collapse two layers with `merge-layers`:

    $ help merge-layers
    Command
      -merge-layers merge multiple layers into as few layers as possible
    
    Options
      force         merge layers with inconsistent data fields
      name=         rename the edited layer(s)
      target=       layer(s) to target (comma-sep. list)

But the `target=` attribute isn't working: 

    $ merge-layers target=bayarea_county,california_places_clipped
    [merge-layers] Use the target= option to specify multiple layers for merging

I tried putting the list in quotes and got:

    $ merge-layers target='"bayarea_county","california_places_clipped"'
    Missing target: "bayarea_county","california_places_clipped"
    Available layers:   [1]  bayarea_county
      [2]  california_place_clipped

How do I use `merge-layers` in the web interface?

**Comment by mbloch** [comment]
Hi,
Mapshaper is getting confused by the nested quotation marks in your command. The command should work if you use:
`merge-layers target='bayarea_county,california_places_clipped'`
This should work too:
merge-layers target=bayarea_county,california_places_clipped

**Comment by mbloch** [comment]
@amandabee I re-read your comment... I see that you originally used what looks like the correct syntax (without nested quotes).

I'm attaching a .zip file containing two GeoJSON files. If you drop the files onto the web UI and run `merge-layers target=group1,group2`, the layers should get merged.  If merging works for you with my test files but not your own data files, please send me your files and I will investigate.
[group.zip](https://github.com/mbloch/mapshaper/files/3060474/group.zip)

**Comment by amandabee** [comment]
Ahh. Okay. With that first syntax I do get an error:

```
$ merge-layers target=bayarea_county,california_place_clipped
Fields [PLACE, PLACENUM, NAME, OBJECTID, FIPSSTCO] are missing from one or more layers
```

I assume this means that I need to ensure that both layers have the same fields before I can merge them. Can I just force a merge?

**Comment by mbloch** [comment]
Yes, you can force a merge by adding the "force" option to the command.

To see the all the options for a particular command, in the console you can run, e.g., `-h merge-layers`.

There's also a Wiki page on Github: https://github.com/mbloch/mapshaper/wiki/Command-Reference#-merge-layers

**Comment by amandabee** [comment]
Thank you. 

https://github.com/amandabee/workshops/blob/master/2019/advanced_media_institute/mapshaper.md

I was working on getting a local basemap that I can import to Datawrapper. If it's worth adding this as a tutorial on the wiki, I can finish it out as at least a baseline?
