### ISSUE TITLE
exporting simplified geojson data to topojson is broken

### ISSUE THREAD

**Issue by nharrisanalyst** [mbloch/mapshaper#338]
I uploaded geojson data then simplified it and then exported it to topojson and that file is corrupted and it does not work in a d3 projection or in mapstarter

**Comment by mbloch** [comment]
If you send me both the input GeoJSON file and the output TopoJSON file, I'll be happy to investigate.

**Comment by mbloch** [comment]
I checked mapstarter.com.... This site appears not to accept data that includes null (or empty) shapes. During simplification, some polygons may collapse, creating empty shapes in the output file. You can remove the empty shapes by running the following console command: `-filter remove-empty`. After removing empty shapes, you should be able to import TopoJSON, GeoJSON and Shapefiles generated by mapshaper.

Without looking at your d3 code, I can't tell what the problem there is.
