### ISSUE TITLE
Unable to generate .prj file for stereographic projection

### ISSUE THREAD

**Issue by TomBor** [mbloch/mapshaper#339]
No matter the input shapefile (natural earth or a simple rectangle), when I apply a stereographic projection with all parameter by default (`-proj +proj=stere`) and export in shapefile format, mapshaper cannot generate .prj file.

**Comment by mbloch** [comment]
Thanks for reporting this! I just released a new version (v0.4.113) that should fix the problem.

**Comment by TomBor** [comment]
Thanks for you very fast fix!
I regularly use Mapshaper for my day to day work and I am always thankful for your amazing work on this tool.
