### ISSUE TITLE
Combine commands: in example clip and filter

### ISSUE THREAD

**Issue by aborruso** [mbloch/mapshaper#341]
Hi,
is it possible to combine in a single command two one?

I would like to clip a points layer using a polygons layer, filtered using one of its attribute: all points that clip the items of polygons layer with 'FIELD_A > 12'

Is it possible to do it one command, or do I must proceed by steps: first the filter and than the clip?

Thank you

**Comment by mbloch** [comment]
You have to run the commands in sequence. Do you see an advantage to combining multiple functions in a single command?

**Comment by aborruso** [comment]
@mbloch I use the cli (not able to write nodejs script) and I would like to do not produce temporary output files.
To use a sort of piping inside the command (for me) would be great.

Thank you

**Comment by mbloch** [comment]
The CLI does not limit you to running a single command... something like piping is already built in. So you can do:

```
mapshaper points.shp -filter 'FIELD_A > 12' -clip polyygons.shp -o clipped_points.shp
```

Most of the examples in the Wiki demonstrate a single command, but you can use any number of commands when you run the program. The commands are run in sequence, from left to right.

**Comment by aborruso** [comment]
@mbloch in

    mapshaper points.shp -filter 'FIELD_A > 12' -clip polygons.shp -o clipped_points.shp

the filter is applied to points.shp or to polygons.shp? I'm sorry for the question but I need to apply it to the polygon layer: all points that clip the items of polygons layer (the polygon items with 'FIELD_A > 12').

**Comment by mbloch** [comment]
I see... to filter the polygons layer, you'll have to import it prior to the `-clip` command. This should work.

```
mapshaper polygons.shp -filter 'FIELD_A > 12' -i points.shp -clip polygons -o clipped_points.shp
```

**Comment by aborruso** [comment]
As usual @mbloch and mapshaper are great!

It works, thank you
