### ISSUE TITLE
Editing null feature no longer available

### ISSUE THREAD

**Issue by pearlearing77** [mbloch/mapshaper#344]
Hi Matt,
Just couple of Month Ago I was able to get a converted DXF to geojson, then convert it to polygons, write each id=id, and then i can edit all the null fields and assign them name. I can't seem to do that anymore. I am using chrome, on mac and that didn't work. I tried safari and firefox. Was this feature removed. So i basically upload a shapefile, then in the console i say "dissolve", then "clean", then "each id=id". I later click on the "i" i don't see them highlighted in blue anymore, so when i click on the null i can't edit. Thank you so much for looking into it.

**Comment by mbloch** [comment]
I changed the interface a bit. Now, if you click on the "i" icon, a triangle appears to the left of the icon. Click on that, and you get a flyout menu for selecting from two or more editing modes. By default, data editing is turned off. If you want to edit data properties interactively, you need to click on the "data" label.

Black triangle, menu closed:
![image](https://user-images.githubusercontent.com/1232222/58055167-de4de300-7b2a-11e9-8e81-3554d6362572.png)

Flyout menu open:
![image](https://user-images.githubusercontent.com/1232222/58055331-6af8a100-7b2b-11e9-97b5-f19f0d956242.png)

The reason for the change is that I wanted to add several different editing modes. Now there's a mode for changing the location of point symbols by dragging them, and a mode for changing label position of labels (label layers are not documented yet).

**Comment by pearlearing77** [comment]
Thank You Matt. I now see it and can edit.
