### ISSUE TITLE
join with duplicate entries

### ISSUE THREAD

**Issue by 2803media** [mbloch/mapshaper#345]
I try to do the following process:

I have a geojson with geometry and properties and I have csv files with id which can be map to the geojson file. The problem is that those id are not uniq in this csv so I wonder (and can't find a way to do that) if it's possible to join the csv to the geojson in a child object in order to populate duplicate entries from the csv into the geojson.

Thanks for you input on the feasibility of this !

**Comment by mbloch** [comment]
It sounds like you want to do a many-to-one join. Mapshaper supports many-to-one joins in a somewhat awkward way. The `-join` command has an option named `calc`. There's a description and an example in the wiki (https://github.com/mbloch/mapshaper/wiki/Command-Reference#-join). 

The `calc` option can be used for combining data values from multiple external records, using built-in functions like "sum()", "median()" and "count()". For example, if you want to count the number of csv records that match each shape, you could do:
```
mapshaper shapes.geojson -join data.csv keys=id,id calc='n = count()' -o
```
This creates a field named "n" in your shapes layer, containing the number of csv records that joined to each shape.

Does this address your need, or did you want to do something different?

**Comment by 2803media** [comment]
thanks @mbloch for your reply, here is more detail of my problematic.

My geojson is a classic one, with geometries and properties and for each feature an unique id. And I have a csv file with informations related to the id of the geojson but for some ids I have multiple entries in my csv file. So the aim is to populate a new field in my geojson with each data matching the id.

Here is an example of one feature of my geojson file:

`{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[1.5876762,50.5286659],[1.5877074,50.5287045],[1.5879429,50.5286227],[1.5879256,50.5286003],[1.5879127,50.5285835],[1.5878851,50.5285931],[1.5877308,50.5286469],[1.5876762,50.5286659]]]},"properties":{"id":"62826000AN0635","contenance":68},"id":"62826000AN0635"},`

And what I desire with the "join" of my csv (adding a new field csv2017 with the datas):

```
{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[1.5876762,50.5286659],[1.5877074,50.5287045],[1.5879429,50.5286227],[1.5879256,50.5286003],[1.5879127,50.5285835],[1.5878851,50.5285931],[1.5877308,50.5286469],[1.5876762,50.5286659]]]}"properties":{"id":"62826000AN0635","contenance":68,
"csv2017": [{
			"id": "62826000AN0635",
			"date": "oct 2017",
			"code": 3
			},{
			"id": "62826000AN0635",
			"date": "nov 2017",
			"code": 2
		},{
			"id": "62826000AN0635",
			"date": "dec 2017",
			"code": 1
		},{
			"id": "62826000AN0635",
			"date": "jan 2017",
			"code": 3
		}]},
"id":"62826000AN0635"},
```

My csv looks like this:

id - date - code
62826000AN0635 - oct 2017 - 3
62826000AN0635 - nov 2017 - 2
62826000AN0635 - dec 2017 - 1
62826000AN0635 - jan 2017 - 3

Thanks again for your help

**Comment by 2803media** [comment]
With calc and collect() I can create multi arrays:

`mapshaper 62826.json -join 62826-2017-new.csv calc='csv2017 = collect(date), csv2017_2 = collect(code)' keys=id,id_parcelle -o new100.json`

`"properties":{"id":"62826000AN0635","contenance":28,"csv2017":["2017-862428","2017-862428","2017-862444","2017-863030","2017-863030","2017-863240","2017-863278","2017-863381","2017-863907","2017-863907","2017-864270","2017-864746","2017-864841","2017-864845"],"csv2017_2":[265000,265000,126000,105000,105000,145100,195000,180000,155000,155000,214000,183000,176500,196500]},"id":"62826000AA0006"},
`

But it's not exactly what I search... Is it possible to collect multiple fields with calc?

**Comment by mbloch** [comment]
You can try using `collect(this.properties)` to create arrays of objects, like you wanted to do:
```
mapshaper 62826.json -join 62826-2017-new.csv calc='csv2017 = collect(this.properties)' keys=id,id_parcelle -o new100.json
```

If you wanted to collect a subset of fields from the csv, you could do something like: `collect({date: date, code: code})`

**Comment by 2803media** [comment]
@mbloch this is exactly what I want! 
Thanks again for this incredible tool.
