### ISSUE TITLE
Getting the unshared coordinates of two features

### ISSUE THREAD

**Issue by yttcs** [mbloch/mapshaper#347]
Getting the shared coordinates of two features is straightforward:

-filter 'Name=="featurename1" || Name =="featurename2"' -innerlines

Getting the unshared coordinates of two features doesn't appear to be so straightfoward. Is there something like -outerlines that would do the job?

**Comment by mbloch** [comment]
The `-lines` command adds attributes to each line that you can use for filtering, e.g.:
```
-filter 'Name=="featurename1" || Name =="featurename2"' -lines -filter 'TYPE == "outer"'
```

I guess I should add `-outerlines`... haven't yet because the number of commands is getting so large, it's hard for people to scan through the list of commands that `-help` outputs.
