### ISSUE TITLE
Read shapefile without import

### ISSUE THREAD

**Issue by HuuPhucDang** [mbloch/mapshaper#349]
Hi, i want to read shapefile or .zip in default directory when running, but i don't know how to do it

**Comment by mbloch** [comment]
Hi, what do you mean by "when running"? Do you want to invoke mapshaper from your own program? This wiki page has some information about using mapshaper from another program: https://github.com/mbloch/mapshaper/wiki/Using-mapshaper-programmatically

Also, what do you mean by "without import"? Do you want to get information about a Shapefile without actually importing all the data from the Shapefile? Mapshaper is not designed to be used like this.

**Comment by HuuPhucDang** [comment]
oh, i understand, thank you so much
