### ISSUE TITLE
Overlay between polygons and attributes

### ISSUE THREAD

**Issue by aborruso** [mbloch/mapshaper#353]
Is it possible to do Union in mapshaper and produce the intersection between all polygons and have also the values combination as output?

|ID|Value|
|---|---|
|1|A|
|2|A,B|
|3|A,B,C|
|4|A,C|
|5|B|
|6|C|
|7|B,C|

![image](https://user-images.githubusercontent.com/30607/64076833-2b188c80-ccca-11e9-8b20-3a7109e71f9f.png)

Thank you

**Comment by aborruso** [comment]
I think the steps should be:

- -lines\<input \>output01
- -polygons\<output01 \>output02
- -points inner\<output02 \>output03
- `mapshaper output03 -join input  calc='Value = collect(polyField)' -o joinpoints.geojson`

**Comment by mbloch** [comment]
This should be available as a single command, I'll look into it when I have some free time.

**Comment by aborruso** [comment]
> This should be available as a single command, I'll look into it when I have some free time.

Wow, it would be great. Than I reopen it

**Comment by aborruso** [comment]
@mbloch it's in some way related to https://github.com/mbloch/mapshaper/issues/239#issuecomment-365295777

**Comment by aborruso** [comment]
@mbloch is the new mosaic function related to this issue?

Thank you

**Comment by mbloch** [comment]
The -mosaic command is related to this issue, in the sense that it provides a more direct way to put together this functionality out of a series of existing commands. A single -mosaic command can replace the -lines -polygons sequence that you used in your example above.

I'm planning to implement the overlay feature in a way that avoids having to calculate inner points and do a point-to-polygon join, but for now, this is a workaround that you can use.

Cheers,
Matt

**Comment by pigreco** [comment]
@mbloch 
thank you so much!

**Comment by aborruso** [comment]
@mbloch thank you very much.

I have tested it, it's great.

How to transfer the source attributes to the mosaic polygons? Via `-join input calc='Value = collect(polyField)' is it possibile?`

**Comment by geodata4all** [comment]
I have also tested -mosaic command. It is awesome.

It will be also nice if output gaps/overlaps polygon has some sort of flag (1=gap, 2=overlap). This flag will be helpful for selecting new gaps/ overlaps polygons from the ouput.

Cheers.

**Comment by mbloch** [comment]
Transferring the source attributes is a multi-step process (which is why we need a real overlap command). The following example is based on the example in the second comment above, and creates a "values" attribute for each mosaic tile, containing attribute values from all overlapping source polygons. The basic approach is to create a layer of points from the mosaic, to a polygon-to-point join to join data from the source polygons to the points, then join the data from the points layer to the mosaic layer.

```
-mapshaper polygons.json` \
	-mosaic + name=mosaic \
	-each 'key = this.id' \
	-points inner + name=points \
	-join polygons calc='values = collect(polyField)' \
	-target mosaic \
	-join points keys=key,key \
	-o out.json
```

**Comment by aborruso** [comment]
wow, it works, thank you!!

```
mapshaper polygons.json \
	-mosaic +name=mosaic \
	-each 'key = this.id' \
	-points inner + name=points \
	-join polygons calc='values = collect(fieldname)' \
	-target mosaic \
	-join points keys=key,key \
	-o out.json
```

**Comment by aborruso** [comment]
And now, using 0.4.142, it's super easy:

```
mapshaper input.geojson -mosaic calc='outputField=collect(inputField).toString()' -o output.shp
```

`inputField` is the input field with the values I want to collect and `outputField` is the output field with the collectd values.

@mbloch thank you very much, it's really fantastic

**Comment by aborruso** [comment]
Hi @mbloch I have written a blog post in Italian about the great mosaic command https://medium.com/tantotanto/unire-i-poligoni-di-un-layer-con-grande-semplicit%C3%A0-%C3%A8-un-lavoro-soltanto-per-mapshaper-2aedec0e484

Thank you again
