### ISSUE TITLE
-polygons does not transform in polygons all enclosed areas

### ISSUE THREAD

**Issue by aborruso** [mbloch/mapshaper#354]
Hi,
I have [this layer](https://github.com/mbloch/mapshaper/files/3563923/tmp_dbg_lines.zip)

![image](https://user-images.githubusercontent.com/30607/64082555-29be8280-cd11-11e9-84fd-05c54b989131.png)

If I run `-polygons` to it, I have

![image](https://user-images.githubusercontent.com/30607/64082558-3f33ac80-cd11-11e9-9eac-db3395a63f62.png)

and not

![image](https://user-images.githubusercontent.com/30607/64082573-55da0380-cd11-11e9-97b5-368d60918bca.png)

How to have all enclosed polygons as output?

Thank you

**Comment by aborruso** [comment]
If I run -simplify before -polygons I have the right output

**Comment by aborruso** [comment]
It's ok using `precision`

    mapshaper input.shp -o precision=0.000001 simplified.shp
    mapshaper simplified.shp -polygons -o polygons.shp

**Comment by mbloch** [comment]
Hi @aborruso , I just tested `-polygons` using the sample data layer that you attached above. It worked as expected without changing the precision. I recently made some improvements to how mapshaper detects intersections between lines -- that might be why it's working now.

If you see this problem again, please report it and I'll investigate.

--mbloch

**Comment by aborruso** [comment]
@mbloch I'm really impressed, it works.

mapshaper  is a tool out of the ordinary
