### ISSUE TITLE
Split lines with lines

### ISSUE THREAD

**Issue by aborruso** [mbloch/mapshaper#355]
Hi,
starting from a single layer, how to split lines with lines and obtain something like the image below?

It there is a way I solve also #354 

Thank you

![image](https://user-images.githubusercontent.com/30607/64156554-4358ea80-ce35-11e9-99b8-e29767bad564.png)

**Comment by mbloch** [comment]
I just updated the `-clean` command in a way that might help with this (v0.4.146).

If you run `mapshaper lines.shp  -clean -explode -o` do you get the desired output? The -clean command should convert line features to multi-part line features at the points of intersection, and the -explode command coverts multi-part features to multiple single-part features.

If this doesn't work as desired, I might be able to add a `-divide` command to accomplish what you want to do.

**Comment by aborruso** [comment]
As usual it works great.

Thank you

P.S. where can I read about what's new in `-clean` command?

**Comment by mbloch** [comment]
@aborruso I updated the Command Reference page of the wiki with updated information about the -clean command (https://github.com/mbloch/mapshaper/wiki/Command-Reference#-clean). 

I'm planning eventually to set up a documentation site for mapshaper, but I've been spending my available time working on fixing bugs and adding new features instead of writing documentation ;)

**Comment by aborruso** [comment]
Ok @mbloch I reope

> It seems to me that -clean doesn't exactly do what you want in terms of dividing lines where they cross other lines.... Dividing lines at intersections seems like a useful feature to me... It should also be possible to divide a line layer by a polygon layer (for example, splitting roads where they cross international borders).... so it seems to me that this issue is not fully resolved.

Ok, I'm reopening it. Thank you for your notes

**Comment by mbloch** [comment]
I just added a `-divide` command, which uses a polygon layer to divide a line layer,  and copies data from polygons to intersecting lines. This is not the feature you asked for... but it seems like the `-clean` command, possibly followed by `-explode`, addresses your use case, @aborruso. If you have a different use case, please reopen this thread again. 
Cheers, mbloch
