### ISSUE TITLE
I cannot build mapshaper on Windows 10

### ISSUE THREAD

**Issue by zbychuk** [mbloch/mapshaper#361]
When I try to run 
`npm run buil`
I get message:
'.' is not recognized as an internal or external command,

I have no problem building other node apps, but I am not an expert in node at all, so it might be something trivial

![image](https://user-images.githubusercontent.com/1868311/65781945-8bbdac80-e144-11e9-9f99-16225454f5bf.png)

**Comment by mbloch** [comment]
Can you tell me, does `node build` work on your system (instead of `npm run build`). If so, I can fix this issue easily.

**Comment by zbychuk** [comment]
I got the below:

[image: image.png]

**Comment by mbloch** [comment]
@zbychuk, could you re-submit that image using the GitHub web interface? It didn't come through via email.

**Comment by zbychuk** [comment]
Can you see it now?
![image](https://user-images.githubusercontent.com/1868311/65820136-533dd180-e21d-11e9-85b0-f7a914cc056e.png)

**Comment by mbloch** [comment]
Thanks! It looks like the build was successful, but with some warnings that you can ignore. I'll look into suppressing those warnings, then I'll update the `npm run build` command so it doesn't fail on Windows.

**Comment by zbychuk** [comment]
I know I might ask stupid questions, please forgive me, but how should I start this compiled one? 
I have tried node ./mapshaper.js but I just get back command prompt, like in the screenshot
The reason I want to recompile is that, I guess, it detects wrong shape of pixels or something else, as map is stretched horizontally, example of map of Poland below, map works ok in the leaflet

![image](https://user-images.githubusercontent.com/1868311/65822118-d6b7ec80-e236-11e9-8114-a2339bde1c29.png)
![image](https://user-images.githubusercontent.com/1868311/65822157-44641880-e237-11e9-8240-a44a5c108c5a.png)
![image](https://user-images.githubusercontent.com/1868311/65822160-475f0900-e237-11e9-97ba-bf551cff7f74.png)

**Comment by mbloch** [comment]
I just updated mapshaper so `npm run build` will work on Windows.

If you install mapshaper using `npm install -g mapshaper`, then you won't need to run `npm run build`. `npm run build` is needed if you have cloned the repo and want to build mapshaper from  source code. Once you've built the source code, you can install mapshaper so it can be run in the Windows console by running `npm link`. (Again, this is not necessary if you installed by running `npm install -g mapshaper`).

About the stretched appearance. Your file contains "unprojected" data, in units of degrees latitude and longitude. Like most GIS software, mapshaper displays latitude and longitude coordinates on a Cartesian plane, along the y and x axes. This makes shapes that are north or south of the equator look stretched horizontally.

Leaflet displays your data using the Mercator projection, so the shapes don't look distorted.

If you don't understand what I'm talking about, you should maybe do some background reading about projections and geographic coordinate systems. Here's a video you can watch: https://www.youtube.com/watch?v=wlfLW1j05Dg
