### ISSUE TITLE
Clip points to polygon

### ISSUE THREAD

**Issue by 2803media** [mbloch/mapshaper#366]
Hi I have a csv file with coordinates of points (lat and lng) and I want to clip this file to a polygon and exclude the points outside the polygon, I try this command:

`/usr/bin/mapshaper /full/59368.csv -clip /full/test.json  -o /full/test.csv`

But it look like it doesn't work as my test.csv is like my 59368.csv file. Do I miss something or maybe it's not possible to clip with points (lat/lng) as entries?

I guess the script don't get the coordinates of the points, is there any way to specify them?

**Comment by mbloch** [comment]
You need to convert the imported csv data to a point-type layer using the `-points` command before you can use the `-clip` command. The below command should work, provided mapshaper can automatically detect the coordinate fields in the csv, and the coordinates in the two files are in the same coordinate reference system.
`/usr/bin/mapshaper /full/59368.csv -points -clip /full/test.json -o /full/test.csv`

**Comment by 2803media** [comment]
@mbloch thanks Matthew it's working perfectly! Everyday I'm impress from your amazing script. Have a great day
