### ISSUE TITLE
feature request: visual feedback on which files are loaded in GUI

### ISSUE THREAD

**Issue by mroswell** [mbloch/mapshaper#37]
Once we're working on a file in the GUI, there's no feedback to remind us which file we loaded. 

Then, if we drag a DBF file (to ensure that that data is included), there's a plus icon for a moment, but then any feedback disappears. (We may hardly see the plus icon if we're on a laptop, where the Finder (or file directory window) is on top of the browser when we drag the file. Sometimes I'm not sure if the file actually arrived.)

(This is related to the feature request #33 )

**Comment by mbloch** [comment]
The new v0.3 web UI has a layers menu. Now, a note will appear if a .shp file is imported without its .dbf.
