### ISSUE TITLE
Force Intersected Side by Side?

### ISSUE THREAD

**Issue by gelinger777** [mbloch/mapshaper#370]
I have a problem that intersected lines  in geojson are not shown  as they come one on another. Could you hint a command  or option i can use on your web version to force intersected lines to move left-right  2-3mm so that both will be visible on the road? 

![image](https://user-images.githubusercontent.com/184276/67045216-213dd200-f12e-11e9-8545-08a76272d572.png)

**Comment by mbloch** [comment]
Mapshaper doesn't have a way to offset routes like that. I'm not sure what tool would be good for that... maybe the commercial Illustrator plugin "MAPublisher."

**Comment by gelinger777** [comment]
thank you @mbloch
