### ISSUE TITLE
Is the projection EPSG:3035 supported?

### ISSUE THREAD

**Issue by 2803media** [mbloch/mapshaper#371]
I wonder know if EPSG:3035 as ETRS89 / LAEA Europe (https://epsg.io/3035) is supported in the -proj option. I try the following command but the proj doesn't seem to be the right one:

My input shp is with a proj EPSG:3035 and I want a wgs84 output

`mapshaper-xl -i data.shp -proj wgs84 from laea -split codeid -o format=geojson`

I also try (I get the last mapshaper version 0.4.139):

`mapshaper-xl -i data.shp -proj wgs84 from='EPSG:3035' -split codeid -o format=geojson`

But it's wrong too

Thanks

**Comment by mbloch** [comment]
If your Shapefile has a valid .prj file, you don't need the `from` option:
`mapshaper-xl -i data.shp -proj wgs84 -split codeid -o format=geojson`.

EPSG:3035 should be supported.

Is the output wildly off or just slightly shifted from the correct coordinates? Do you have a way to verify that your Shapefile is correctly georeferenced (e.g. does QGIS load it correctly?)

If you're pretty sure that Mapshaper is the culprit, I'd appreciate it if you send me your Shapefile, so I can debug the problem.

**Comment by 2803media** [comment]
Thanks Matthew.

Finally after some test and research about the data source, they use EPSG:2154 based on a EPSG:3035 grid, so it's normal that the conversion to wgs84 wasn't good.

So this works:

`mapshaper data.json -proj wgs84 from='EPSG:2154' -o convert.json`

For the record without the "from=", it fail to identify the correct coordinates.

I give you my file (an extract) just below:

```
{"type":"FeatureCollection", "features": [
{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[1221093.8948096188,6211199.48770266],[1221111.6369005793,6210999.445394327],[1220912.8158949688,6210981.684959549],[1220895.0739518777,6211181.727271715],[1221093.8948096188,6211199.48770266]]]},"properties":{"IdINSPIRE":"CRS3035RES200mN2189400E4269200","Id_carr1km":"CRS3035RES1000mN2189000E4269000","I_est_cr":0,"Id_carr_n":"CRS3035RES16000mN2176000E4256000","Groupe":409644,"Depcom":"2B184","I_pauv":0,"Id_car2010":"CRS3035RES200mN2189400E4269200","Ind":28,"Men":15,"Men_pauv":2,"Men_1ind":6,"Men_5ind":0,"Men_prop":11,"Men_fmp":2,"Ind_snv":676130.2,"Men_surf":1254,"Men_coll":7,"Men_mais":8,"Log_av45":11,"Log_45_70":0,"Log_70_90":1,"Log_ap90":3,"Log_inc":0,"Log_soc":0,"Ind_0_3":0,"Ind_4_5":0,"Ind_6_10":0,"Ind_11_17":1,"Ind_18_24":1,"Ind_25_39":3,"Ind_40_54":3,"Ind_55_64":7,"Ind_65_79":7,"Ind_80p":6,"Ind_inc":0,"I_est_1km":1}},
{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[1221111.6369005793,6210999.445394327],[1221093.8948096188,6211199.48770266],[1221292.7156817685,6211217.247791866],[1221310.4579205937,6211017.205487403],[1221111.6369005793,6210999.445394327]]]},"properties":{"IdINSPIRE":"CRS3035RES200mN2189400E4269400","Id_carr1km":"CRS3035RES1000mN2189000E4269000","I_est_cr":1,"Id_carr_n":"CRS3035RES16000mN2176000E4256000","Groupe":3900,"Depcom":"2B184","I_pauv":0,"Id_car2010":"CRS3035RES200mN2189400E4269400","Ind":7,"Men":3.9,"Men_pauv":0.4,"Men_1ind":1.2,"Men_5ind":0,"Men_prop":2.7,"Men_fmp":0.4,"Ind_snv":163911,"Men_surf":269.1,"Men_coll":2.1,"Men_mais":1.8,"Log_av45":2.1,"Log_45_70":0,"Log_70_90":0.6,"Log_ap90":1.2,"Log_inc":0,"Log_soc":0,"Ind_0_3":0.2,"Ind_4_5":0,"Ind_6_10":0,"Ind_11_17":0.4,"Ind_18_24":0,"Ind_25_39":0.4,"Ind_40_54":1.2,"Ind_55_64":1.9,"Ind_65_79":1.9,"Ind_80p":1,"Ind_inc":0,"I_est_1km":1}},
{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[1221310.4579205937,6211017.205487403],[1221292.7156817685,6211217.247791866],[1221491.5365683883,6211235.007539333],[1221509.2789550738,6211034.965238771],[1221310.4579205937,6211017.205487403]]]},"properties":{"IdINSPIRE":"CRS3035RES200mN2189400E4269600","Id_carr1km":"CRS3035RES1000mN2189000E4269000","I_est_cr":1,"Id_carr_n":"CRS3035RES16000mN2176000E4256000","Groupe":3900,"Depcom":"2B184","I_pauv":0,"Id_car2010":"CRS3035RES200mN2189400E4269600","Ind":6,"Men":3.3,"Men_pauv":0.3,"Men_1ind":1,"Men_5ind":0,"Men_prop":2.3,"Men_fmp":0.3,"Ind_snv":140495.1,"Men_surf":230.7,"Men_coll":1.8,"Men_mais":1.5,"Log_av45":1.8,"Log_45_70":0,"Log_70_90":0.5,"Log_ap90":1,"Log_inc":0,"Log_soc":0,"Ind_0_3":0.2,"Ind_4_5":0,"Ind_6_10":0,"Ind_11_17":0.3,"Ind_18_24":0,"Ind_25_39":0.3,"Ind_40_54":1,"Ind_55_64":1.7,"Ind_65_79":1.7,"Ind_80p":0.8,"Ind_inc":0,"I_est_1km":1}},
{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[1221310.4579205937,6211017.205487403],[1221509.2789550738,6211034.965238771],[1221527.0213638875,6210834.922294508],[1221328.2001814116,6210817.162539224],[1221310.4579205937,6211017.205487403]]]},"properties":{"IdINSPIRE":"CRS3035RES200mN2189200E4269600","Id_carr1km":"CRS3035RES1000mN2189000E4269000","I_est_cr":1,"Id_carr_n":"CRS3035RES16000mN2176000E4256000","Groupe":3900,"Depcom":"2B184","I_pauv":0,"Id_car2010":"CRS3035RES200mN2189200E4269600","Ind":19,"Men":10.6,"Men_pauv":1.1,"Men_1ind":3.2,"Men_5ind":0,"Men_prop":7.4,"Men_fmp":1.1,"Ind_snv":444901.2,"Men_surf":730.4,"Men_coll":5.8,"Men_mais":4.8,"Log_av45":5.8,"Log_45_70":0,"Log_70_90":1.6,"Log_ap90":3.2,"Log_inc":0,"Log_soc":0,"Ind_0_3":0.5,"Ind_4_5":0,"Ind_6_10":0,"Ind_11_17":1,"Ind_18_24":0,"Ind_25_39":1.1,"Ind_40_54":3.2,"Ind_55_64":5.3,"Ind_65_79":5.3,"Ind_80p":2.6,"Ind_inc":0,"I_est_1km":1}}
]}
```

Have a good day

**Comment by mbloch** [comment]
In your above example, your input file is GeoJSON. You do have to use `from=` with GeoJSON, because the coordinate system is not included in the data file (according to the current specification).

**Comment by 2803media** [comment]
You can find the shp and dbf files just here (from the french institute of statistics):
https://www.insee.fr/fr/statistiques/fichier/4176293/Filosofi2015_carreaux_1000m_shp.zip

I try without the "from" and get this error:
`[proj] Error: Unable to project -- source coordinate system is unknown`
 
And works this the from command.

**Comment by mbloch** [comment]
Is it possible that your `.shp` file got separated from the `.prj` file? When I download the above Shapefiles (there are three in the the .zip archive) mapshaper is able to identify the CRS of all three:
```
mapshaper Filosofi2015_carreaux_1000m_metropole.shp  -info
mapshaper Filosofi2015_carreaux_1000m_reg04.shp -info
mapshaper Filosofi2015_carreaux_1000m_reg02.shp -info
```
The error message you got `[proj] Error: Unable to project -- source coordinate system is unknown` typically appears when the .prj file is missing.

**Comment by 2803media** [comment]
You're right! There is a prj file inside the zip, i'm dumb to not use it...

I just made a test and it's working when I have this file in my folder ;)

Thanks again I learnt a lot today !

I'm closing this issue
