### ISSUE TITLE
dissolve on "name" field impossible, "name" is interpreted as an option

### ISSUE THREAD

**Issue by matkoniecz** [mbloch/mapshaper#375]
```
mapshaper -i input.geojson -info \
  -dissolve "name" \
  -o output.geojson
```

ends with

`Error: Missing value for name option`

**Comment by matkoniecz** [comment]
I used

`mapshaper input.geojson -each 'mapshaper_name=name' -o intermediate.geojson`

```
mapshaper -i input.geojson -info \
  -dissolve "mapshaper_name" \
  -o output.geojson
```

**Comment by mbloch** [comment]
`-dissolve name` is a shortcut for `-dissolve fields=name`. If there's a conflict like this, use the second form.

**Comment by mbloch** [comment]
I suppose there's a clearer way to document default arguments... currently , the command line help says:
```
  <fields>      (optional) field or fields to dissolve on (comma-sep. list)
  fields=       equivalent to <fields>
```

This might be clearer:
```
  <fields>    shortcut for fields=
  fields=     (optional) field or fields to dissolve on (comma-sep. list)
```

**Comment by matkoniecz** [comment]
Proposed improvements is a good idea!

I was looking at https://github.com/mbloch/mapshaper/wiki/Command-Reference that seems to be missing `  fields=       equivalent to <fields>` help (that would be probably enough to discover how it can be fixed).

I now edited that wiki page, hopefully improving it - some other commands were already mentioning it explicitly

**Comment by mbloch** [comment]
Thanks for editing the wiki.

I haven't found a simple, backwards-compatible way to resolve the syntax ambiguity that caused this error. At least there's a workaround and a reasonably informative error message. I hope you don't mind if I close this issue.

**Comment by matkoniecz** [comment]
And in case of someone else stumbling on that they are likely to find this issue.
