### ISSUE TITLE
Missing CRS field in GeoJSON export

### ISSUE THREAD

**Issue by luisbausalopez** [mbloch/mapshaper#377]
When exporting a shapefile to the GeoJSON format, the resulting file is missing the coordinate reference system (CRS, aka Spatial Reference System or SRS).
The CRS is very important, it should always be present in any spatial file.

In the geoJSON file it should be stated like in the example below, where the WGS84 (aka EPSG:4326) is defined:
{"type": "FeatureCollection",
"name": "dataset_name",
**"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },**
"features": [...]}

**Comment by mbloch** [comment]
I agree that GeoJSON should support multiple CRSs, but that's not up to me to decide. The current "standard" states that GeoJSON is WGS84-only (see https://geojson.org/). Mapshaper will output GeoJSON with projected coordinates, if you tell it to, but it won't add a "crs" property.

Perhaps you can help persuade the standard committee to reintroduce "crs" to the next revision?

**Comment by luisbausalopez** [comment]
You are absolutely right, I was looking into the 2008 spec (https://geojson.org/geojson-spec.html#coordinate-reference-system-objects) instead of the 2015 spec (https://tools.ietf.org/html/rfc7946#section-4), where only the urn:ogc:def:crs:OGC::CRS84 (aka EPSG:4326) is accepted. Apologies.
