### ISSUE TITLE
retain additional point fields in simplify

### ISSUE THREAD

**Issue by bhogan-mitre** [mbloch/mapshaper#378]
Thank you for this fantastic tool!  I would like to suggest retaining additional point-level fields in the `simplify` function.  The [GeoJSON spec](https://tools.ietf.org/html/rfc7946#section-3.1.1) allows for fields beyond just longitude and latitude:

> A position is an array of numbers.  There MUST be two or more
   elements.  The first two elements are longitude and latitude, or
   easting and northing, precisely in that order and using decimal
   numbers.  Altitude or elevation MAY be included as an optional third
   element.

These fields are currently getting stripped by the `simplify` function as shown in the example below.   It would be most helpful to retain the full XYZM dimensions.

This relates to an [earlier thread](https://github.com/mbloch/mapshaper/issues/48) on preserving attribute data, although my interest is at the point level as well.

```
$ cat poly_feature.json 
{
 "type": "Feature",
 "properties": {},
 "geometry": {
   "type": "Polygon",
   "coordinates": [[
     [-70.603637, -33.399918, 1],
     [-70.614624, -33.395332, 2],
     [-70.639343, -33.392466, 3],
     [-70.659942, -33.394759, 4],
     [-70.683975, -33.404504, 5],
     [-70.697021, -33.419406, 6],
     [-70.701141, -33.434306, 7],
     [-70.700454, -33.446339, 8],
     [-70.694274, -33.458369, 9],
     [-70.682601, -33.465816, 10],
     [-70.668869, -33.472117, 11],
     [-70.646209, -33.473835, 12],
     [-70.624923, -33.472117, 13],
     [-70.609817, -33.468107, 14],
     [-70.595397, -33.458369, 15],
     [-70.587158, -33.442901, 16],
     [-70.587158, -33.426283, 17],
     [-70.590591, -33.414248, 18],
     [-70.594711, -33.406224, 19],
     [-70.603637, -33.399918, 20]
   ]]
 }
$ mapshaper -i poly_feature.json -simplify dp 20% -o format=geojson poly_feature_simple.json
[o] Wrote poly_feature_simple.json
$ cat poly_feature_simple.json 
{"type":"GeometryCollection", "geometries": [
{"type":"Polygon","coordinates":[[[-70.603637,-33.399918],[-70.609817,-33.468107],[-70.694274,-33.458369],[-70.683975,-33.404504],[-70.603637,-33.399918]]]}
```

**Comment by mbloch** [comment]
I want to support Z values, but there's a problem. When mapshaper imports polygons, it converts the original polygon data from a "spaghetti" data model to a topological data model. At the vertex level, this means that each pair of matching vertices from adjacent polygons is replaced with a single vertex. I don't see a straightforward way to retain the original Z data after this transformation.

If someone can suggest a workable solution to this problem, I'd be happy to implement it.

**Comment by mbloch** [comment]
I'm closing this issue, because it would be difficult to implement and has not been widely requested. Thanks for the suggestion :)
