### ISSUE TITLE
Unable to edit data or attribute values for polygons

### ISSUE THREAD

**Issue by shahbaz5990** [mbloch/mapshaper#382]
Earlier I remember when we select a polygon area we could edit the attribute values for fields created by us. For eg : after creating a field 'name', by just clicking any polygon area in the map, we could give values to it. Now the values are un editable. 
Would love to know how to do it again. Its a very simple and important functionality.
![mapshaper-edit-info](https://user-images.githubusercontent.com/27345937/69137741-5c437480-0ae3-11ea-99bd-86e7f9e47ac9.png)

**Comment by mbloch** [comment]
There's a fly-out menu next to the "i" button now that lets you select attribute editing. It's a bit hidden... perhaps you could suggest a better design?

![image](https://user-images.githubusercontent.com/1232222/69158585-acefa900-0ab4-11ea-89f4-dd8c49e6ad4e.png)
![image](https://user-images.githubusercontent.com/1232222/69158648-c09b0f80-0ab4-11ea-98dc-0bce981c47f6.png)

**Comment by mbloch** [comment]
I'm closing this issue because the functionality in question is still available... I welcome any future suggestions for improving the interface.
--mbloch
