### ISSUE TITLE
Possible to extract the latlng coordinates of each layer corner?

### ISSUE THREAD

**Issue by pistell** [mbloch/mapshaper#383]
I've been playing around with the command line tool and the website and I am having a bit of an issue. I uploaded a valid GeoJSON file of a grid zone. I can extract the bounding boxes of all the individual layers but I was wondering if it is possible to generate LatLng coordinates of the corners of each layer?

I ran this command which output the bboxes for each layer

`mapshaper 18T.geojson -split 100kmSQ_ID -o bbox-index`

Example output:

`{ "bbox": [-76.2720329, 44.2463709, -75, 45.1534771], "name": "18T-VQ" },`

This is nice but I would like to have LatLng coordinates of the corners of the polygon layers. None of these grid squares are rectangles so I need to use polylines when adding them to my map. 

It would be nice to have the coordinates for the most northwest/northeast/southwest/southeast points of each layer. 

Example image of what I am talking about:

<img width="1000" alt="Screen Shot 2019-11-25 at 1 32 32 AM" src="https://user-images.githubusercontent.com/7827805/69517825-d892e900-0f23-11ea-9324-cf1cd4dbd6cc.png">

**Comment by mbloch** [comment]
To be clear, you want to find the coordinates of the corner points of these non-rectangular grid cells?

Mapshaper doesn't have a built-in way to identify corner points.

The coordinates you need are going to be contained in the `coordinates` arrays of your GeoJSON polygon features, you might have to write your own script to extract them.

**Comment by pistell** [comment]
Yeah, I'm looking for the corner points of the non-rectangular grids. Not too sure how to get that since each of coordinates arrays have hundreds and hundreds of coordinates inside them :/

**Comment by mbloch** [comment]
If you simplify your grid layer using the 'Douglas-Peucker' method, you should be able to strip out all but the corner points.

**Comment by pistell** [comment]
I figured out how to do it. Had to include Turf.js but it works. Including my answer in case someone else is interested [answer](https://codepen.io/pistell/pen/QWWXpEV)

**Comment by mbloch** [comment]
I'm glad you found a solution!  Finding corners seems a bit niche to build into mapshaper, but if other people request it, I'll consider adding the functionality to mapshaper. Meanwhile, I'm going to close this issue.
