### ISSUE TITLE
Web Interface: Import numbers as strings from a CSV

### ISSUE THREAD

**Issue by Maserick74** [mbloch/mapshaper#385]
Hi there,

I'm new on mapshaper, but I couldn't find any help for my problem. I'm running the web interface. Is there a possiblity to import this CSV File with "plz" as string. Using the join command with the "string-fields" or "field-types" option doesn't work. What am I doing wrong?
`plz,ort,bundesland
01067,Dresden,Sachsen
`
At the end I would like to use the "join" command to join spreadsheet data with polygon map. Thank you for your help.

Best regards
Marco

**Comment by mbloch** [comment]
Hi, thanks for reporting this. I fixed the web UI bug that prevented string-fields from working, you can try importing again using `string-fields=plz`
--mbloch :)
