### ISSUE TITLE
Web Interface - Import CSV file fields as string instead of number

### ISSUE THREAD

**Issue by Maserick74** [mbloch/mapshaper#386]
Hello!

I'm new here, and maybe my question isn't good, but I couldn't find an answer in the web: I'm using mapshaper web interface to import this type of CSV (note the zero, a common problem in germany):

```
plz,ort,bundesland
01067,Dresden,Sachsen
```
By using the console, I haven't found any solution to convert the plz field as string, I tried the join command together with the `string-fields` and `field-types` option without success - any idea, what I'm doing wrong.

Many thanks!!
Marco

**Comment by mbloch** [comment]
There are two ways to solve this problem. 

Option one: prevent mapshaper from importing the `plz` field as a string by entering `string-fields=plz` in the command line options field in the import dialog, here:

![image](https://user-images.githubusercontent.com/1232222/69595207-ed778700-0fcc-11ea-9dfb-59f63c3dafac.png)


Option two: convert plz back to a string using a JavaScript expression and the `each` command in the console, like this:

![image](https://user-images.githubusercontent.com/1232222/69595259-15ff8100-0fcd-11ea-8aed-c83958046e79.png)

**Comment by Maserick74** [comment]
Hey, it works perfectly - I was shure, that I tried the `string-fields` command but, hey maybe it was to late. Nevertheless, thank you for your quick solution and thank you for delivering such a great piece of software!!
