### ISSUE TITLE
mapshaper: now available as a dockerized tool for CI / CD

### ISSUE THREAD

**Issue by christian-weiss** [mbloch/mapshaper#390]
Hi mbloch,

once again i want to thank you for this great tool.

To enable the crowd to easily use mapshaper in CI / CD pipelines i implemented an automated build and release of a docker image, which is available at: https://hub.docker.com/r/freifunkhamm/mapshaper. This docker image is automatically scanned for security vulnerabilities with trivy.

You are warm welcomed to join the release process. If your are interested in it i can grant you direct permissions at https://github.com/Freifunk-Hamm/docker_mapshaper. Just ping me.

Release cycle is very simple:
a) change Dockerfile (new version number)
b) commit and tag commit with version number
c) push
(we use sticky version numbers to have the same result on subsequent build re-runs of the same commit)

Feel free to link it in your github repo / project website.

Alternative:
If you want to create your own namespace/organisation at DockerHub feel free to grap my code and enable automation in your git repo.

**Comment by mbloch** [comment]
I don't use Docker myself, and I'd rather not publish Dockerfile updates myself, but I did add a link to your project to the mapshaper README, under a new section titled "User-contributed resources." Thanks for sharing this :)
