### ISSUE TITLE
Filter using max

### ISSUE THREAD

**Issue by aborruso** [mbloch/mapshaper#391]
Hi,
is there in mapshaper a way to something like

```
SELECT *, MAX(ST_Area(geometry)) area FROM layer GROUP BY fieldname
```

and select in example for every group of polygons with the same `fieldname` value, the polygon that has the max area value?

Something like a "group" option in mapshaper `-filter` command.

Thank you

**Comment by geodata4all** [comment]
hi, 
you can use this command.
mapshaper fc.shp -each "this.fieldname" -sort "this.area" descending -uniq "fieldname" -o out.shp
I am assuming you have single part polygons.

**Comment by aborruso** [comment]
@geodata4all great!

Thank you very much
