### ISSUE TITLE
Is it possible to use clean, to correct ogc ring self intersection error?

### ISSUE THREAD

**Issue by aborruso** [mbloch/mapshaper#393]
Hi,
if I run a geom validity check (as [this one](https://postgis.net/workshops/postgis-intro/validity.html) on PostGIS, or in spatialite, or in QGIS) on [this geojson](https://gist.github.com/aborruso/be896621ca8e255dd53b1867999e50cc/raw/541051e596a9f3fda67b385887155a03e65e24c0/input.geojson) file - EPSG:32632 - I have a "ring self intersection" error (x:1308926.3 and y:4476059.7).

![image](https://user-images.githubusercontent.com/30607/71325909-c640a680-24f3-11ea-9ad0-aba1b9ba9ef0.png)

Is there a way to check and clean it in mapshaper? Using `-clean` I'm able only to delete the small empty triangle. I would like to keep the small white triangle (this is an [example output](https://gist.github.com/aborruso/c5375b7e11f840d6af015bbc83b21516/raw/69f16e419eae393f0153b46b9f7f9ffcb6725fe8/input_validate.geojson) corrected using QGIS).

Thank you

**Comment by mbloch** [comment]
If you want to keep small shapes like this one, you need to use the `-clean gap-fill-area=0` option.
Also, you should update to the newly released v0.4.149. I  just re-read the OGC guidelines for simple shapes and changed -clean output to avoid the self-intersection error.

**Comment by aborruso** [comment]
@mbloch wow, this is a great thing.

Yesterday I had used `-clean gap-fill-area=0` and the small shapes were not canceled, but the ouptut file  was still invalid. That's why I made this request.

Once again thank you very much
