### ISSUE TITLE
Add google map satellite layer and polygon color

### ISSUE THREAD

**Issue by bassem94** [mbloch/mapshaper#397]
I would like to add a layer of google map (satellite) in background and color the polygons.
How to do it ?

**Comment by mbloch** [comment]
Mapshaper has some simple styling options. There's the `-style` command and the `-colorizer` command, which you can read about in the [Command Reference](https://github.com/mbloch/mapshaper/wiki/Command-Reference).

Mapshaper does not support Google Maps layers or any other background layers. You can try using http://geojson.io/ for that
