### ISSUE TITLE
convert .shp to topojson display issues in power bi

### ISSUE THREAD

**Issue by CatherineHansen** [mbloch/mapshaper#399]
I would love to understand why a polygon file (MN Parks - 87 polygons) displays this way in power bi after using mapshaper to convert .shp to topojson. The "shape map" visualization tool requires topojson and I was pointed to use the mapshaper tool. Display looks great in mapshaper, but when brought into power bi the polygons are all jumbled (as shown). Assuming its some sort of topology error I tried clean, dissolve, and dissolve2 to clear up any shape issues. suggestions welcomed.
![topojsonimportissues](https://user-images.githubusercontent.com/61255116/74884839-bdc0ec80-5339-11ea-8d7f-d1834599bae4.PNG)

**Comment by mbloch** [comment]
Interesting looking mess!  I've never used power bi, but i've seen this sort of issue in other situations, where the software expected lat-long coordinates and the data was projected. If your Shapefile is projected, can you try converting it to WGS84? You can do this in Mapshaper using  the `-proj wgs84` command. 

If this doesn't work, can you give me a copy of your Shapefile to look at? I can try getting it to work in power bi.

**Comment by CatherineHansen** [comment]
That TOTALLY worked. Thank you Matthew. The data was UTM15NAD83 so the –proj wgs84 fixed it in Power Bi.
So Happy.

Have a great weekend.

Catherine Hansen
GIS Support Specialist | GIS Section
Minnesota IT Services | Partnering with Department of Natural Resources
DNR Region 3 Headquarters
1200 Warner Road
Saint Paul, MN 55601
651-259-5734
Information Technology for Minnesota Government | mn.gov/mnit<http://mn.gov/mnit>
[Minnesota IT Services Logo]
[Facebook logo]<https://www.facebook.com/MN.ITServices>[LinkedIn logo]<https://www.linkedin.com/company/mn-it-services>[Twitter logo]<https://twitter.com/mnit_services>

“Learning is experience. Everything else is just information.” – Albert Einstein
