### ISSUE TITLE
Add crs data to output files when possible

### ISSUE THREAD

**Issue by mbloch** [mbloch/mapshaper#40]
GeoJSON (and TopoJSON) files that are not wgs84 should have a `crs` property.

When converting *JSON to Shapefile, a .prj file should be generated.

**Comment by Chaz6** [comment]
I support this as in the UK we use OSGB36.

**Comment by mbloch** [comment]
I just pushed commit 74151be5deac401c08eab197a3fe689402054d8e, which preserves the "crs" property of a GeoJSON or TopoJSON file when outputting to GeoJSON or TopoJSON.

To convert between Shapefile .prj files and GeoJSON crs would be much more involved. My current thinking is not to try to support this in mapshaper.

**Comment by Chaz6** [comment]
Thank you!

**Comment by mbloch** [comment]
Since v0.2.21, mapshaper has been preserving the (optional) "crs" property of GeoJSON and TopoJSON datasets. If the (still undocumented) `-proj` command is used, "crs" is set to null.

**Comment by BobHarper1** [comment]
According to the new Internet Engineering Task Force (IETF) new standardisation of the GeoJSON format, there is no requirement for the crs property in GeoJSON files as all formatting uses WGS84. The notes state that the inclusion of a defined crs previously led to some interoperability issues of file formats. 

It goes on:
> In general, GeoJSON processing software is not expected to have access to coordinate reference system databases or to have network access to coordinate reference system transformation parameters.  However, where all involved parties have a prior arrangement, alternative coordinate reference systems can be used without risk of data being misinterpreted.

See IETF, [RFC7946](https://tools.ietf.org/html/rfc7946#section-4)

Still, the inclusion of a crs is not harmful, if still apparently unnecessary.
