### ISSUE TITLE
Refactoring mapshaper

### ISSUE THREAD

**Issue by kwangure** [mbloch/mapshaper#403]
I've used mapshaper extensively for the past few weeks and still find it difficult to keep track of files and what calls what and where. Have you considered refactoring from your custom `/* requires package */` syntax and custom build system to a more standard `import package from "./package.js"` syntax?

Programmers unfamiliar with mapshaper's codebase also get zero editor support such as autocomplete and jump-to-file when they're trying to figure out what does what.

It would make it easier for others to read and contribute to mapshaper if you gradually adopted standard Javascript imports. Would you be interested in a PR?

**Comment by mbloch** [comment]
I would like to transition to JS modules and a standard build system (e.g. using rollup). There would be a lot of refactoring involved, though. I count 472 source code files and test files, which would each have to be manually edited. If you can put together a PR that demonstrates how the codebase could be gradually transitioned, that would be fantastic. At this point, I wouldn't want to you put a lot of time into this, at least until we understand the scope of the task, and agree on how mapshaper should be built in the future.

Cheers :)
mbloch

**Comment by kwangure** [comment]
Oh yes, it's plenty of refactoring. I've had one or two false starts in the time I've played around with the codebase.

The greatest challenge is that everything is so tightly coupled. In the future, I imagine ideally having a `mapshaper-core` module. Then `mapshaper-cli` and `mapshaper-gui` can be developed independently to depend on `mapshaper-core`.

Since most functions are currently tied to the `internal` global variable, I think the first step should be to decouple them and use ES `import`s instead to start (now supported in Node). Then bundling can be added to support older Node versions before merging into master. Further refactoring into clearer modules can be done later. 

Does this sound like a reasonable approach?

**Comment by mbloch** [comment]
About the `internal` object -- I started using `internal` as a way to export functions so they could be tested by mocha. The `internal` object will no longer be needed after the transition to ES6 modules is complete (except maybe to expose a few functions to the GUI that are not intended to be part of the main API).

My preferred way to transition is to use a two-step build process. First, use the old build tool ("catty") to create a bundle containing all of the source code files that are still required using the "@require" notation. Then, use Rollup to include the files that are being required using "import". This way, the project can be ported one file at a time. Meanwhile, mapshaper will continue to run all its tests and the GUI will continue to function.

I created a "rollup" branch to start this process: https://github.com/mbloch/mapshaper/commits/rollup

**Comment by kwangure** [comment]
I found that it's pretty easy to parse files into ASTs and manipulate them using sth like [recast](https://github.com/benjamn/recast). I created a small demo at [kwangure/mapshaper-recast](https://github.com/kwangure/mapshaper-recast) to explore how applicable it would be for mapshaper. It's a basic program that finds all the functions of the form: 
```javascript
internal.Func = function(param1, param2){ }
```
and transforms them into 
```javascript 
function Func(param1, param2){ }  // if only used locally
``` 
or 
```javascript
export function Func(param1, param2){ } // if used in other files.
```

Then imports like: 
```javascript

import { Func } from "../path/to/func.js";

...
Func(1, 2) // from internal.Func(1, 2)
...
``` 
in files that consume the exported function.

There are 2500+ functions of the above form in mapshaper. Manipulating ASTs saves you weeks/months of manual work and eradicates bugs (such as typos etc.) that might slip through if you're making 2500 changes. 

There are of course some things that are much easier to change by hand especially if they only appear in a few places. As you move forward you should explore where ASTs can help you take larger strides in the refactoring process. Feel free to use [kwangure/mapshaper-recast](https://github.com/kwangure/mapshaper-recast) as a starting point.

**Comment by mbloch** [comment]
Thank you for writing this script :)  It is useful in its current form, as a way to partially refactor source files by replacing the `internal` construct with module imports and exports.

 I've already refactored a bunch of files by hand. Going forward I'll try using the output of your script as a starting point, then manually add imports for a handful of global functions (like `stop()` and `message()` and namespaces like `utils` and `geom`.  This could be scripted, too, I suppose, but it's pretty simple to manually add a few import statements.

I also want to start thinking about next-step code reorganization. I'd like to make commands (like -i, -simplify and -o) more modular, in order to support plugins. Currently, commands are hard-coded into `mapshaper-options.js` and `mapshaper-run-command.js`.

**Comment by mbloch** [comment]
I've mostly finished porting the core mapshaper module to ES6 modules (I've been working on the "rollup" branch). This includes everything but the GUI.

Within the non-gui part of the app, I completely replaced "internal" with module imports. I'm still adding "internal" to the module, though (see mapshaper-internal.js and mapshaper.js), to maintain compatibility with the existing test suite and with the GUI.

You could say that the GUI is tightly coupled to the core module, because it contains almost 200 calls to functions attached to the "internal" namespace. I don't see a good way around this, although I'm open to suggestions.

There are still plenty of improvements that could be made to the core part of mapshaper, in terms of improving code style and organization -- I welcome any suggestions.

Next I think I'll turn to the web UI (everything inside the src/gui/ directory), and port that to JavaScript modules + Rollup bundling.

P.S. thanks again for your refactoring script  @kwangure -- it saved me a lot of time.

**Comment by kwangure** [comment]
That was fast! I'm impressed...and very pleased with what I see. I'm glad you found the script useful.

In regards to the GUI, I had to get familiar with the internals of mapshaper because I needed to output SVGs in JSON form before processing into HTML (i.e SVG objects like -> `{ tag: "path", properties: { d : "" }`) which I pass into a Svelte app that needs to do stuff with each path like event handling etc. 

My point is, a portion of mapshaper users will likely have niche use cases that might be challenging to do with a largely CLI-based interface. I recommend exposing more functions (particularly the exporters) to the public API. 

I think you should be able to build mapshaper.org's web UI as a blind client —only using the public API. This might help you determine which functions other developers might need easier access to. What do you think?

As for performance + style improvements, I think mapshaper would benefit greatly from Typescript.  Espectially for large files, it would probably eliminate a few hundred calls to util functions such as `isObject` and `isString` by moving that work to compile time.

I admittedly haven't written too much Typescript, but I always immensely appreciate editor hints and auto-completion while using typed libraries. Recast is not too well documented, but I found it easy to rewrite mapshaper's ASTs with help from its Typescript hints.

**Comment by mbloch** [comment]
I finished converting the `gui/` files to modules today.  Switching to JS modules is something I've wanted to do for a while... thank you  for giving me the nudge I needed to finally get it done, @kwangure.

I appreciate your other suggestions, too. But I feel like maintaining the various useful bits and pieces of mapshaper as developer APIs would take me away from my main goal for this project, which is to give me and my colleagues a better workflow for editing map data. In other words, I'm treating mapshaper first and foremost as an end-user application. So my inclination is to keep the Node API as simple and focused as possible, and to treat the low level geoprocessing functions as internals.

Converting this 30,000 line program to TypeScript seems like a pretty bit time commitment, for a relatively modest payoff. I think TS would be a good option if I were starting out from scratch.  

Cheers,
mbloch

**Comment by Dave592309** [comment]
Hi Mbloch/Mapshaper,

Is there an API for this service? If so where would I find it in the docs?
Thanks

**Comment by kwangure** [comment]
CC @Dave592309. See the [wiki](https://github.com/mbloch/mapshaper/wiki) page for docs on how to use mapshaper.

**Comment by mbloch** [comment]
@Dave592309   I just updated the wiki page about mapshaper's Node API:
https://github.com/mbloch/mapshaper/wiki/Using-mapshaper-programmatically

**Comment by Dave592309** [comment]
Awesome thanks so much Matthew! Appreciate it.

Dave
