### ISSUE TITLE
how to simplify data in node api

### ISSUE THREAD

**Issue by chenguang1994** [mbloch/mapshaper#404]
const input = {'input.csv': 'x,y\n75.345678,38.123456\n75.356528,38.123456\n75.367378,38.123456\n75.375678,38.123456\n75.385678,38.123456\n75.395678,38.123456\n75.405678,38.123456\n75.415678,38.123456\n75.425678,38.123456\n75.435678,38.123456'}

  mapshaper.applyCommands(`-i input.csv -simplify  10% -points  -o output.geojson`, input, (err, output) => {
    let res =  output['output.geojson'].toString();
    console.log(res)
  });
this is my code ,input 10 points , the result is also 10 points

**Comment by mbloch** [comment]
Mapshaper imports CSV files as data tables, without geometry. You need to explicitly convert the data to geometric points, using the `-points` command. Then, you can convert the points to a line, using the `-lines` command. Only then can you use the `-simplify` command.

For example: `-i input.csv -points -lines -simplify 10% -o output.geojson`.

If you want to output the vertices of the simplified line, you need you use `-points vertices`, like this:

`-i input.csv -points -lines -simplify 10% -points vertices -o output.geojson`.

One useful trick is to test your commands in the web UI console before running them in the Node API -- that way you can visually confirm that each step is working the way you expect.
