### ISSUE TITLE
PHP and/or Drupal

### ISSUE THREAD

**Issue by dchaffin** [mbloch/mapshaper#405]
Any possibility (or examples) of using this inside a Drupal module? I want to pull shapefile data from a database and create json files with mapshaper to "dissolve" and "simplify" them.

I know this isn't an "issue", per se ... but not sure where else to ask this.

Thanks!

**Comment by mbloch** [comment]
I'm not a PHP programmer, but... there must be a way to run shell commands (`shell` and `shell_exec`?). You could try running the `mapshaper` command line program that way.

**Comment by dchaffin** [comment]
@mbloch - Thanks! I have seen a class that I think does just that. I should have probably mentioned ... the server I'm on doesn't support node.js. Is there a way to run mapshaper without node.js? I'm not yet that familiar with node.js myself, so sorry for such an uninformed question.

**Comment by mbloch** [comment]
The only way to run mapshaper that doesn't use Node is via the web interface (mapshaper.org). It doesn't seem like the web UI would be useful for your purpose.
