### ISSUE TITLE
simplify issue - not retaining all the coordinates

### ISSUE THREAD

**Issue by sowmya-alugubelli** [mbloch/mapshaper#406]
For few geojson files, I have been having some issues and below is one issue.

Input file - [https://github.com/sowmya-alugubelli/geojson/blob/master/22.geojson](url)

Output file - [https://github.com/sowmya-alugubelli/geojson/blob/master/out.geojson](url)

Command used - `mapshaper 22.geojson -simplify keep-shapes dp 99% -o format=geojson out.geojson`

Issue - after simplifying, getting a very small polygon instead of the main polygon

**Comment by mbloch** [comment]
Thanks for reporting this.. I will investigate and get back on this in a day or two.

**Comment by mbloch** [comment]
I see the issue... the GeoJSON file is improperly formed. The largest polygon is encoded as a "hole" belonging to one of the small peripheral islands. If you drop 22.geojson into the web gui and run 'clean' in the console, you'll see that the large island disappears, because it is being interpreted as a hole without a containing ring around it. You can repair the geometry by running the commands `-lines -polygons`. `-lines` converts the polygons to rings, and `-polygons` converts the lines back to valid polygons.

**Comment by sowmya-alugubelli** [comment]
Thank you so much! it worked!!

This file is being generated by bing maps, but for now I'm good with this. Thanks again.

**Comment by sowmya-alugubelli** [comment]
@mbloch I just realized that it converted 'FeatureCollection' to 'GeometryCollection' and removed all properties.

I tried the below command to retain the fields, but i think when its converting to lines and back to polygons, its removing the polygons.

`mapshaper 22.geojson  -lines -polygons -filter-fields bounds,centroid,countryCode,id,name -simplify dp 6% -o format=geojson out.json`

Is there anyway we can keep the same name "FeatureCollection" and "features" along with properties?

**Comment by mbloch** [comment]
It's true, the attribute data gets lost as soon as you run `-lines`.

I can update mapshaper to repair this kind of file, but I might not have time for a few days.

Meanwhile, you said that you're getting them from bing maps... can you give me some instructions so I can generate these GeoJSON files myself? I'd like to investigate why they are getting made this way. 

fwiw, the clause in the GeoJSON specification that is being violated is this:
" For Polygons with more than one of these rings, the first MUST be
      the exterior ring, and any others MUST be interior rings.  The
      exterior ring bounds the surface, and the interior rings (if
      present) bound holes within the surface."

**Comment by mbloch** [comment]
v0.5.7 adds the `-clean rewind` option, which will repair MultiPolygons with geometry errors  like 22.geojson.

**Comment by sowmya-alugubelli** [comment]
Thank you, its working now and retaining the exact format.
