### ISSUE TITLE
mapshaper cannot find geojson file (username with spaces?)

### ISSUE THREAD

**Issue by grcolli** [mbloch/mapshaper#409]
> shape_municipios_simp <- rmapshaper::ms_simplify(shape_municipios, sys = T)
Error: [o] Command expects a single value. Received: C:\Users\Guarino R. Colli\AppData\Local\Temp\RtmpScK7dh\file41301ed349d8.geojson
Run mapshaper -h to view help
Error: Cannot open "C:\Users\Guarino R. Colli\AppData\Local\Temp\RtmpScK7dh\file41301ed349d8.geojson"; The file doesn't seem to exist.

From other forums, the issue is related to a username (and directory names) with spaces. Is there a way around this, other than creating a new user? Thanks, Guarino.

> Sys.getenv()
ALLUSERSPROFILE                          C:\ProgramData
APPDATA                                  C:\Users\Guarino R. Colli\AppData\Roaming
ChocolateyInstall                        C:\ProgramData\chocolatey
ChocolateyLastPathUpdate                 132333295157412892
CLICOLOR_FORCE                           1
CLIENTNAME                               leptophis
CommonProgramFiles                       C:\Program Files\Common Files
CommonProgramFiles(x86)                  C:\Program Files (x86)\Common Files
CommonProgramW6432                       C:\Program Files\Common Files
COMPUTERNAME                             TYRANNOSAURUS
ComSpec                                  C:\WINDOWS\system32\cmd.exe
DISPLAY                                  :0
DriverData                               C:\Windows\System32\Drivers\DriverData
GDAL_DATA                                C:/Users/Guarino R. Colli/Documents/R/win-library/4.0/sf/gdal
GFORTRAN_STDERR_UNIT                     -1
GFORTRAN_STDOUT_UNIT                     -1
HOME                                     C:\Users\Guarino R. Colli\Documents
HOMEDRIVE                                C:
HOMEPATH                                 \Users\Guarino R. Colli
LOCALAPPDATA                             C:\Users\Guarino R. Colli\AppData\Local
LOGONSERVER                              \\TYRANNOSAURUS
MPLENGINE                                tkAgg
MSYS2_ENV_CONV_EXCL                      R_ARCH
NUMBER_OF_PROCESSORS                     44
OneDrive                                 C:\Users\Guarino R. Colli\OneDrive - unb.br
OneDriveCommercial                       C:\Users\Guarino R. Colli\OneDrive - unb.br
OS                                       Windows_NT
tools40\usr\bin;C:\Program               C:
                                         Files\R\R-4.0.0\bin\x64;C:\Python38\Scripts\;C:\Python38\;C:\Program Files
                                         (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS
                                         Client\;C:\Program Files\Intel\iCLS
                                         Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program
                                         Files\Dell\Dell Data Protection\Drivers\TSS\bin\;C:\Program Files
                                         (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
                                         Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
                                         (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program
                                         Files\Intel\Intel(R) Management Engine
                                         Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\MiKTeX
                                         2.9\miktex\bin\x64\;C:\Program
                                         Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\Guarino R.
                                         Colli\AppData\Local\Microsoft\WindowsApps;C:\Users\Guarino R.
                                         Colli\AppData\Local\GitHubDesktop\bin;C:\Users\Guarino R.
                                         Colli\AppData\Local\Microsoft\WindowsApps;C:\Users\Guarino R.
                                         Colli\AppData\Roaming\npm
PATHEXT                                  .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
PROCESSOR_ARCHITECTURE                   AMD64
PROCESSOR_IDENTIFIER                     Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
PROCESSOR_LEVEL                          6
PROCESSOR_REVISION                       4f01
ProgramData                              C:\ProgramData
ProgramFiles                             C:\Program Files
ProgramFiles(x86)                        C:\Program Files (x86)
ProgramW6432                             C:\Program Files
PROJ_LIB                                 C:/Users/Guarino R. Colli/Documents/R/win-library/4.0/sf/proj
PSModulePath                             C:\Program
                                         Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC                                   C:\Users\Public
QT_D3DCREATE_MULTITHREADED               1
R_ARCH                                   /x64
R_COMPILED_BY                            gcc 8.3.0
R_DOC_DIR                                C:/PROGRA~1/R/R-4.0.0/doc
R_HOME                                   C:/PROGRA~1/R/R-4.0.0
R_LIBS_USER                              C:/Users/Guarino R. Colli/Documents/R/win-library/4.0
R_USER                                   C:/Users/Guarino R. Colli/Documents
RMARKDOWN_MATHJAX_PATH                   C:/Program Files/RStudio/resources/mathjax-26
RS_LOCAL_PEER                            \\.\pipe\10135-rsession
RS_RPOSTBACK_PATH                        C:/Program Files/RStudio/bin/rpostback
RS_SHARED_SECRET                         63341846741
RSTUDIO                                  1
RSTUDIO_CONSOLE_COLOR                    256
RSTUDIO_CONSOLE_WIDTH                    80
RSTUDIO_MSYS_SSH                         C:/Program Files/RStudio/bin/msys-ssh-1000-18
RSTUDIO_PANDOC                           C:/Program Files/RStudio/bin/pandoc
RSTUDIO_SESSION_PORT                     10135
RSTUDIO_USER_IDENTITY                    Guarino R. Colli
RSTUDIO_WINUTILS                         C:/Program Files/RStudio/bin/winutils
RTOOLS40_HOME                            C:\rtools40
SESSIONNAME                              RDP-Tcp#4
SystemDrive                              C:
SystemRoot                               C:\WINDOWS
TEMP                                     C:\Users\Guarino R. Colli\AppData\Local\Temp
TERM                                     xterm-256color
TMP                                      C:\Users\Guarino R. Colli\AppData\Local\Temp
TZDIR                                    C:/PROGRA~1/R/R-4.0.0/share/zoneinfo
USERDOMAIN                               TYRANNOSAURUS
USERDOMAIN_ROAMINGPROFILE                TYRANNOSAURUS
USERNAME                                 Guarino R. Colli
USERPROFILE                              C:\Users\Guarino R. Colli
windir                                   C:\WINDOWS

**Comment by mbloch** [comment]
Can you try enclosing the file name in quotes? See if that works...

**Comment by grcolli** [comment]
This is the original line (in RStudio):

shape_municipios_simp <- rmapshaper::ms_simplify(shape_municipios, sys = T)

Are you suggesting that I use "shape_municipios" instead?

**Comment by mbloch** [comment]
I see.. you're using mapshaper in R... I'm not an R user, and I'm not sure how rmapshaper works, so i might not be much help... I would like you to put the quotes around the file path that is assigned to the variable shape_municipios. Can you do something like this in R?
```r
shape_municipios <- "\"C:\Users\Guarino R. Colli\AppData\Local\Temp\RtmpScK7dh\file41301ed349d8.geojson\""
```

**Comment by mbloch** [comment]
If my above suggestion doesn't work, I suggest you file an issue in the rmapshaper repo, here: https://github.com/ateucher/rmapshaper

**Comment by grcolli** [comment]
> I see.. you're using mapshaper in R... I'm not an R user, and I'm not sure how rmapshaper works, so i might not be much help... I would like you to put the quotes around the file path that is assigned to the variable shape_municipios. Can you do something like this in R?
> 
> ```r
> shape_municipios <- "\"C:\Users\Guarino R. Colli\AppData\Local\Temp\RtmpScK7dh\file41301ed349d8.geojson\""
> ```

"shape_municipios" is not a file, but a spatial object created within the R session. Apparently rmapshaper creates a .geojson file to be processed by mapshaper, but the latter cannot find it due to spaces in the user directory's names. Thus, I suspect the issue has more to do with mapshaper than with rmapshaper.

But thanks a lot for your attention. Will post the issue in the rmapshaper repo.

**Comment by mbloch** [comment]
I see... it seems to me that rmapshaper needs to detect the presence of spaces and wrap the name in quotes.  Mapshaper requires this.

**Comment by grcolli** [comment]
It's curious that the exactly same code works in macOS. Yet, macOS collapses user names with spaces in the directory structure.

**Comment by grcolli** [comment]
Let's see what the rmapshaper guys will say. Will keep you posted. Thanks!

**Comment by ateucher** [comment]
Hi, I’m the rmapshaper maintainer - this is definitely an rmapshaper issue, I think you can close this issue. 

Cheers,
Andy

**Comment by grcolli** [comment]
OK. Closed. Thanks!
