### ISSUE TITLE
Question - How to line up output SVGs

### ISSUE THREAD

**Issue by ajruckman** [mbloch/mapshaper#410]
We are downloading 4 separate GeoJSON files from Overpass Turbo and we would like to create 4 separate SVGs from them. We would like each of them to line up perfectly so we can use them as masks in other software.

We figured out that the roads and rivers in the GeoJSON files kindof jut out from the edges of the area we want, so the data in the GeoJSON files isn't cropped like we need it to be. We learned that we could use `ogr2ogr` to crop them:
```
ogr2ogr -spat -85.1363 34.9548 -84.9167 35.1385 -f "GeoJSON" buildings_clipped.geojson buildings.geojson -clipsrc spat_extent
ogr2ogr -spat -85.1363 34.9548 -84.9167 35.1385 -f "GeoJSON" highways_clipped.geojson  highways.geojson  -clipsrc spat_extent
ogr2ogr -spat -85.1363 34.9548 -84.9167 35.1385 -f "GeoJSON" water_clipped.geojson     water.geojson     -clipsrc spat_extent
ogr2ogr -spat -85.1363 34.9548 -84.9167 35.1385 -f "GeoJSON" waterways_clipped.geojson waterways.geojson -clipsrc spat_extent
```
As far as we can tell this does exactly what we wanted. (You can get the GeoJSON files here if you want to see: [https://we.tl/t-2Ws5x8Dq3n](https://we.tl/t-2Ws5x8Dq3n)) 

Next we went on to trying to get the SVGs with mapshaper. We learned that if we didn't set the projection, the buildings were skewed, so we added `-proj from=wgs84 EPSG:32616`. Here is the command we have for mapshaper so far:
```
mapshaper-i *.geojson -proj from=wgs84 EPSG:32616 -o width=20000
```
And we also tried using the `-clip` option in mapshaper:
```
mapshaper -i *.geojson -clip bbox=-85.1363,34.9548,-84.9167,35.1385 -o format=svg width=20000
```

Unfortunately these SVGs don't line up and we aren't sure why. Are we doing something wrong or is there a way we could get them aligned?

**Comment by mbloch** [comment]
Currently there's not a good way to output separate SVGs that align. Mapshaper scales the content of SVG files to fill the entire SVG artboard area, and since the content bounds of your layers are not the same, they each get scaled differently.

It shouldn't be hard to come up with an option for generating outputting SVGs that align. 

Until that exists, though, the best you can do would be to create an SVG file containing all four layers, like this:
```
mkdir -p out
mapshaper *.geojson combine-files \
	-clip bbox=-85.1363,34.9548,-84.9167,35.1385 \
	-proj from=wgs84 EPSG:32616 \
	-o out/layers.svg width=20000
```

**Comment by ajruckman** [comment]
Thank you! That could work too but we were hoping to have each GeoJSON set be a different color. We were just going to change them in Inkscape but maybe there is a way to do it with mapshaper? I have tried a few things with the `-colorizer` command and I know I can change the fill/stroke for ALL layers with the `-style` command, but I don't know if I can change them per file.

**Comment by mbloch** [comment]
Per-layer colors are easy. the '-target' commands selects one or more layers as the target of the following command(s).

```
mkdir -p out
mapshaper *.geojson combine-files \
-clip bbox=-85.1363,34.9548,-84.9167,35.1385 \
-proj from=wgs84 EPSG:32616 \
-target water \
-style fill=blue \
-target waterways \
-style stroke=blue \
-target buildings \
-style fill=black \
-target highways \
-style stroke=orange \
-target '*' \
-o out/layers.svg width=20000
```

**Comment by ajruckman** [comment]
That is perfect! This is a really awesome tool. Thanks!
