### ISSUE TITLE
Coloring Building Footprints

### ISSUE THREAD

**Issue by nonoumasy** [mbloch/mapshaper#411]
Just a question. Whats the easiest way to color building footprints I extracted from overpass? can I randomly color fill the polygons with a list of 3 colors for example?
![7937ccd8c994ce8b19c09548d9c44dcd](https://user-images.githubusercontent.com/6312676/81644507-b9f2b280-93dc-11ea-86ea-d5d3708cda50.jpg)

**Comment by mbloch** [comment]
Here are two ways of assigning three colors randomly (show in the web ui)
![image](https://user-images.githubusercontent.com/1232222/81675251-86377d00-941c-11ea-8fa6-9eb6c41fe09d.png)

**Comment by nonoumasy** [comment]
Thank you very much. I was able to do my experiments.
<img width="767" alt="Screen Shot 2020-05-12 at 1 15 39 PM" src="https://user-images.githubusercontent.com/6312676/81741120-e47f5280-9452-11ea-914f-14d093f088d0.png">

**Comment by mbloch** [comment]
love your experiments :)
