### ISSUE TITLE
How to display Shapefiles (.shp, .shx, .dbf) in the map ?

### ISSUE THREAD

**Issue by Kayumiy** [mbloch/mapshaper#412]
I have 3 data files which are:
* .shp
* .shx
* .dbf

I need to display these files in the map. 
1. Is it possible tp render these three files in the map by using **mapshaper**?
2. Is **mapshaper** web application or can be published as a desktop application because I have to build desktop application not web.

Thank You

**Comment by mbloch** [comment]
I don't think Mapshaper is a good option for rendering Shapefiles in a desktop application. First of all, the Mapshaper GUI is a web application, so to use it in a desktop app, you'd have to include a web environment in your app, e.g. by using Electron. Secondly, the rendering functionality is pretty tightly integrated with Mapshaper's editing functionality, so it's not a great platform for general-purpose map rendering. Some people have tried to use Mapshaper for map rendering, but I believe they eventually gave up.
