### ISSUE TITLE
.dbf file (read and load)

### ISSUE THREAD

**Issue by Kayumiy** [mbloch/mapshaper#413]
![image](https://user-images.githubusercontent.com/22438366/82006952-ef7cf180-96a3-11ea-98b8-0d90d0e4a51f.png)

On the right side of the picture is your solution which can shows red points in the map.
My code does not show red points because my code cannot read .dbf file.

This is my .dbf file should be read and load in the map.

![image](https://user-images.githubusercontent.com/22438366/82007096-57333c80-96a4-11ea-8c7b-1a87600aaa33.png)

Can you explain it please how your solution read and display these red points?

**Comment by mbloch** [comment]
The points indicated places where two lines cross each other. Mapshaper calculates these locations from the geometry, they are not loaded from a file.
