### ISSUE TITLE
Problem joining 2 layers

### ISSUE THREAD

**Issue by dkillpack** [mbloch/mapshaper#414]
I'm using the web interface and attempting to join 2 layers similar to the example provided in the -join section of the command reference.

"Join a point layer to a polygon layer (spatial join), using the calc= option to handle many-to-one matches. - mapshaper states.shp -join points.shp calc='median_score = median(SCORE), mean_score = average(SCORE), join_count = count()' -o out.shp"

I was able to generate a grid to use as a target but the primary goal is to generate an average of the points falling within the grid squares and all my attempts end up with an error.  I'm sure it's an issue with my syntax but it could also be that this isn't possible using the web interface.  Any guidance would be greatly appreciated.

<img width="1078" alt="Join2LayersExample" src="https://user-images.githubusercontent.com/6939541/82466136-a521b900-9a85-11ea-9553-6e3e7ee9ba0e.PNG">

[Join2Layers.zip](https://github.com/mbloch/mapshaper/files/4657820/Join2Layers.zip)

**Comment by mbloch** [comment]
Your first command almost worked. The web console has a few differences from the command line program. Layers are referenced by name, not filename. So with the grid layer selected, the following command works:
![image](https://user-images.githubusercontent.com/1232222/82475428-7cf08500-9a9a-11ea-9aec-6f8560adad23.png)
