### ISSUE TITLE
problem with join for multiple keys

### ISSUE THREAD

**Issue by manishlmn** [mbloch/mapshaper#416]
Im totally agreed this is wonderful tool and free of cost....

Recently im working on one map file which does not have unique identifier , we need to join multiple multiple columns to get the unique records in geojson file.

Problem: i would like to join my geojson file with csv, here my joining keys are more than two. How to achieve this. it seems in this tool it will accept only one key from both files.

Could you please help me to achieve this?

**Comment by mbloch** [comment]
To join two datasets using multiple key fields, you would have to create unique key fields containing  in both tables, by concatenating the values of your existing, non-unique keys. The `-each` command is useful here. So for example, if you have a 	STATE  field and a CITY field, you could create a field named KEY by concatenating STATE and CITY, like this:
```
-each 'KEY = STATE + "-" + CITY'
```
Then you could use the KEY field for joining.

**Comment by manishlmn** [comment]
Thank you so much for your kind reply.

I didn't think like this. Yes we can achieve what I asked you. I'm closing this request.
