### ISSUE TITLE
Wiki edit request: TopoJSON quantization on output

### ISSUE THREAD

**Issue by jsonkao** [mbloch/mapshaper#417]
Hi Matt, hope you're well and safe. Just wanted to request a change in the Command Reference under the options for [`-o (output)`](https://github.com/mbloch/mapshaper/wiki/Command-Reference#-o-output).

Currently, the `quantization` option is documented as follows:
> `quantization=` (TopoJSON) Specify quantization as the maximum number of differentiable points along either dimension. Equivalent to the `--q1/--post-quantization` option of Mike Bostock's topojson program. By default, mapshaper applies quantization equivalent to 0.02 of the average segment length.

Since [TopoJSON v2](https://github.com/topojson/topojson/releases/tag/v2.0.0), quantization has been extracted into the [topojson-client](https://github.com/topojson/topojson-client) module. And I think that the `--q1/--post-quantization` option is now equivalent to the quantization number `n` in [topoquantize](https://github.com/topojson/topojson-client#topoquantize) (though I'm not 100% sure).

Thanks so much for your work.

**Comment by mbloch** [comment]
Thanks for this request, Jason... I just updated the wiki.
