### ISSUE TITLE
encoding is problem

### ISSUE THREAD

**Issue by zhishiqu** [mbloch/mapshaper#421]
i set optins [encoding=gbk] content is ok, but property  name is wrong

![image](https://user-images.githubusercontent.com/22735110/87003204-ca14eb80-c1ed-11ea-9114-c8549839b406.png)

**Comment by mbloch** [comment]
Mapshaper assumes that Shapefile field names use ASCII text. In your Shapefile, it appears that the field names are encoded in GBK, like the data records. If you send me the Shapefile that you screenshotted above (or a similar one), I will try to fix this problem.

**Comment by zhishiqu** [comment]
> Mapshaper assumes that Shapefile field names use ASCII text. In your Shapefile, it appears that the field names are encoded in GBK, like the data records. If you send me the Shapefile that you screenshotted above (or a similar one), I will try to fix this problem.

ok，I have sent you an email. Please check it

**Comment by zhishiqu** [comment]
> Mapshaper assumes that Shapefile field names use ASCII text. In your Shapefile, it appears that the field names are encoded in GBK, like the data records. If you send me the Shapefile that you screenshotted above (or a similar one), I will try to fix this problem.

hello, Can you solve the problem of property name confusion? thanks

**Comment by mbloch** [comment]
@zhishiqu can you explain what you mean by "property name confusion"? Do you mean the problem where your Chinese language field names are not correctly imported?

I have already finished adding support for importing non-ASCII (for example, Chinese) field names. Now I am working on exporting non-ASCII field names. This is a bit tricker, because long names have to be shortened. I expect to finish later today.

**Comment by zhishiqu** [comment]
> @zhishiqu can you explain what you mean by "property name confusion"? Do you mean the problem where your Chinese language field names are not correctly imported?
> 
> I have already finished adding support for importing non-ASCII (for example, Chinese) field names. Now I am working on exporting non-ASCII field names. This is a bit trickier, because long names have to be shortened. I expect to finish later today.
> 
> ![image](https://user-images.githubusercontent.com/1232222/87253714-64be3600-c44b-11ea-839f-2cbacbd6e2c0.png)

good，it is very usefully than your write the js libary . 为您点个赞 👍

**Comment by mbloch** [comment]
I just released a new version (0.5.11) with preliminary support for reading and writing encoded field names. In the future, I would like to add automatic encoding detection. But for now, you will usually need to manually set the `encoding` option in the `-i` and `-o` command.

**Comment by zhishiqu** [comment]
> I just released a new version (0.5.11) with preliminary support for reading and writing encoded field names. In the future, I would like to add automatic encoding detection. But for now, you will usually need to manually set the `encoding` option in the `-i` and `-o` command.

ok，thanks。

**Comment by mbloch** [comment]
you're welcome, and thanks for using mapshaper :)
