### ISSUE TITLE
Chrome rejecting exported geojson files

### ISSUE THREAD

**Issue by mtdukes** [mbloch/mapshaper#424]
Not sure if this is happening in a widespread way or not, but I'm getting the following error message in Chrome (Version 83.0.4103.116 (Official Build) (64-bit)) when I try to export and download a Geojson file:

> FILENAME is dangerous, so Chrome has blocked it.

The error includes a link to the [Google Help Question ](https://support.google.com/chrome/answer/6261569?visit_id=637305986556450627-4031608608&p=ib_download_blocked&hl=en&rd=1)on the issue. To download the file, users have to disable safe browsing.

This seems to be a new issue, since I use mapshaper every day and first received it today.

**Comment by mbloch** [comment]
Hi @mtdukes, thanks for reporting this!

I wasn't able to reproduce this problem myself, using the same Chrome version as you.

I'd like to know if it's particular to the one dataset, or if it is happening all the time now for you.

Either way, I'd like to understand what is setting Chrome off.

Please share whatever additional information that you can about this incident.

Cheers,
mbloch

**Comment by mtdukes** [comment]
@mbloch Thanks for the quick response. It's definitely strange. The original file uploaded to mapshaper is here:
https://github.com/mtdukes/nc-covid-by-zip/blob/master/time_series_data/full_geojson/nc_zip0717.geojson

The exported file (the one Chrome is blocking) is here:
https://github.com/mtdukes/nc-covid-by-zip/blob/master/time_series_data/reduced_geojson/nc_zip0717.json

If there's any other information I can provide that would be helpful, please let me know.

**Comment by mtdukes** [comment]
@mbloch FWIW, I'm no longer getting this error anymore (I've been downloading a similar file without issue several days in a row). So this is probably an issue you can close.
