### ISSUE TITLE
Improve (or document) UTM support

### ISSUE THREAD

**Issue by wdmartin** [mbloch/mapshaper#431]
I recently had occasion to re-project a GeoJSON file containing boundaries for the fylker (counties, or districts) of Norway.  GeoNorge (the Norwegian Mapping Authority) supplies these in the projection "EUREF89 UTM sone 33, 2d", i.e. UTM zone 33.  UTM divides the world up into 6-degree segments called zones; but although the `-proj` command supports UTM, there doesn't seem to be a mechanism for specifying which zone the data belongs in.  As a result, it picks a zone by default (looks like Zone 30, or maybe Zone 31) and winds up mis-translating the coordinates of they happen to be from any other zone.  The data wind up centered around the prime meridian.

I would attach the GeoJSON, to save you the trouble, as it is an open dataset, but it's rather large for a Github attachment (26 MB).  Steps to obtain the data and reproduce the issue:

1. Go to [Norske fylker og kommuner illustrasjonsdata 2020 (klippet etter kyst)](https://kartkatalog.geonorge.no/metadata/norske-fylker-og-kommuner-illustrasjonsdata-2020-klippet-etter-kyst/7408853f-eb7d-48dd-bb6c-80c7e80f7392)
2. Click "Last ned" to add it to your cart
3. Click the download/cloud icon in the top right
4. Click "Åpne nedlastinger"
5. For the field "Geografisk område" select "Hele landet" (the only option)
6. For "Velg grukergruppe" pick "Fylkeskommune"
7. For "Velg formål" pick "Teknologi og innovasjon"
8. Click the dusty blue "Last ned" button.
9. Click the dusty blue download icon at the right of the blue box, which lacks a textual label.
10. Unzip the resulting "Basisdata_0000_Norge_25833_NorskeFylkerKommunerIllustrasjonsdata2020_GeoJSON.zip" file
11. Open one of the two GeoJSON files inside it in Mapshaper. Your options are "Fylker" (counties) or Kommuner (municipalities)
12. Open the console
13. Enter `-proj from=utm wgs84` and press enter

The data will be re-projected, but if you simplify the result and export it to a new file and open it in something like [geojson.io](https://geojson.io), it will be offset to the west of its correct location, leaving Norway floating over the sea.

Proj.4 apparently supports this with a command like `+proj=utm +zone=33 +datum=WGS84 +units=m +no_defs `, so if Mapshaper's internals are a close reimplementation of that, this functionality may be there but not exposed in the command line interface.  Or perhaps there is a way to do it already, but if so I don't see it in the documentation on the wiki.

The Norwegian programmer Erik Smistad has apparently written a [script to do this task](https://github.com/smistad/konverter-norgeskart-projeksjon) that I'm going to go investigate now, but it would have been nice if Mapshaper had been able to do it.

**Comment by mbloch** [comment]
Thank you for the detailed instructions to reproduce. And apologies for the lack of documentation. Here's how you specify the  utm zone in your -proj command (hint: you have to enclose the Proj4 string in quotes, so mapshaper knows that the entire string belongs to the "from" parameter).

```
-proj from='+proj=utm +zone=33' wgs84
```
After exporting, you should see this in geojson.io:

![image](https://user-images.githubusercontent.com/1232222/90202784-ad4f7300-ddac-11ea-941c-d0874b4a693a.png)

**Comment by wdmartin** [comment]
Yup, that works.  Thank heavens.  The script I spent the last four hours working on to perform this task kept mangling the geometry anyway.  Now I can quit fiddling with that and get on with my life.

I have edited the wiki to add this information to the documentation on the `crs=` and `from=` parameters of `-proj`.  Please take a moment to check my work and make sure it is accurate. Once that's done, I think this can be closed.

**Comment by mbloch** [comment]
Thanks for contributing to the wiki... looks good to me.
