### ISSUE TITLE
geojson file seems to get corrupted when processed in mapshaper

### ISSUE THREAD

**Issue by mbkupfer** [mbloch/mapshaper#432]
I'm running into this issue with all the UK regions files in this repo: https://github.com/martinjc/UK-GeoJSON/tree/master/json/administrative

I'm choosing to narrow the problem down to the smaller Northern Ireland dataset which can be found here: https://github.com/martinjc/UK-GeoJSON/blob/master/json/administrative/ni/lgd.json

I'm not sure what is going on, but whenever I load the json file into mapshaper, it doesn't process well in my visualizing library. I narrowed it down to the step of loading/exporting from mapshaper, b/c the viz comes out fine when I used the untouched version. See below:

**No mapshaper version**
![image](https://user-images.githubusercontent.com/6313008/90569283-6d98da80-e162-11ea-9a26-f6192e6f3b5c.png)

**After loading into mapshaper. Didn't even simplify or make any correction, just loaded and exported right away**
![image](https://user-images.githubusercontent.com/6313008/90569287-725d8e80-e162-11ea-9320-b15398944d8f.png)

Any idea what is going on here?

**Comment by mbloch** [comment]
I have a hunch what might be causing this problem. Are you by any chance using d3, or a library that depends on d3?  If so, there's an incompatibility between d3 and the current revision of the GeoJSON standard (sometimes referred to as [RFC7946 GeoJSON](https://tools.ietf.org/html/rfc7946). D3 requires that the outer rings of most polygons have a clockwise winding order and GeoJSON states that outer rings should be counterclockwise. You can read about this issue in the [d3-geo README file](https://github.com/d3/d3-geo#d3-geo). 

(Is this accurate @tmcw?)

Mapshaper will output clockwise rings if you add the `gj2008` flag to the `-o` command. 

I wish that all GeoJSON files would "just work" in d3.... As things stand, d3 users need to understand the ways that d3-flavored GeoJSON is different than standard GeoJSON.

**Comment by mbkupfer** [comment]
Yes, I'm using plotly which uses d3 under the hood. I added the `gj2008` flag and it fixed it! Odd how I didn't run into this with plotly before.

Anyways, thank you so much for your quick and helpful reply!
