### ISSUE TITLE
Export to GeoJSON failed for an unknown reason

### ISSUE THREAD

**Issue by luptilu** [mbloch/mapshaper#433]
I dissolved [these regions](https://data.opendatasoft.com/explore/dataset/european-union-countries@public/export/) into one using the `--dissolve` command. I then wanted to export this in GeoJSON format but it did not seem to work. I got the error "Export failed for an unknown reason".

The following console error was displayed, not sure if related:

<img width="549" alt="Screenshot 2020-08-24 at 11 47 02" src="https://user-images.githubusercontent.com/34059973/91036599-89d3c600-e5ff-11ea-97fb-fb934fbd59be.png">

Or maybe if it is related to the fact that I no longer had attribute data due to dissolving the features.

Exporting as TopJSON seemed to work fine.

**Comment by mbloch** [comment]
Hi, thanks for reporting this. The previous release introduced the bug that you encountered. It should be fixed now, in v0.5.20.

Thanks too for including sample data! I noticed that this dataset includes several misaligned borders (a common occurrence). This shows up as red dots in the web UI. Dissolving will work better if you first clean up the borders by running the  `-clean` command. 

![image](https://user-images.githubusercontent.com/1232222/91053327-a74d6380-e5f0-11ea-92f2-534127ee6067.png)

**Comment by mbloch** [comment]
It looks like this issue was resolved, i'm closing.
