### ISSUE TITLE
map visualization creates odd lines originating from same point

### ISSUE THREAD

**Issue by mbkupfer** [mbloch/mapshaper#434]
I'm currently using mapshapper to compress a geojson of the United Kindgom and visualize them in plotly (a d3 supported visualization library)

The resulting viz has several lines all sprouting from the same corner. Do you have any idea what is going on here?

![image](https://user-images.githubusercontent.com/6313008/91101254-8c441900-e61b-11ea-9637-e23f5f9b3e9c.png)

**Comment by mbloch** [comment]
I haven't seen this particular problem... but if you send me a copy of the compressed GeoJSON along with the original file, I will look look into it.

**Comment by mbkupfer** [comment]
Thanks for looking into this!

I must've overwritten the original version, becuase now it is looking a bit different, but still has the same visual effect....just a bit more extreme now. The new json file is up here: https://api.jsonbin.io/b/5f4451a8993a2e110d35b08c

I downloaded the original shapefile from here:
https://geoportal.statistics.gov.uk/datasets/nuts-level-1-january-2018-full-clipped-boundaries-in-the-united-kingdom

**Comment by mbloch** [comment]
I don't use plotly myself, so I won't be able to reproduce this problem. I do see something that might be causing this issue. The coordinates in your GeoJSON file are projected coordinates, copied from the original Shapefile, in units of meters. GeoJSON files generally use geographical coordinates (latitude and longitude). I wonder if this is confusing plotly. You can try converting the Shapefile to geographical coordinates by running the `-proj wgs84` command in mapshaper, before or after you apply simplification. Please let me know if this solves the problem.

**Comment by mbkupfer** [comment]
When attempting the conversion to geographical coordinates, I get the following error message:

`Unable to project -- source coordinate system is unknown`

Is this something I need to provide via the `init` option? At least that is what I'm getting from the help message.

**Comment by mbloch** [comment]
I'm guessing that you were reprojecting a GeoJSON file...  If your input file is a Shapefile, you generally don't need to use `init`, because mapshaper gets the initial projection data from the  Shapefile's `.prj` file. GeoJSON (at least the current version of GeoJSON) does not contain projection information, so you need to use `init` to tell mapshaper what the current coordinate system is.

**Comment by mbkupfer** [comment]
> You can find this string by loading the Shapefile in mapshaper and running the -info command.

Ah, yes. this works like a charm.

Thank you so much! This is a great library, and an even greater maintainer 😃
