### ISSUE TITLE
City Boundary in County Dissolved Post Merging Layers

### ISSUE THREAD

**Issue by abhinava37** [mbloch/mapshaper#435]
Hi,

I am trying to display City of Detroit along with Counties in Michigan map. I have downloaded source files and imported the City of Detroit shape file and Michigan Counties shape file to Mapshaper. I have merged 2 layers using "merge-layers" command in Mapshaper console. I am able to see the City of Detroit boundary under Wayne County of Michigan map.

I have exported in TopoJSON format as a local file.  But, when I loaded this custom map to Shape Map visual in Power BI, I am not able to find the City of Detroit's boundary in Power BI. It is just showing me Wayne County. I have checked Map keys. It is fine. And when I filtered 'City of Detroit' in my fields, the Shape Map is approximately zooming in to Detroit's geographic location in Wayne County. 

I need a separate boundary for City of Detroit to appear so that I can click on either Detroit or rest of Wayne County in my Shape map visual of Power BI.

Can you please help me with what I am missing here? Am I missing something in Mapshaper? 

I am sharing the source file download links below.

http://gis-michigan.opendata.arcgis.com/datasets/cities-v17a/data?where=NAME%20%3D%20%27Detroit%27

http://gis-michigan.opendata.arcgis.com/datasets/counties-v17a/data

Thank you,
Abhinav

**Comment by mbloch** [comment]
Apologies for the slow reply. It sounds like you might want to cut the cities layer out of the counties layer, so that the county polygons do not overlap the city polygons. Mapshaper has a new command for that, `-inlay`. This is how to use `-inlay` using the command line program:
```
mapshaper Counties__v17a_.shp -inlay Cities__v17a_.shp -o output.shp
```

If you are using the web UI, you would load both layers and run `-inlay` in the console.
