### ISSUE TITLE
Reproject geojson for Scotland

### ISSUE THREAD

**Issue by mbkupfer** [mbloch/mapshaper#440]
Hi @mbloch ,

Having a projection issue which I can't quite figure out. My geojson file for Scotland is coming up like the right map in the below screenshot, but in fact, Scotland looks a lot different on most political maps used in the UK, as shown on the left. How do I fix this?

![image](https://user-images.githubusercontent.com/6313008/95636940-53ce9200-0a45-11eb-9cfe-3933c3463aab.png)

**Comment by mbloch** [comment]
Your map seems to be showing unprojected shapes. In other words, your dataset has coordinates in units of longitude and latitude, and the coordinates are being used as x- and y-coordinates on a cartesian plane. I don't know what software you're using to display the map, so I can't tell you how to fix the problem. You can try using QGIS or mapshaper's -proj command to project your coordinates. Also, your Scotland layer seems to be missing some bits and pieces.
