### ISSUE TITLE
.shx file causes errors when providing data in applyCommands' input argument

### ISSUE THREAD

**Issue by gaelhameon** [mbloch/mapshaper#443]
First of all, thanks for this great piece of software!

I'm using mapshaper inside a node project, using `applyCommands` , as suggested [here](https://github.com/mbloch/mapshaper/wiki/Using-mapshaper-programmatically#applycommands)

I run into errors when I try to use shapefiles as an input, and preloading the data of the files myself rather than just providing a path and letting mapshaper retrieve the data. The errors are different depending on the order in which the files are provided.

```
    var path = 'test/data/issues/166/';
    var input = {
      'a_utm.shp': fs.readFileSync(path + 'a_utm.shp'),
      'a_utm.shx': fs.readFileSync(path + 'a_utm.shx'),
      'a_utm.dbf': fs.readFileSync(path + 'a_utm.dbf'),
    };

    var cmd = `-i ${Object.keys(input).join(' ')} -o a_utm.geojson`;

    api.applyCommands(cmd, input, function (err, output) {
      console.log(err);
      console.log(output);
      assert.equal(err, undefined);
      assert.equal(output['a_utm.geojson'], JSON.stringify({some: 'geojson data'}));
      done();
    });
```

The code above, where the .shx file is provided after the .shp file, yields a "File not found" error: 

`Uncaught Error [UserError]: File not found (a_utm.shx)`

If I put the .shx file first:

```
    var input = {
      'a_utm.shx': fs.readFileSync(path + 'a_utm.shx'),
      'a_utm.dbf': fs.readFileSync(path + 'a_utm.dbf'),
      'a_utm.shp': fs.readFileSync(path + 'a_utm.shp'),
    };
```
I get this error: `Uncaught Error [UserError]: Missing an expected input type`

My understanding is that when we provide the shp file first, the import command also looks for the .shx file right away after reading the .shp file, and it reads the shx file as well.
After reading the file, it is deleted from the cache here:

https://github.com/mbloch/mapshaper/blob/6038e851e1ce0beee0acb4d2ad50905a3f72caf2/src/cli/mapshaper-cli-utils.js#L33-L37

But it's not deleted from the original list of input data. So the next file to import after the .shp is the .shx, but it has been removed from the cache and that causes the error.

When we provide the .shx first, I guess that there is usually something that looks for the associated .shp on the filesystem, which fails in this case because all of the data is in memory.

It's really not a big deal for me: I actually have no idea of what the .shx contains, and I get the data I want just fine in my geosjon by providing only the .shp and .dbf, but I figured it would still be worth trying to fix it.

I'd be glad to try working on a pull request for this, but I'd appreciate some pointers on what you think the best strategy is:
- somehow removing the file from the input files list at the same time as we remove it from the cache ?
- adding something to just ignore the error in that case and move on to the next file ?
- ...

**Comment by mbloch** [comment]
I think the problem is that you're listing all of the Shapefile components as arguments to the -i command. Mapshaper only expects the '*.shp' file to be listed, so it's trying to import the '*.shx' and other files as separate datasets.

**Comment by gaelhameon** [comment]
Oh ! That makes a lot of sense, thank you !
