### ISSUE TITLE
Export with transparent background

### ISSUE THREAD

**Issue by cfwt** [mbloch/mapshaper#444]
Is it possible to export a map with the transparent color as a background?

**Comment by mbloch** [comment]
Hi, you're referring to SVG export, right? I'm not currently setting any background color on the SVG document. When I export an SVG map, the map renders with a transparent background when I view it in a browser or import it into Adobe Illustrator. 

Are you asking me to add in inline CSS style to the <svg> element (`style="background:transparent"`)? If so, can you explain why you need that?
