### ISSUE TITLE
Fails to read really big geojson file

### ISSUE THREAD

**Issue by zingi** [mbloch/mapshaper#461]
The problem: I am trying to simplify a really big geojson file with mapshaper.

And it seems like, there are single polygons which occupy more space than the biggest possible buffer in node.js (currently 2GB on 64bit systems).

```
❯ mapshaper-xl -i results_sentinel_snow_vectorized.json -simplify 10% -filter remove-empty -o format=geojson geojson-type=FeatureCollection simplified.json                         
Allocating 8 GB of heap memory
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received type number (2147483648)
    at Function.from (buffer.js:333:9)
    at Object.createBuffer (/home/aaron/.nvm/versions/node/v14.15.3/lib/node_modules/mapshaper/mapshaper.js:901:57)
    at updateCache (/home/aaron/.nvm/versions/node/v14.15.3/lib/node_modules/mapshaper/mapshaper.js:8046:23)
    at FileReader.readSync (/home/aaron/.nvm/versions/node/v14.15.3/lib/node_modules/mapshaper/mapshaper.js:8007:7)
    at readObject (/home/aaron/.nvm/versions/node/v14.15.3/lib/node_modules/mapshaper/mapshaper.js:11378:39)
    at readObjects (/home/aaron/.nvm/versions/node/v14.15.3/lib/node_modules/mapshaper/mapshaper.js:11314:15)
    at GeoJSONReader.readObjects (/home/aaron/.nvm/versions/node/v14.15.3/lib/node_modules/mapshaper/mapshaper.js:11298:7)
    at importGeoJSONFile (/home/aaron/.nvm/versions/node/v14.15.3/lib/node_modules/mapshaper/mapshaper.js:11488:35)
    at readJSONFile (/home/aaron/.nvm/versions/node/v14.15.3/lib/node_modules/mapshaper/mapshaper.js:11502:17)
    at importJSON (/home/aaron/.nvm/versions/node/v14.15.3/lib/node_modules/mapshaper/mapshaper.js:11537:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

The workflow was always (last step = mapshaper simplify):
`input.tif => vectorized.json => simplified_vectorized.json`

Currently to bypass the problem, I use gdal_sieve.py to reduce the genereal complexity, so the biggest polygon is not greater than the maximum node.js buffer:
`input.tif => sieved_input.tif => vectorized.json => simplified_vectorized.json`

### If you want to reproduce the error:
* [This](https://mega.nz/file/mpJWibaJ#8wen6j_yXV49p-ZfUHH_0yC7REl7Q544RhmEh7zonj8) was the input.tif which was used to generate the geojson file. (you can preview it with QGIS)
* [This](https://mega.nz/file/GlQgAJIC#r1J-Sm8wnHOiTx43E-Q-8AOA7c2PCBBqFz054GnuPsQ) is the really big geojson file, where mapshaper-xl fails.
* [This](https://mega.nz/file/SlIACDYa#GUqHplWkxVlWN8UVBcY_wbBx464cLWyfuX9GQpTuqyU) is the geojson file, generated by vectorizing a sieved version of the input.tif, where mapshaper-xl does not fail.

(for context: the data is snow coverage over central europe, observed by a satellite)

(to unzip .lrz files, you can use lrzip:
* linux `sudo apt install lrzip`
* macos `brew install lrzip`
```
lrunzip someFile.lrz
```
)

**Comment by mbloch** [comment]
Thanks for reporting this :) It might be possible to support larger individual GeoJSON features by switching to an incremental JSON parser. (This would probably be a lot slower than the current method, which parses each GeoJSON feature separately using JSON.parse()). I'll leave this issue open in case someone wants to work on this.

**Comment by zingi** [comment]
@mbloch Maybe the module: [simdjson](https://github.com/luizperes/simdjson_nodejs) could somehow help in this use-case?

**Comment by zingi** [comment]
@mbloch I have implemented a prototype of a [Big FeatureCollection Reader](https://github.com/zingi/big-geojson-featurecollection-reader). 
It is able to read the mentioned big geojson file (6.2 GB) and yields its features sequentially.

Maybe you can use it for some inspiration or copy some parts of it?

Maybe we could implement it into mapshaper and trigger it as an alternative geojson file loader with a cli flag?

**Comment by mbloch** [comment]
This is great... i'm looking forward to testing this out.

**Comment by mbloch** [comment]
Hi Aaron,

I decided to write a general-purpose JSON parser that could parse features larger than the maximum Buffer size, instead of switching to your FeatureCollection parser. For one thing, it didn't seem desirable to have one parser for large files and another one for small files. I also wanted to improve parsing performance over mapshaper's old GeoJSON parser and also your new parser. The new parser is pretty fast -- up to twice as fast as JSON.parse() for some GeoJSON files.

The newly released v0.5.36 includes my new parser. It was able to import the 6GB file you submitted in about 200 seconds on my laptop:

```
time mapshaper-xl 50gb data/results_sentinel_snow_vectorized.json no-topology
Allocating 50 GB of heap memory
      120.72 real       193.06 user        22.13 sys
```

I appreciate the work you did on this problem! There are likely even more performance gains to be found.

**Comment by zingi** [comment]
Thank you Matthew, for taking your time to investigate my code. And thank you for providing such a great open source tool.

**Comment by yuletide** [comment]
I'm having this same issue, trying to run `-points` on a very large JSON file:

```
mapshaper-xl -i temp/sedac_global.shp \
                -points x=INSIDE_X y=INSIDE_Y \
                -o temp/sedac_inside.shp
Allocating 8 GB of heap memory
RangeError [ERR_FS_FILE_TOO_LARGE]: File size (6694163048) is greater than 2 GB
    at new NodeError (node:internal/errors:371:5)
    at tryCreateBuffer (node:fs:419:13)
    at Object.readFileSync (node:fs:464:14)
    at Object.cli.readFile
```

**Comment by ThomasG77** [comment]
Not sure why you don't use a direct way purely based on `ogr2ogr` e.g

```bash
ogr2ogr sedac_global.shp gpw_v4_admin_unit_center_points_population_estimates_rev11_global.gpkg -dialect SQLite -sql "SELECT OBJECTID, GUBID, ISOALPHA, COUNTRYNM, NAME1, NAME2, NAME3, NAME4, NAME5, NAME6, CENTROID_X, CENTROID_Y, INSIDE_X, INSIDE_Y, CONTEXT, CONTEXT_NM, WATER_CODE, TOTAL_A_KM, WATER_A_KM, LAND_A_KM, UN_2000_E, UN_2005_E, UN_2010_E, UN_2015_E, UN_2020_E, UN_2000_DS, UN_2005_DS, UN_2010_DS, UN_2015_DS, UN_2020_DS, B_2010_E, F_2010_E, M_2010_E, A00_04B, A05_09B, A10_14B, A15_19B, A20_24B, A25_29B, A30_34B, A35_39B, A40_44B, A45_49B, A50_54B, A55_59B, A60_64B, A65PLUSB, A65_69B, A70PLUSB, A70_74B, A75PLUSB, A75_79B, A80PLUSB, A80_84B, A85PLUSB, A00_04F, A05_09F, A10_14F, A15_19F, A20_24F, A25_29F, A30_34F, A35_39F, A40_44F, A45_49F, A50_54F, A55_59F, A60_64F, A65PLUSF, A65_69F, A70PLUSF, A70_74F, A75PLUSF, A75_79F, A80PLUSF, A80_84F, A85PLUSF, A00_04M, A05_09M, A10_14M, A15_19M, A20_24M, A25_29M, A30_34M, A35_39M, A40_44M, A45_49M, A50_54M, A55_59M, A60_64M, A65PLUSM, A65_69M, A70PLUSM, A70_74M, A75PLUSM, A75_79M, A80PLUSM, A80_84M, A85PLUSM, MakePoint(INSIDE_X, INSIDE_Y, 4326) AS geom FROM gpw_v4_admin_unit_center_points_population_estimates_rev11_global"
```

Hope it helps

**Comment by yuletide** [comment]
@ThomasG77 Yes this is exactly what I was looking for! I tried a few ways and could not get it working. I was trying to use `CAST()` instead of `MakePoint()` so this is very helpful. Thanks!

**Comment by ThomasG77** [comment]
Also not sure you were not satisfied by default points as output of `ogrinfo -so -al gpw_v4_admin_unit_center_points_population_estimates_rev11_global.gpkg` show you there are already points.

Normally, doing just `ogr2ogr sedac_global.shp gpw_v4_admin_unit_center_points_population_estimates_rev11_global.gpkg` is enough

**Comment by mbloch** [comment]
@yuletide  GPKG support is probably not coming to mapshaper in the new future (i don't have much time to work on it, and i need to prioritize features that my colleagues and I will use).

Support for large DBFs is more achievable in the short term. 

If you want a mapshaper solution that you can use right now, that would be to use the CSV-formatted files from GPW (I believe they release their data in CSV, GPKG and GeoDatabase formats). Mapshaper can read very large CSV files. If you only need a few data fields, you can use the `-i csv-fields=` option, which can speed up importing by a lot. This command took about 30 seconds to import a 2G CSV file and convert to points:

```
mapshaper-xl gpw_v4_admin_unit_center_points_population_estimates_rev11_usa_midwest.csv csv-fields=INSIDE_X,INSIDE_Y,UN_2020_E -points x=INSIDE_X y=INSIDE_Y -o points.shp

```

**Comment by yuletide** [comment]
Great, this makes sense and lets me skip the ogr step entirely. Appreciate your help and this awesome tool!
