### ISSUE TITLE
Reserved words in JS may conflict with feature property names

### ISSUE THREAD

**Issue by clhenrick** [mbloch/mapshaper#462]
With the Mapshaper CLI if I'm attempting to filter features using a feature's property/attribute and the property name is a reserved word in JavaScript, a syntax error will be thrown. 

For example, if my features have an attribute called "class" and I attempt to do a `-filter 'class === "some string"'` then Mapshaper will throw a syntax error. I can work around this by using the `this` context, e.g. `-filter 'this.properties.class === "some string"'` but the docs do not clarify to users that this edge case exists.

Here is sample data and commands to reproduce:

`test_data.json`

```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "id": 0,
      "properties": { "class": "a", "foo": 1 },
      "geometry": {
        "type": "Point",
        "coordinates": [125.6, 10.1]
      }
    },
    {
      "type": "Feature",
      "id": 1,
      "properties": { "class": "b", "foo": 2 },
      "geometry": {
        "type": "Point",
        "coordinates": [0, 0]
      }
    }
  ]
}
```

This command throws a syntax error `[filter] SyntaxError in expression [class === "a"]`

```bash
mapshaper test_data.json -filter 'class === "a"'
```

This command works as intended:

```bash
mapshaper test_data.json -filter 'this.properties.class === "a"'
```

**Comment by mbloch** [comment]
This is the expected behavior.  If a data property name is not a valid JS variable name, then it can't appear by itself in an expression. You have to use a different syntax. A shortcut for `this.properties.class` is `d.class`. (This idiom comes from d3).

**Comment by clhenrick** [comment]
@mbloch thank you for clarifying.

However I could not find this stated in the docs for `-filter` or `-each` so I do think it would be helpful to document it for users, unless I missed it somewhere. The context is that I was helping someone debug their CLI command and they were confused by why they were getting this syntax error.

**Comment by mbloch** [comment]
Good suggestion! The documentation on expressions could certainly be improved.
