### ISSUE TITLE
Mapshaper -proj resulting shapes in wrong Hemisphere

### ISSUE THREAD

**Issue by AlpacaJ** [mbloch/mapshaper#474]
This is essentially a copy/paste of my question on GIS-stackexchange before I thought to check on the mapshaper github (I won't include the link here but the title of the question is the same).

----
I have shapefiles that I am projecting in Mapshaper, however when I use `-proj WGS84` the end-result (topoJSON) has the shapes in the Northern Hemisphere, rather than the Southern Hemisphere.

On inspecting the shapefiles using `info` it shows` 'CRS: +proj=utm +zone=55 +datum=WGS84` which to me indicates the default is UTM55N, not 55S as I want it to be.

When I explicitly specify UTM55S using `-proj from=EPSG:32755 crs=EPSG:4326` I get the correct end-result with the shapes in the Southern hemisphere.

The prj file contained within the shapefiles zip appears to specify 55**S**:

`PROJCS["WGS_1984_UTM_Zone_55S",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",10000000.0],PARAMETER["Central_Meridian",147.0],PARAMETER["Scale_Factor",0.9996],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]`

Why can't I use `-proj WGS84`? Do I need to change the prj file or is the only solution to keep explicitly referring to the EPSG number for **S** (because perhaps it defaults to **N**?)

**Comment by mbloch** [comment]
It's possible that mapshaper's code for parsing prj files is not correctly parsing the name `WGS_1984_UTM_Zone_55S`. If you can send me a sample file to help me test, I'll try to get this fixed.

**Comment by AlpacaJ** [comment]
PRJ file attached - thanks for looking into this!
[PRJ test.zip](https://github.com/mbloch/mapshaper/files/6242517/PRJ.test.zip)

**Comment by mbloch** [comment]
There was a bug in the mapshaper-proj library... I fixed this and published an update. Should work now.

**Comment by AlpacaJ** [comment]
thanks for fixing this so quickly! Just tested and it `-proj wgs84` projects correctly now

Do you think it's possible to add the ZoneLetter from the UTM projection to the CRS information from `info` as well?

At the moment it returns: `CRS:      +proj=utm +zone=55 +south +datum=WGS84` and it would be good if it actually showed `(..) +zone=55S (..)`

**Comment by mbloch** [comment]
I'm trying to use CRS codes that are compatible with the open-source Proj library. It looks like Proj uses `+zone=55 +south` rather than `+zone=55S`, so I'd rather keep things as they are (see: https://proj.org/operations/projections/utm.html)
