### ISSUE TITLE
Mapshaper fails when final folder in shapefile path contains period

### ISSUE THREAD

**Issue by AlpacaJ** [mbloch/mapshaper#476]
When I run `mapshaper "c:\Users\firstName.lastName\folder1\folder2\01.1 folder name\shapefile.shp" proj crs=EPSG:4326 -o "c:\Users\firstName.lastName\folder1\folder2\01.1 folder name" format=topojson`

I get an error message as per screenshot below:

`Error: EISDIR: illegal operation on a directory,` and `errno: -4068`

![mapshaper error](https://user-images.githubusercontent.com/73318764/113810068-cd54fc00-97ac-11eb-9e89-9f45b3ebdfe5.png)

When I remove the dot in the final folder name this operation works as planned (so if the final folder name is _01_1 folder name_)

I am planning on using this as part of an embedded macro that captures the file path from the creation process of the shapefiles so I do not have control over how users name their folders.

**Comment by mbloch** [comment]
The latest release (0.5.46) should fix this issue, which also affected non-Windows systems.
