### ISSUE TITLE
String vs Number - other solutions aren't working

### ISSUE THREAD

**Issue by Marklack71** [mbloch/mapshaper#478]
Hi I hope someone can help.

I found a post where csv files turn text into numbers, making the join not possible.  The solution has not worked to add string-fields=<feilds>

Here is my code:

$ join CountyMTAShapefile.csv string-fields=FIPS,GEOID keys=GEOID,FIPS 
Join keys have mismatched data types: string and number 

alternatively I could key on state and county to get them together but 2 keys don't seem to work either.

TIA,

Mark

**Comment by mbloch** [comment]
I'll investigate if you provide example data files. This is an older issue that I overlooked before -- I'm going to close for now, feel free to reopen as needed.
