### ISSUE TITLE
Filtering and slicing polygons by bbox

### ISSUE THREAD

**Issue by apresmoi** [mbloch/mapshaper#480]
Hello,

Is there a way (with the current status of the tool) to slice and filter a layer with a limiting bbox ?

If there is not, would you be interested in such feature ?

Regards,
Juan

**Comment by mbloch** [comment]
It sounds like the `clip` command does what you want... it has a `bbox` option for clipping to bounding box. the command line syntax is:  `-clip bbox=<xmin,ymin,xmax,ymax>`. The web UI has a "shift-drag box tool" option under the arrow menu that can do a similar thing interactively.

**Comment by apresmoi** [comment]
Awesome, thank you !

I'll try and see what happens.

**Comment by apresmoi** [comment]
Works as spected, thank you !
