### ISSUE TITLE
Are the points inside a polygon ?

### ISSUE THREAD

**Issue by chris3522** [mbloch/mapshaper#482]
Hello,

Is it possible to determine in a list of points, which points are included in a polygon with mapshaper?
I've tried this 
```
 mapshaper.runCommands(`points.csv -points -clip polygons.json -o result.csv`)
```
But I get an error 
```
UserError: Missing x,y data fields
```
My entry files are:
a grid csv points 
```
-6,51.5
-5.99,51.5
-5.98,51.5
-5.97,51.5
....
```
and a geojson.
```
{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"code":"DOLLER_AMONT","NAME":"Doller amont"},"geometry":{"type":"Polygon","coordinates":[[[6.9837,47.8433],[6.9837,47.8432], ......
```
 Other question: Can I choose one of its polygons from the command line?
Many thanks.

**Comment by mbloch** [comment]
Hey, once you have converted the coordinates to point features, you can do a spatial join to determine which of the points are within a polygon. In this example, a field named "n" gets created on the points layer, with a value of 0 if a point is outside all the polygons, or a value of >=1 if the point is inside one or more polygon.
  
  ```
  mapshaper points.json \
  -join polygons.json calc='n = count()'

**Comment by chris3522** [comment]
Many Many thanks mister Bloch by adding -filter 'n>"0"', I get exactly what I want!

**Comment by chris3522** [comment]
Hello M Bloch,
I'm sorry to reopen this issue, but there is a case where the command you gave me does not meet my needs. 
Indeed when a polygon is included in a larger polygon: the small polygon does not recover the intersection with the grid of points. Do you think it is possible to optimize this command?

Here is an example where the point is assigned to polygon 44 (the largest) while the included polygon number 69 has no point. So I get a point with an id_bv = 44. 
It would be necessary to be able to duplicate this point and give it the id_bv of the smallest polygon.

thank you so much.

![exemple1](https://user-images.githubusercontent.com/60651125/143050502-ce27881f-ccbb-4ad0-b740-989295dd5863.png)
![exemple2](https://user-images.githubusercontent.com/60651125/143050515-ecd9b7d3-bd16-4856-9ee4-bcdeb9c4f1e6.png)

**Comment by mbloch** [comment]
You can use the new `duplication` option with the join command. To join attributes from the polygon layer to the points layer (named "points" in the example below), you could do this:
```
-join points duplication
```
The `duplication` option creates multiple versions of a target feature when there is a on-to-many join.

**Comment by chris3522** [comment]
So cool :)
