### ISSUE TITLE
 Problem cleaning with a polygon inside another but with a shared border

### ISSUE THREAD

**Issue by chris3522** [mbloch/mapshaper#486]
Hello M. bloch,
I can't seem to clean up these shared boundaries when one polygon is inside another. See attached photos.
The "clean" command will erase the polygons inside. 

![detail](https://user-images.githubusercontent.com/60651125/118662640-76513680-b7f0-11eb-8227-2adbee1e1449.png)
![pic2](https://user-images.githubusercontent.com/60651125/118662647-76e9cd00-b7f0-11eb-8c7a-fd4b52f0deef.png)
![pic1](https://user-images.githubusercontent.com/60651125/118662651-781afa00-b7f0-11eb-9721-133edc86b3db.png)

Many thanks for your advice on this point.

**Comment by chris3522** [comment]
I finally succeeded but it is very complicated. It takes several steps (examples with p1, p2 in pBig):
0) have several layers of polygons p1, p2, pBig
1) merge layers of small polygons (s1, s2) into sOne
2) dissolve
3) adding properties lost with each
4) export of sOne
5) merge sOne and pBig
6) mosaic
7) adding properties lost with each
8) Filter of the amputated polygon named pBig2
9) Adding sOne
10) merge target = sOne, pBig2
11) dissolve to reconstruct the large polygon
13) adding lost properties with each

  ;))))

**Comment by mbloch** [comment]
Hi, sorry i didn't have a chance to respond to this issue earlier... thanks for sharing your solution, @chris3522. It would be nice to have a simpler way to fix topology errors across layers... I'll try to explore this problem when I have more time.
