### ISSUE TITLE
About clean command

### ISSUE THREAD

**Issue by chris3522** [mbloch/mapshaper#490]
Hello,
Is there a way to use clean command but preventing the removal of polygons with data, even when it is overlapping polygons?
Many thanks

**Comment by chris3522** [comment]
I'm sorry I hadn't seen the option "clean allow-overlaps". But I wonder if there is an option to make overlap near boundaries coincide with the enclosing polygon?

**Comment by mbloch** [comment]
Hi... no need to apologize... i just added `allow-overlaps` yesterday
