### ISSUE TITLE
Colorizer not working when column name is numeric

### ISSUE THREAD

**Issue by gurmanbh** [mbloch/mapshaper#496]
I have a couple of columns in a csv where the name of a the column is a number. Years in this case. After merged the columns with a shapefile, when I try to use the colorizer, the function gives the colour for the number (which in this case is the year), instead of the value of that year for that particular enter. I prepended the year name with a alpha string, and that solved the issue. Is there a way to deal with this without changing the column names in the csv?

**Comment by mbloch** [comment]
Hi,
Without seeing the command that you ran, I can only speculate... but it sounds like you are using the name of the column in an expressions, perhaps like this: `-style fill=getColor(2020)`. In this expression, 2020 is a number, not the value of a field. The form to use when a field is not a valid JS variable name is this: `-style fill=getColor(d["2020"])`. If this does not solve your problem, please paste the command that you're running in another comment. Thanks!

**Comment by gurmanbh** [comment]
That worked! Thank you.
