### ISSUE TITLE
erase broken with collection of overlapping polygons

### ISSUE THREAD

**Issue by matkoniecz** [mbloch/mapshaper#497]
`mapshaper -i combine-files 'water.geojson' -erase source='bridge.geojson'   -style fill="#666666"   -proj webmercator   -o 'water.svg'` gives unexpected holes in output geometry

water.geojson
```
{"type":"GeometryCollection", "geometries": [
{"type":"Polygon","coordinates":[[[19.934934,50.04876],[19.935084,50.04876],[19.935834,50.04876],[19.935644,50.048989],[19.935369,50.049349],[19.935089,50.049745],[19.934876,50.050037],[19.934385,50.050743],[19.934373,50.05076],[19.933674,50.05076],[19.93353,50.05076],[19.93335,50.05076],[19.93335,50.04977],[19.933496,50.049562],[19.933852,50.049067],[19.934019,50.048834],[19.934076,50.04876],[19.934934,50.04876]]]}
]}
```

bridge.geojson
```
{"type":"GeometryCollection", "geometries": [
    {"type":"Polygon","coordinates":[[[19.933,50.049],[19.93551,50.049854],[19.935404,50.049994],[19.93335,50.049412],[19.933,50.049]]]},
    {"type":"Polygon","coordinates":[[[19.935486,50.049901],[19.935476,50.049898],[19.933447,50.04925],[19.935489,50.049902],[19.935486,50.049901]]]},
    {"type":"Polygon","coordinates":[[[19.934972,50.049805],[19.935433,50.049953],[19.934936,50.049819],[19.934966,50.049804],[19.934972,50.049805]]]},
    {"type":"Polygon","coordinates":[[[19.934953,50.049862],[19.933365,50.049356],[19.934992,50.049831],[19.934953,50.049862]]]}
    ]}
```

**Comment by matkoniecz** [comment]
Note: I can try to simplify it a bit further (let me know if that would be useful), but now it is time to find a workaround.

water.geojson
![screen01](https://user-images.githubusercontent.com/899988/126893737-d1684fea-9d32-40f4-b8a0-47a8ce1739a3.png)


bridge.geojson
![screen02](https://user-images.githubusercontent.com/899988/126893740-80b3b4ca-9ddc-4055-a07e-b02e0a60d80c.png)

output (hole should not be there)
![screen03](https://user-images.githubusercontent.com/899988/126893775-6e8e5e11-0465-4a36-bd23-f223a3d1e2d0.png)

**Comment by mbloch** [comment]
Hi, thanks for reporting this and providing sample files :)
As you discovered, erasing (and clipping) with a layer containing overlapping shapes didn't work correctly. I think this is fixed now in v0.5.63.

**Comment by matkoniecz** [comment]
Thanks - and here are coasters made with (among other tools) with Mapshaper (operation on geometries like filtering out small water areas and removing water under bridge areas - and geojson to SVG)

![IMG_20210728_165231](https://user-images.githubusercontent.com/899988/127762538-77480b5c-9f37-47b2-8059-298a16b9db09.jpg)

**Comment by mbloch** [comment]
Love the coasters!
