### ISSUE TITLE
Group points by shape (question)

### ISSUE THREAD

**Issue by giorigor** [mbloch/mapshaper#499]
Hello!
I have two layers: one containing multiple points (point_id + coordinates) and one containing multiple polygons (shape_id + coordinates). Is there a way to check if a point is inside a specific polygon?

What I wanted was to output the points layer with a new attribute, naming the shape it was contained in. I'm having trouble using `clip` and `each`, since it removes the other points outside of the first polygon.

For example the following situation: red polygons are in the "Shapes" layer, and the green dots are in the "Points" layer.
![image](https://user-images.githubusercontent.com/10777906/127178075-e2e2ef47-384f-4da2-b9af-5ee224d07307.png)

My input CSV is as follows:
```
point_id: 1 | x: whatever | y: whatever
point_id: 2 | x: whatever | y: whatever
point_id: 3 | x: whatever | y: whatever
point_id: 4 | x: whatever | y: whatever
```
I'd like to output the following CSV or GeoJson:
```
point_id: 1 | x: whatever | y: whatever | shape_id: A
point_id: 2 | x: whatever | y: whatever | shape_id: A
point_id: 3 | x: whatever | y: whatever | shape_id: B
point_id: 4 | x: whatever | y: whatever | shape_id: null (or the field can be absent as well)
```

**Comment by mbloch** [comment]
You want to do a spatial join to copy data from the polygon layer to the point layer. so:
```
mapshaper points.json -join polygons.json fields=shape_id -o output.csv
```

**Comment by giorigor** [comment]
Wow I feel stupid, it was this simple hahah
Thanks!
