### ISSUE TITLE
Combining Fields From Multiple Datasets

### ISSUE THREAD

**Issue by mapguy10034** [mbloch/mapshaper#502]
I am trying to tie census tract data to congressional data in the mapshaper browser. I'll use the state of Michigan as an example (Data is attached below). 

The Michigan Congressional District Map looks like:
![image](https://user-images.githubusercontent.com/90933250/133846178-4336258a-baec-48ab-a8aa-5b6f777eb1fe.png)

The Michigan Census Tract Map looks like:
![image](https://user-images.githubusercontent.com/90933250/133846084-0f3c0832-8cb7-4fd4-9afb-014188057668.png)

My aim is to add an additional field to the Census Tract Map called 'Legislator', based on the 'Legislator' field from the U.S. Congressional District Map. Using the tract highlighted in the pictures as an example, the field 'Legislator' would have the entry 'John Moolenaar'. I have tried many of the commands from the command reference on this GitHub page (including merge-layers using 'force') and have looked at many previously posted questions, but I am unsure of a way to get the two layers to talk to each other in the way that I want. 

When I do merge the layers, (using command "-merge-layers target=2010_Census_Tracts_(v17a),Michigan_U.S._Congressional_Districts_(v17a) force") one can see that when highlighting an individual census tract, the outline of the congressional district is shown, implying that there may be a way to intertwine the datasets. A picture of this looks like:
![image](https://user-images.githubusercontent.com/90933250/133847176-6af698c6-06ab-4535-8764-8bae466edd7c.png)

Based on the above picture, I could manually add the Legislator to the Census Tract, but I wouldn't want to do that for 2000+ tracts. Is there a way to do this using the command line in the browser version of mapshaper?

Side Note: In the event a census tract covers multiple congressional districts, how would I choose the congressional district where the census tract has the most area?

Thank you for creating this wonderful online map tool.

[2010_Census_Tracts_(v17a).zip](https://github.com/mbloch/mapshaper/files/7188122/2010_Census_Tracts_.v17a.zip)
[Michigan_U.S._Congressional_Districts_(v17a).zip](https://github.com/mbloch/mapshaper/files/7188123/Michigan_U.S._Congressional_Districts_.v17a.zip)

**Comment by mbloch** [comment]
It sounds like the "join" command is what you need. to copy the LEGISLATOR field from the districts layer to the tracts layer using a spatial join, and selecting the source feature with the largest overlapping area, you would run the following command with the tracts layer selected in the web UI and the districts layer renamed to "districts":
```
join districts fields=LEGISLATOR largest-overlap
```

**Comment by mapguy10034** [comment]
This worked perfectly. Thank you!
