### ISSUE TITLE
Getting zoom 18 geojson tiles as output

### ISSUE THREAD

**Issue by psociety** [mbloch/mapshaper#503]
Hi again @mbloch !
Sorry for having to reach you back :(
I want to export an SHP as zoom 18 geojson tiles.
Checking the wiki the nearest thing i find is `-split-on-grid` but it uses grid dimensions rather than zoom. 
(https://github.com/mbloch/mapshaper/wiki/Command-Reference#-split-on-grid)

Is this the best way to go to achieve what i'm trying?
So i will have to findout the dimensions of a z18 tile right?

**Comment by mbloch** [comment]
`-split-on-grid` won't work well for making vector tiles. Mapshaper doesn't support making vector tiles. There might be a workflow that uses tippecanoe to generate an mbtiles file, and another utility (maybe this one: https://github.com/mapbox/mbtiles-extracts ... or this one: https://github.com/mapbox/mbutil) to export GeoJSON files.

**Comment by psociety** [comment]
ok, ty for taking your time to reply!
