### ISSUE TITLE
[feature request] "keep-shapes" by attribute

### ISSUE THREAD

**Issue by tobwen** [mbloch/mapshaper#504]
Would it be possible to keep polygons by attribute, e.g.
-  _Don't change the shape of this city, since it's important, but I don't care about the surrounding ones_?

**Comment by mbloch** [comment]
Is this in reference to simplification? If so, you can use the `variable` flag together with a JS expression, like this (given a boolean attribute field named IMPORTANT):
```
-simplify variable percentage='IMPORTANT ? 1 : 0.1'
```

**Comment by tobwen** [comment]
Incredible, thanks a lot!
![image](https://user-images.githubusercontent.com/1864057/135343829-9f9d0f1f-d276-4814-b683-f9b417cbb588.png)

**Comment by tobwen** [comment]
Maybe you allow another question. I'd love to keep the outer boundary of all polygons (in red color). Would you suggest converting them to polylines and also apply an "importance" variable here?

![image](https://user-images.githubusercontent.com/1864057/135344762-4b529df9-439f-4deb-9584-0730acde6c7a.png)

**Comment by tobwen** [comment]
Yes, it works. Thanks a lot.

![image](https://user-images.githubusercontent.com/1864057/135346377-70c9c8d4-8db4-483c-b55c-996e9b1c22e0.png)

**Comment by mbloch** [comment]
I guess converting the polygons to polylines is the way to do this, like you suggested:
```
-lines -simplify variable percentage='TYPE == "outer" ? 1 : 0.1' -polygons
```
If you are only interested in the shape of the boundaries, this should work fine. It's trickier if you want to preserve the attribute values.

**Comment by tobwen** [comment]
I can transfer the attribute using normal GIS techniques, so this is fine. Thanks a lot!

**Comment by wuqi** [comment]
My workflow :
1.  mapshaper  -i  data.shp -clean rewind -lines -filter "RANK == 0" -points  -o dataBoundPoint.shp
2. mapshaper -i  data.shp -join dataBoundPoint.shp   -clean rewind    -simplify variable percentage='RANK == 0 ? 1 : 0.1'   result.geojson
In this way I can get a polygon layer with original attribute values
