### ISSUE TITLE
[feature request] undo / redo

### ISSUE THREAD

**Issue by tobwen** [mbloch/mapshaper#505]
## intro
I might be mistaken, but I haven't found an _undo_ function.

## undo
`-undo` the last action
`-undo 3` the last three actions

## redo
`-redo` the last action
`-redo 3` the last action for three times

**Comment by mbloch** [comment]
I added undo/redo with keyboard shortcuts to most of the editing modes that you can access from the arrow menu. undo data is only saved while the editing mode is turned on.
