### ISSUE TITLE
[feature request] reduce precision

### ISSUE THREAD

**Issue by tobwen** [mbloch/mapshaper#507]
## What?
Since v3,1, _PostGIS_ has a great new function: https://postgis.net/docs/ST_ReducePrecision.html
It returns a valid geometry with all points rounded to the provided grid tolerance, and features below the tolerance removed. Unlike snapping to a grid, the returned geometry will be valid, with no ring self-intersections or collapsed components.

## Why?
Sometimes, you need to work in a fixed precision (cadastral data, etc.). Some output filters might support this, but it might be interesting within a _mapsharper_ processing chain.

**Comment by mbloch** [comment]
In mapshaper, using `-snap precision=0.0001` (for example) will reduce coordinate precision and snap vertices to a grid. If you then run `-clean`, mapshaper will remove self-intersections and fix other geometry problems.

But, `-clean` can insert new vertices, and those vertices are full-precision, so the output is not strictly fixed-precision.

This feature request seems a bit niche for mapshaper -- at least, it's not something I've ever needed in my map making work. I'm going to put it on hold for now.
