### ISSUE TITLE
Is there a command to split a lines file every xxx meters?

### ISSUE THREAD

**Issue by aborruso** [mbloch/mapshaper#508]
Hi,
I need to split it in example every 100 m..

Thank you

**Comment by ThomasG77** [comment]
Try https://github.com/ThomasG77/geojson-line-chunk

Done due to your question

**Comment by aborruso** [comment]
You are great @ThomasG77 !

Thank you

**Comment by mbloch** [comment]
This strikes me as a special-purpose need that would only be useful to a few users. I probably wouldn't add this functionality directly to mapshaper. But there may be a way to support calling out to external scripts.

One option I'm considering: The `this` object that is available in `-each` expressions could have a `geojson` getter/setter. This would let you edit each feature using a custom JS script that you would load using the `-require` command.

The syntax might look like this, where `script.js` is a Node module that exports a function called `splitLine()`:

```
mapshaper lines.geojson \
-require script.js \
-each 'this.geojson = splitLine(this.geojson)' \
-o edited_lines.geojson
```

I'm also open to other suggestions

**Comment by aborruso** [comment]
I like this proposal @mbloch .

I'm closing the issue.

Thank you for all

**Comment by mbloch** [comment]
I added just added support for `this.geojson` in `-each` expressions. I know I'll use this in my work, I hope others find it useful as well.

**Comment by aborruso** [comment]
@mbloch if you can, and when you have the time, could you add an hello world example in the wiki documentation?

Thank you

**Comment by mbloch** [comment]
@aborruso I will update the docs. Meanwhile, by coincidence, I needed similar functionality myself today for creating dashed lines for disputed borders. I just updated mapshaper with a new and undocumented function, `-split-lines`. If you run it with a `dash-length=` option but no `gap-length=` option, it will divide lines into contiguous sections. 

```
COMMAND
  -split-lines  (undocumented command)

OPTIONS
  dash-length=  length of split-apart lines (e.g. 200km)
  gap-length=   length of gaps between dashes (default is 0)
  planar        use planar geometry
  where=        use a JS expression to select a subset of features
  target=       layer(s) to target (comma-sep. list)
```

Example command:
`-split-lines dash-length=25km gap-length=35km where='type == "disputed"'`

**Comment by aborruso** [comment]
Wow, thank you very much!
