### ISSUE TITLE
How display version with runCommands

### ISSUE THREAD

**Issue by chris3522** [mbloch/mapshaper#509]
Hello,
I've tried this in nodejs, there is the code in a file named file-test.js:
```
const mapshaper = require('mapshaper')
async function test() {
    let cmd = `-v`
    await mapshaper.runCommands(cmd)
}
test
```
and then 
```
node file-test.js
```
to display the version of mapshaper but I guess I'm doing something wrong because nothing happened.
Many thanks

**Comment by ThomasG77** [comment]
You are not doing wrong. It's just the version info is removed from the result when running mapshaper from Node.js e.g
https://github.com/mbloch/mapshaper/blob/master/src/cli/mapshaper-run-commands.js#L326-L329

To get the mapshaper version, use Node.js [`require.resolve`](https://nodejs.org/api/modules.html#requireresolverequest-options) like below :

```
const fs = require('fs');

const pathToMapshaperPackageJson = require.resolve('mapshaper/package.json');

const content = fs.readFileSync(pathToMapshaperPackageJson, 'utf8')
console.log(JSON.parse(content).version);
```

**Comment by chris3522** [comment]
Thanks!

**Comment by mbloch** [comment]
Another way to do this is by calling the module function `enableLogging()`, for example:
```
const mapshaper = require('mapshaper');
mapshaper.enableLogging();
mapshaper.runCommands('-v');
```
