### ISSUE TITLE
Many to One Joins

### ISSUE THREAD

**Issue by Zulu-Inuoe** [mbloch/mapshaper#510]
Hey all,

I'm asking in hopes that I'm missing some obvious way to do this, but I have a many-to-many dataset.
In particular, I have a dataset of AreaIDs->Polygons, where Polygons can belong to more than one AreaID.
My Areas are just ID's, and my polygons are geojson features.

Ultimately, if I have 5 Areas, I want to end up with 5 features, one for each area and with the Polygons essentially Duplicated so that they appear in more than one area...

eg

AreaA->PolygonX
AreaA->PolygonY
AreaB->PolygonX
AreaC->PolygonZ

Any thoughts?

Thanks!

**Comment by mbloch** [comment]
I just published v0.5.70, which adds a `duplication` flag to the `-join` command. If you use `-join duplication`, many-to-one joins will cause features in the target layer to be duplicated. You can try joining a table of area-to-polygon mappings to your polygon layer using `duplication` to get your desired output.
