### ISSUE TITLE
Import doesn't work on mapshaper.org

### ISSUE THREAD

**Issue by antonrinas** [mbloch/mapshaper#514]
I'm trying to import this file:
https://www.hudexchange.info/resources/documents/CoC_GIS_National_Boundary_2021.zip
here
https://mapshaper.org/
But nothing happens. I tried to drop the file and by using the "Select" button.
I'm using the last Chrome.

**Comment by geodata4all** [comment]
Zip file contain ESRI File Geodb format which is not recognized by mapsahper.

**Comment by antonrinas** [comment]
Got it, thank you!

**Comment by ThomasG77** [comment]
If you need it as shp, download it https://www.hudexchange.info/resources/documents/CoC_GIS_National_Boundary_2021.zip
uncompress. Rename directory `CoC_GIS_National_Boundary_2021` to `CoC_GIS_National_Boundary_2021.gdb` and then do

```
ogr2ogr output.shp CoC_GIS_National_Boundary_2021.gdb FY21_CoC_National_Bnd -lco ENCODING=UTF-8
```

PS: I consider you know how to install and use GDAL command line utility `ogr2ogr`

**Comment by antonrinas** [comment]
@ThomasG77 Thank you! It works for me!
