### ISSUE TITLE
Problem with parsing of some .prj WKT strings

### ISSUE THREAD

**Issue by jaltin** [mbloch/mapshaper#517]
Hi,

We are testing out mapshaper (version 0.5.77) and love it so far!

In our tests we have run into an issue with some .prj WKT strings. When trying to parse a shapefile with the error-causing WKT we get the following error:

> Unusable .prj file (unparsable WKT format)

An example of a failing WKT (taken from the .prj file:

> GEOGCS["",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223562997]],PRIMEM["Greenwich",0],UNIT["Degree",0.0174532925199433]]

Our digging into this problem has narrowed down the error to this function in **mproj.js**

```// Convert WKT string to a JS object
// WKT format: http://docs.opengeospatial.org/is/12-063r5/12-063r5.html#11
function wkt_unpack(str) {
  var obj;
  // Convert WKT escaped quote to JSON escaped quote
  str = str.replace(/""/g, '\\"');

  // Convert WKT entities to JSON arrays
  str = str.replace(/([A-Z0-9]+)\[/g, '["$1",');

  // Enclose axis keywords in quotes to create valid JSON strings
  str = str.replace(/, *([a-zA-Z]+) *(?=[,\]])/g, ',"$1"');

  // str = str.replace(/[^\]]*$/, ''); // esri .prj string may have extra stuff appended

  // WKT may have a "VERTCS" section after "PROJCS" section; enclosing contents
  //   in brackets to create valid JSON array.
  str = '[' + str + ']';

  try {
    obj = JSON.parse(str);
  } catch(e) {
    wkt_error('unparsable WKT format');
  }
  return obj;
}```

It appears that the string being parsed (at obj = JSON.parse(str); ) is not a valid JSON string.

We have low knowledge and understanding of the WKT format so hard for us to figure out what can be wrong here.

Worth noting is that the .prj file is properly read in QGIS and other tools we have tested (e.g. DotSpatial, a c# library), so I guess the format is correct but not properly parsed in mapshaper.

Do you have any idea what the issue could be?

**Comment by mbloch** [comment]
Hi, thanks for reporting this. Could you send a complete `.prj` file for me to test? If your data is not sensitive, it would be even more useful to have the whole Shapefile. Thanks!

**Comment by jaltin** [comment]
Hi,

Yes, have a look at this shapefile. 

[Anmarkningar.zip](https://github.com/mbloch/mapshaper/files/7686226/Anmarkningar.zip)

Let me know if I can help further.

**Comment by mbloch** [comment]
Thanks for the file, I'll look into this as soon as I have a bit of time.

**Comment by mbloch** [comment]
I think I've fixed the WKT parsing bug (the parser was tripping on the empty string `""`). You can try installing version `0.5.78`.

**Comment by jaltin** [comment]
I tested 0.5.78 on a few of the failing files and it seems to work well. Thanks a lot for such a quick fix!
