### ISSUE TITLE
Remove Holes from (Multi-) Polygons

### ISSUE THREAD

**Issue by indus** [mbloch/mapshaper#524]
Is there a way to remove holes from Polygons and Multipoligons?

**Comment by mbloch** [comment]
You can do `-drop holes` to remove holes.

Be aware that this will lead to overlapping polygons if you have a polygon ring that is contained within another polygon.

**Comment by indus** [comment]
Thanks for the fast responseAm 18.01.2022 13:02 schrieb Matthew Bloch ***@***.***>:
You can do -drop holes to remove holes.
Be aware that this will lead to overlapping polygons if you have a polygon ring that is contained within another polygon.
