### ISSUE TITLE
 UserError: [i] No files matched (shapefiles/*.shp)

### ISSUE THREAD

**Issue by zxpzxp** [mbloch/mapshaper#525]
![1642574306](https://user-images.githubusercontent.com/21053019/150077744-b26d3359-798e-4851-9035-307829ad5538.jpg)
![1642574306(1)](https://user-images.githubusercontent.com/21053019/150077757-375b9120-fde9-435c-83f5-e0d537c6b6f3.jpg)

I want to import files  through code, but an error is reported, how to solve it? Is the path I introduced wrong?

**Comment by mbloch** [comment]
Your `-i shapefiles/*.shp` command doesn't work because web browsers can't read files directly from the filesystem (as far as I know). The mapshaper web app is only able to read files that have been dragged onto the browser window or selected via the browser's file selection dialog.

**Comment by zxpzxp** [comment]
If so, how to use mapshaper programmatically, how to get file resources？
