### ISSUE TITLE
Polar stereographic projection

### ISSUE THREAD

**Issue by chris3522** [mbloch/mapshaper#526]
Hello,
I would like to create a 1536 by 1536 dot grid with stereographic projection. The characters of the grid are:
NAME;LAT;LON;
"NW Point";53.670;-9.965;
"SW Point";39.856;-6.971;
"SE Point";39.465;10.307;
"NE Point";53.060;14.646;

Is there a way to do this after importing these four points into mapshasper?
Regards

**Comment by criloach** [comment]
I finally reconstructed a point-by-point grid using a proj lib which is more suitable in this case.
