### ISSUE TITLE
Spatial Join not resulting in same outputs as ArcGIS Arcpy module

### ISSUE THREAD

**Issue by ParkerJohnsonUF** [mbloch/mapshaper#532]
Hello

### Context:

In my organization, we have used GIS and Arcpy to perform spatial processing for a long time. While it works, it is incredibly slow. Due to this, if something is wrong with the outputs, it will take multiple hours (or sometimes an entire work day) to re-run the program and get the correct results. We looked to mapshaper as an alternative to our arcpy processing because of the speed, feedback in the terminal, and simplicity of mapshaper programming. However, we have recently found that the outputs from our mapshaper code are different than the outputs from our arcpy code; and these outputs  make it to where we cannot reliably use the mapshaper code for our work. The speed is a great benefit, but if the outputs are incorrect we ultimately cannot use it as an alternative.

### Issue:

The main issue lies in the difference in the outputs from the arcpy spatial join and the spatial join options in mapshaper. Mapshaper has a few different spatial join methods (standard, point-method, and largest-overlap) but they all result in the same issues. What we have found is that when we do a spatial join of a parcel shapefile (many small polygons) to a subdivision shapefile (many larger polygons) and the subdivision polygons that we want to capture data from are adjacent to each other, the output is not correct. It seems that when two subdivision polygons are adjacent, the spatial join does not completely capture all of the parcels within their correct subdivisions, and some parcels are "pushed" into the adjacent polygon instead of the polygon where they should be captured. In my example pictures below we used the standard spatial-join option from mapshaper. For arcpy, we used the following parameters for the spatial join: 

arcpy.SpatialJoin_analysis(target_features=PATH + CNTY+"_PARCELS.shp", join_features=PATH + CNTY+"_SUBS.shp",
                           out_feature_class=PATH + CNTY+"_PARCELS_SUBS.shp", join_operation="JOIN_ONE_TO_ONE",
                           join_type="KEEP_ALL", match_option="HAVE_THEIR_CENTER_IN", search_radius="",
                           distance_field_name="")

For Mapshaper, we use the following join option:

print("Calling mapshaper to join subdivisions layer to parcels layer")
do_cmd(ms_cmd + ' -i ' + path + CNTY+'_parcels1.shp -join ' + path + CNTY+'_subs3.shp -o '+ path + 'parcels_subs.shp')

We join the subdivisions polygons to the parcels polygons in order to capture which subdivision any given parcel belongs to. We do this using the match_option "HAVE_THEIR_CENTER_IN". Below I will attach mapped results of both the arcpy outputs (which are correct) and the mapshaper -join outputs (which have errors). If there is a way to properly do this which I do not know about, I would be happy to implement some edits in our code. 

**County 1 Example**

Arcpy Result: 
![Osceola_Arcpy_Example](https://user-images.githubusercontent.com/60367856/156442392-a3992d41-ece2-424d-bd02-f7e9c99020a8.PNG)

Mapshaper Result (errors):
![Osceola_Mapshaper_Example](https://user-images.githubusercontent.com/60367856/156442490-23573c08-a070-4ee7-8543-a115e38d1173.PNG)

**County 2 Examples**

Example 1 Arcpy Result:

![Polk_Arcpy_Example1](https://user-images.githubusercontent.com/60367856/156442705-efae5510-ac06-4adb-bb61-668c28cda605.PNG)

Example 1 Mapshaper Result (errors):

![Polk_Mapshaper_Example1](https://user-images.githubusercontent.com/60367856/156442854-b1283150-2220-477c-a818-81fcd9b64e98.PNG)

Example 2 Arcpy Result:

![Polk_Arcpy_Example2](https://user-images.githubusercontent.com/60367856/156442907-5ef7dfa9-096e-42bc-9de7-f5490ab4fe39.PNG)

Example 2 Mapshaper Result (errors):

![Polk_Mapshaper_Example2](https://user-images.githubusercontent.com/60367856/156443006-ae7c7fbd-0dd8-418c-8064-252376b81b59.PNG)

I hope that these screenshots provide a clear example of the "pushing" effect that I mentioned previously. I will also attach the example shapefiles below so they may be inspected within mapping software/programming. I look forward to hearing any suggestions or responses. Thank you.

[Cnty1_Ex_Arcpy.zip](https://github.com/mbloch/mapshaper/files/8172824/Cnty1_Ex_Arcpy.zip)
[Cnty1_Ex_MShpr.zip](https://github.com/mbloch/mapshaper/files/8172825/Cnty1_Ex_MShpr.zip)
[Cnty2_Ex1_Arcpy.zip](https://github.com/mbloch/mapshaper/files/8172826/Cnty2_Ex1_Arcpy.zip)
[Cnty2_Ex1_MShpr.zip](https://github.com/mbloch/mapshaper/files/8172827/Cnty2_Ex1_MShpr.zip)
[Cnty2_Ex2_Arcpy.zip](https://github.com/mbloch/mapshaper/files/8172828/Cnty2_Ex2_Arcpy.zip)
[Cnty2_Ex2_Mshpr.zip](https://github.com/mbloch/mapshaper/files/8172829/Cnty2_Ex2_Mshpr.zip)

**Comment by mbloch** [comment]
Hi! thanks for filing this. I'd like to investigate, but I'll need to have the input files (the original subdivision and parcel polygon files). Can you send those as well?

**Comment by ParkerJohnsonUF** [comment]
Sure! The first county examples are from Osceola County, FL and the second county (both examples) are from Polk County, FL. Attached below.

Osceola County Input File (We derive both the parcel polygons and the subdivision polygons from the same shapefile):
It seems like the file is too large or something else is preventing me from attaching the file directly (I am new to posting on Git), so I will provide a link to the download page for the shapefile.

[https://data-ocpagis.opendata.arcgis.com/datasets/osceolataxparcels03012022/explore?location=27.994541%2C-81.259744%2C10.70](url)


Polk County Input Files (Separate parcel and subdivision shapefiles):
The same attachment issue is happening with the parcel shapefile (it is quite large even compressed) so provided is a link:

Download the parcel.zip
[https://www.polkpa.org/FTPPage/ftpdefault.aspx?url=\GISData](url)

[subdiv.zip](https://github.com/mbloch/mapshaper/files/8173074/subdiv.zip)

Thank you!

**Comment by mbloch** [comment]
Hi! Sorry I didn't get back to you earlier on this -- busy at work. I found that both `point-method` and `largest-overlap` worked correctly (see the attached screengrab). Make sure to add these flags after the `-join` command in your command line. Also, to join a data field when the field already exists in the target layer requires the `force` flag -- that's one reason the `point-method` and `largest-overlap` flags might not seem to work if you're testing joins in the browser interface (i should add a warning message about that)
<img width="729" alt="image" src="https://user-images.githubusercontent.com/1232222/158553864-eb5ed945-0980-4d94-987c-f4b731a72218.png">
The console commands to produce the above image:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/1232222/158554276-059e58e5-45cd-409b-9e2e-7abc6d606b84.png">

**Comment by mbloch** [comment]
In the newly-published v0.5.97, I added a warning if some fields are blocked from joining by same-named fields in the target layer. (I'm not sure if this is the reason `largest-overlap` and `point-method` didn't work for you, but it's a possible cause of confusion). 

I think that the reason for the strange joins that you reported is that the boundaries in the two layers are not perfectly aligned. There are tiny overlaps between certain subdivisions and parcels that should have been assigned to a different subdivision. Mapshaper's default behavior when there are multiple overlapping polygons is to join data from the first overlapping polygon, not the best-fit polygon. Maybe I should rethink this...

**Comment by ParkerJohnsonUF** [comment]
Thanks so much for the response and insight! Our program greatly
appreciates your work and contribution to the open-source community.

Parker Johnson

Data Management Analyst

Program for Resource Efficient Communities/H2OSAV

University of Florida

(352)392-7126



[image: image.png]
