### ISSUE TITLE
`breaks=` with `null-value=` fails with only null values

### ISSUE THREAD

**Issue by jkeefe** [mbloch/mapshaper#534]
Looks like the latest updates to the `-classify` option may have broken a line I've been using reliably until now:

```
-classify pct_out colors=Magma invert breaks=10,20,30,40,50,60,70,80,90 null-value='#f8f8f8' \
```

In cases where `pct_out` contains only null values, mapshaper now errors with `[classify] Error: Missing a data field and/or classification method`

That looks like it's being thrown in [mapshaper-classify-methods.js](https://github.com/mbloch/mapshaper/blob/69c950185156d2e9634fbe4db769715e18bd9cdb/src/classification/mapshaper-classify-methods.js)

Let me know if you need any other information! (Or if I'm doing something wrong.)

**Comment by mbloch** [comment]
Thanks for reporting this! The error you got is a consequence of some recent changes, intended to do a better job of validating parameters and setting defaults based on the data type of the field you're classifying. I hadn't considered the case of all null values. I'll fix that.

**Comment by mbloch** [comment]
I think I fixed this in the latest release. If you find any other bugs or unexpected behavior, please report them.

It sounds like you're using mapshaper as part of a data processing pipeline, in which the input files may be inconsistent in various ways. I recently added `-if/-elif/-else/-endif` commands to help with inconsistent input data. See: https://github.com/mbloch/mapshaper/wiki/Command-Reference#control-flow-commands

In your case, if I hadn't fixed the bug, you could do something like:
```
-if 'field_type("pct_out") === null' \
  -style fill="#f8f8f8" \
-else \
  -classify pct_out colors=Magma invert breaks=10,20,30,40,50,60,70,80,90 null-value='#f8f8f8' \
-endif
```
