### ISSUE TITLE
GeoJSON after import/export contains overlapping polygons

### ISSUE THREAD

**Issue by Girilloid** [mbloch/mapshaper#538]
Hi,
We are using mapshaper as a library for our web application. Recently we found an issue with GeoJSONs that are imported to mapshaper and then exported from it (it involves cleaning of layers, but issue is here even if we don't not apply any operation on dataset). After this simple operation GeoJSON becomes invalid for as, i.e. it has overlapping polygons.

Here is an input file: https://pastebin.com/b0vXwTxY
Output file after import/export: https://pastebin.com/hgrFmDCD

Also attaching some screenshots that can show the issue. First screenshot shows just a rendered GeoJSON, on the second there is a polygon selected to see if there are any overlapping polygons.

Source GeoJSON:

![image](https://user-images.githubusercontent.com/38287337/161425427-dbfda028-d508-44b1-9d34-c781f507e610.png)
![image](https://user-images.githubusercontent.com/38287337/161424974-a3fb0f3d-a97e-4eb8-98c6-0a3e0053a0cc.png)

Output GeoJSON:

![image](https://user-images.githubusercontent.com/38287337/161425440-9958a121-9733-4738-8f40-32da45ba60d7.png)
![image](https://user-images.githubusercontent.com/38287337/161424983-fbb6e7c2-8cd0-45a9-98d8-9f94809b3cc2.png)

Much appreciated for all the help and your time.

**Comment by mbloch** [comment]
Thanks for reporting this, @Girilloid ... I can see the problem... let me try to find a solution.

**Comment by mbloch** [comment]
This should be fixed now, in the latest release (v0.5.108)

**Comment by Girilloid** [comment]
Great. Thanks for quick answer and fix. Works as expected
