### ISSUE TITLE
Trying to Export Points and Shape File to SVG

### ISSUE THREAD

**Issue by stevenrothe** [mbloch/mapshaper#545]
Hi.  I'm trying to export a shape file map along with points that were imported from a .csv file but the points don't show up when the .svg file is opened in Adobe Illustrator.  Do you have any idea why?  Please let me know - thanks.

**Comment by mbloch** [comment]
There is a way... you can convert the points to circles by giving them a radius, like this: 
```
-style r=1
```
("r" is the SVG property for circle radius).

**Comment by stevenrothe** [comment]
Thank you so much - it worked.  Also, thank you for this excellent and free tool and the speedy response.  I'm also a UW-Madison alumni.  I'm a novice when it comes to GIS and cartography but will send you the end product(s) when they are finished (a long time from now).
