### ISSUE TITLE
fyi: 404 link in readme + fix

### ISSUE THREAD

**Issue by FrissAnalytics** [mbloch/mapshaper#547]
Hi Matthew,

hope your doing well! incredible tool! 

fyi: one of the links in the readme User-contributed resources gives a 404, it's the ref to Jack Dougherty.

This gives a 404:

https://datavizforall.org/convert-edit-join-and-dissolve-with-mapshaper-org.html

I'm guessing it now should be this one:

https://handsondataviz.org/mapshaper.html

kind regards, Herman

**Comment by mbloch** [comment]
Thanks for reporting this... fixed now.
