### ISSUE TITLE
 加载 geojson 文件失败 Failed to load geojson file

### ISSUE THREAD

**Issue by lengjiaxin** [mbloch/mapshaper#551]
![image](https://user-images.githubusercontent.com/11784736/175855256-faeccdd2-0f46-45a9-a86d-54a2dc750b7e.png)
![image](https://user-images.githubusercontent.com/11784736/175855291-5779e1ea-6a37-4b99-b39e-dcbf0850544f.png)

**Comment by lengjiaxin** [comment]
[Export_Output_Project1.zip](https://github.com/mbloch/mapshaper/files/8988511/Export_Output_Project1.zip)
geoJson file

**Comment by mbloch** [comment]
It looks like you are trying to use mapshaper in your own application, is that right? In addition to `mapshaper.js`, you would also need to load `modules.js` (see https://mapshaper.org/modules.js). Flatbush is one of the modules contained in that file.

**Comment by lengjiaxin** [comment]
Yes, I load the geojson file on the web page and ask how to reference modules js

thank you。

![image](https://user-images.githubusercontent.com/11784736/175861050-93a4b317-fc6a-47e0-ad68-9e6456a35218.png)

**Comment by lengjiaxin** [comment]
If The SHP file uses a projection coordinate system. How can it be correctly parsed into geojson and rendered to a web page?



At present, my side tests The SHP file uses the longitude and latitude coordinate system and can be normally parsed and displayed on the page as geojson.

**Comment by mbloch** [comment]
Sorry I didn't reply sooner! I'm only supporting mapshaper as an end-user program, I don't have time to help developers with their projects.
