### ISSUE TITLE
GeoJSON point geometry -> SVG circles doesnt write r attribute

### ISSUE THREAD

**Issue by jendahorak** [mbloch/mapshaper#553]
# Used command
mapshaper .\utoky_dates.geojson -o .\svg\utoky_data_dates_r.svg format=svg force id-field=fid svg-data=date_s

# SVG output
```
<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.2" baseProfile="tiny" width="800" height="425" viewBox="0 0 800 425" stroke-linecap="round" stroke-linejoin="round">
<g id="utoky_dates">
<circle cx="516.6374" cy="377.838" id="1" data-date_s="1939-10-28"/>
<circle cx="507.9389" cy="368.6373" id="2" data-date_s="1939-10-28"/>
<circle cx="515.023" cy="354.3827" id="3" data-date_s="1939-10-28"/>
<circle cx="699.9922" cy="296.2535" id="4" data-date_s="1942-06-25"/>
<circle cx="66.1749" cy="205.2282" id="5" data-date_s="1943-08-05"/>
<circle cx="93.1114" cy="172.6849" id="6" data-date_s="1943-08-08"/>
```

Is this expected behavior and I am missing something or is it a bug?

**Comment by jendahorak** [comment]
Weird fix:
I have re-exported (from QGIS) the input geojson and now the same mapshaper command as used above, writes svg circles with r attribute correctly.

Therefore I apologize  for maybe a useless Issue ticket.

**Comment by mbloch** [comment]
Typically you would use the `-style` command to add an `r` attribute to each point feature, like this: `-style r=5`. The `-style` command just adds style attributes to each feature's set of data properties, so you could also do `-each 'r=5'`.
