### ISSUE TITLE
is there a way to rename split files with an expression?

### ISSUE THREAD

**Issue by chris3522** [mbloch/mapshaper#554]
Hello, 

I run this command 
`points.json name -split field=idsegment -o ./tmp/BV/ format=geojson`
It works perfecty and I get multiples files in /tmp/BV/ folder.
For idsegment=005_002 , I get a 005_002.json file

I'd like custom files names like this : 
BV_005_002.json
or add another propertie to the name like this:
If a polygone has another field idtroncon=750
I get 750_BV_005_002.json

How to proceed ?

Many thanks

**Comment by mbloch** [comment]
You can create a new property containing the names you want and split on that. For example:
```
-each 'splitname = "BV_" + idsegment' \
-each 'splitname = d.idtroncon ? d.idtroncon +  "_" + splitname : splitname' \
-split splitname \
-drop fields=splitname
```
(untested)

**Comment by chris3522** [comment]
Great and so cool! 

Another question if you allow me. I made a program to do the following but maybe it can be done on the command line in a more elegant way, here's the problem:
I have several polygons with properties idtroncon and idsegment. An idtroncon contains several idsegment. How to add an index property that counts the idsegement (by alphanum order) for the same idtroncon.
idtroncon = 750 is in polygons idsegment=005_002 and idsegment=005_003
I would like to add an index property to the two polygons index=1 and index=2.
