### ISSUE TITLE
maps are stretched and not correctly scaled 

### ISSUE THREAD

**Issue by brighella012** [mbloch/mapshaper#556]
Hi, I'm using react-simple-maps in a React project. The project uses topojson files done in 2018. Everything works.
Now, when I convert the new maps from shp to topojson, I can't scale it correctly and I see them stretched.
But this happens only with the new maps.
Do you have any advice? Something changed from 2018 in way of maps to work?
Thank you

**Comment by mbloch** [comment]
Hi! Can you send me samples of the 2018 topojson and the new topojson files? I can compare them and see what might be different.

**Comment by brighella012** [comment]
Hi Matthew, thank you very much for answering me!
Attached you can find 2 zip:
mapdata-2018 and mapdata-2022.

In each folder you have 6 maps.
The 6 maps are divided in two zoomable groups:
- first zoomable group uses the 3 maps with the name "camera"
- the other group uses the 3 maps with the name "senato"

My problem is about the values of "scale" and "translate" under "transform".
As you can see, the 2018 maps has value of scale very little:

0.0006xxx

While the new maps have value as:


25.35xxx

So much bigger.
I saw how to scale though console on mapshaper but I did by putting number by hazard.
And as the maps are 3 and they have to be positioned perfectly one above the other, I can't do in this way.
So, don't know exactly how to do.

**Comment by mbloch** [comment]
I didn't find the sample files attached to this comment... I'm happy to look into this issue if I can get my hands on the data files.
