### ISSUE TITLE
Set central meridian of the Winkel Tripel projection

### ISSUE THREAD

**Issue by matkoniecz** [mbloch/mapshaper#560]
Is it possible to set central meridian of Winkel Tripel projection?

**Comment by mbloch** [comment]
You can do this using proj-string notation ([link](https://proj.org/usage/quickstart.html)). For example:
```
-proj +proj=wintri +lon_0=150
```
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/1232222/206567506-a0d12163-755a-483e-9083-5cb1a75bcfd3.png">
