### ISSUE TITLE
SVG export not including full relations

### ISSUE THREAD

**Issue by booonen** [mbloch/mapshaper#563]
Trying to export .geojson multipolygons (polygon features) into SVG through Mapshaper - previously (some amount of months ago) this worked flawlessly, but trying this now results in several shapes being lost.

See below a screenshot from mapshaper, with one of the multipolygon relations selected: 
![image](https://user-images.githubusercontent.com/64190340/200333155-9c5eaa22-8e92-4840-9cfa-a6e98d02a063.png)
As you can see, this relation is divided into two large parts. Previously, these relations would be exported into SVG as a grouped object, with the name being "relation/[id]" - upon exporting to SVG now, this is the result:

![image](https://user-images.githubusercontent.com/64190340/200333819-9ed2d948-36d4-4226-b075-d604cdf95c7b.png)

The top half of the relation disappeared; and does no longer exist in the SVG. Consistently in my export, each relation with multiple areas - whether it be islands or exclaves, has one of these areas exported, and the rest ignored. The exception turns out to be areas consisting of only one line which are (seperately) exported no matter what.

Though I'm uncertain whether or not the new approach to exporting these relations into SVG (as seperate objects instead of grouped) is intended behaviour (it would add a little extra manual work to my use-case if so, but not the end of the world), I doubt the non-exportation of these split relations is intentional.

Can provide example file if needed.

**Comment by mbloch** [comment]
Hi @booonen ... sorry for the slow follow-up... can you give me an example file, to help me reproduce this? Thanks :)

**Comment by mbloch** [comment]
I wasn't able to reproduce this problem in my own tests. There may be something particular to this one dataset that is triggering the problem. If I can find a sample file that exhibits this behavior, then I'll reopen this issue.
