### ISSUE TITLE
-o overrides chrome download settings

### ISSUE THREAD

**Issue by tcerman** [mbloch/mapshaper#568]
Hello,
-o in v0.6.16 probably overrides Chrome download settings,
saving output now asks for user-selected directory all the time, even though it's set otherwise in browser settings
(this issue doesn't show up in Firefox)
Toc

**Comment by tcerman** [comment]
Hi,
I meant it causes problems just in Chrome, even when the browser settings are set otherwise, the -o somehow overrides it and prompts anyway. 
It works fine with Firefox, though, I can turn it on and off, and it behaves as it should. I personally prefer the old behavior.

![Screenshot 2023-01-04 083832](https://user-images.githubusercontent.com/121879839/210506279-fbd209ec-b226-4078-8672-87e4df7a686a.jpg)

**Comment by mbloch** [comment]
I added a checkbox to the export menu that lets you choose between the old behavior (the default) and having the browser prompt you where to save your output. If you prefer the old behavior, I think that you'll approve of this change.

**Comment by tcerman** [comment]
Awesome, it works.
Thank you!
