### ISSUE TITLE
After last update I can no longer import shapefiles

### ISSUE THREAD

**Issue by jorq1h** [mbloch/mapshaper#570]
I've been using mapshaper to simplify regions created by ISW (International Study of War) showing different areas in Ukraine.

However, after the last update, I first get the error message "Shapefile Z data will be lost." when importing the same shapefiles as before, so I press OK. After that, the viewport is blank and I can't use any of the functionality.

Problem on both Chrome and Firefox, windows 10.

I can DM the shapefiles if necessary.

**Comment by jorq1h** [comment]
Update: 

Unpacking the zip and working on shp-files directly works fine. Same with doing this from a terminal (however I've always preferred doing this operation on your website for live feedback of the simplify value).

**Comment by jorq1h** [comment]
Update:

Unpacking the zip and working on shp-files directly works fine. Same with doing this from a terminal (however I've always preferred doing this operation on your website for live feedback of the simplify value).

**Comment by mbloch** [comment]
Hi, thanks for the feedback! I'm working on a fix. This problem is occurring because I switched to a new library for zipping/unzipping, which doesn't automatically convert the code page file (.cpg) to a string.

**Comment by jorq1h** [comment]
Thank you, now it works like a charm!
