### ISSUE TITLE
stdin input via pipe stopped working

### ISSUE THREAD

**Issue by pavel-411** [mbloch/mapshaper#583]
with version 0.6.16 stopped working input via stdin when using via pipeline, e.g.:
cat inputfile.csv | mapshaper -i - -o outputfile.tsv format=tsv
script above runs correctly on version 0.6.15, with newer version shows error "no data is available"
running on Debian 10, using "-i /dev/stdin" instead of "-i -"  doesn't help

**Comment by mbloch** [comment]
Thanks for reporting this! It should be fixed in v0.6.28

**Comment by pavel-411** [comment]
thanks a lot, it works now
