### ISSUE TITLE
Exporting Maps Colored using Classify to ArcGIS, Power BI, etc. 

### ISSUE THREAD

**Issue by bonnjorr** [mbloch/mapshaper#585]
@mbloch 

Hello again sir! Do you have any advice on how to export a map colored using classify? I tried to upload my map to ArcGIS and Power BI, but neither recognized the colors once uploaded. Any suggestions would be welcome. Also, I couldn't figure out how to make the lines with the colored map show ups. So it was somewhat difficult to see where the different polygons began and and ended. 

![image](https://github.com/mbloch/mapshaper/assets/108496186/ac0e4352-1db4-4e6f-9c77-4360b95c2f34)

**Comment by mbloch** [comment]
Hi, within Mapshaper, you can make the lines show up by adding a stroke color and stroke width to the polygons. An example command is: `-style stroke=black stroke-width=1.5`.  You can see all the style options with `mapshaper -h style`.

In Mapshaper's GeoJSON output, style properties are stored as data properties with names like `fill`, `stroke`, `fill-opacity`, etc. You'll have to read the PowerBI and ArcGIS documentation to find out if those platforms are able to import styles from GeoJSON properties. A quick web search didn't turn up a simple way to do this... maybe you'll have better luck than me.
