### ISSUE TITLE
Clip not working with small gaps

### ISSUE THREAD

**Issue by manuel-hegner** [mbloch/mapshaper#595]
It seams that clipping is removing small gaps within the clipping layer. I have attached an example where one can see the problem around `-0.06,36`.

The command executed was `-clip clipper target=clipped`. 
[geo.zip](https://github.com/mbloch/mapshaper/files/12081610/geo.zip)

An image of the situation after clipping. The green lines are an inner loop within the clipping polygon layer while the black lines are the Polyline layer that is supposed to be clipped.
![image](https://github.com/mbloch/mapshaper/assets/12272732/6cbd895c-a8eb-4a72-ab06-cb021253fb8b)

**Comment by mbloch** [comment]
Thanks for the bug report! I replicated the problem... I'll work on a fix as soon as I have time, probably in the next few days.

**Comment by mbloch** [comment]
I believe this is fixed in the latest release, v0.6.35.

**Comment by mbloch** [comment]
![image](https://github.com/mbloch/mapshaper/assets/1232222/c04c01b3-8fd0-4ffa-9d91-657da52aed98)
