### ISSUE TITLE
The -i command cannot be run in the browser

### ISSUE THREAD

**Issue by lautarodapin-magoya** [mbloch/mapshaper#612]
I'm getting this error `UserError: [i] The -i command cannot be run in the browser` when trying to use mapshaper in the browser

![image](https://github.com/mbloch/mapshaper/assets/84460589/eb42ed41-ba61-4940-ab8b-bdfcd1df4040)

I have the scriipts  `modules.js` and `mapshaper.js` present, the an input to read the shapefile, then i call the following code

```ts
  const toGeojson = (e: any) => {
        const files = [...e.target.files];
        const input = files.reduce((acc, curr) => {
            acc[curr.name] = curr;
            return acc;
        }, {});
        const cmd = `${files.map((file) => `-i ${file.name}`).join(' ')} -o  format=geojson`;
        mapshaper.applyCommands(cmd, input, (err, output) => {
            console.log(err);
            console.log(output);
        });
    };
```
#601  #407 i checked this two issues but i couldnt solve it

**Comment by lautarodapin-magoya** [comment]
I change the code because ii read the the input filies must be a arraybuffer to
but i get the same error
```tsx
 const files = [...e.target.files];
        const buffers = await Promise.all(files.map((file) => fileRead(file)));
        const input = files.reduce((acc, curr, i) => {
            acc[curr.name] = buffers[i];
            return acc;
        }, {});
        const names = files.map((file) => file.name).join(' -i ');
        const cmd = `${files.map((file) => `-i ${file.name}`).join(' ')} -o  format=geojson`;
        console.log({cmd, input});
        // mapshaper.runCommands(`${files.map((file) => `-i ${file.name}`).join(' ')} -o geojson.json format=geojson`);
        mapshaper.applyCommands(cmd, input, (err, output) => {
            console.log(err);
            console.log(output);
        });

**Comment by mbloch** [comment]
I see... you want to use the JS api in a web browser. The `-i` command doesn't work in the console of the mapshaper web UI, which is why I added the error message that you're seeing. I'll try to get this fixed for you in the next release. Thanks for filing this issue :)

**Comment by lautarodapin-magoya** [comment]
thanks for the fast response! @mbloch how the https://mapshaper.org/ works? i try to search in the source code how it does it, but i couldn't solve it

**Comment by mbloch** [comment]
Hi, I think that I fixed the problem that you were having using  `applyCommands` in the browser.

https://mapshaper.org just serves a static web page, it's the same page as `index.html` in the `www/` folder of the github repo. Mapshaper will mostly work if you open the `index.html` file in a web browser.
