### ISSUE TITLE
Error: require ESM modules with relative paths 

### ISSUE THREAD

**Issue by indus** [mbloch/mapshaper#613]
I've just updated to the latest version and I faced problems using `require` on a local script.

```mapshaper -require "./myESM.mjs"```
```mapshaper -require "./myCommon.js"```

both result in an Error: `Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'`

only the following works:
`mapshaper -require "file:///C:/myProj/myESM.mjs"`
`mapshaper -require "file:///C:/myProj/myCommon.js"`

I think the problem is here https://github.com/mbloch/mapshaper/blob/master/src/commands/mapshaper-require.mjs#L24
It changes the relative to an absolute path but misses to add the required `file:///`

I'm working on Windows (in case that makes a difference). I've testet Node 18 and 20 LTS

**Comment by indus** [comment]
I've just noticed that thet even with an valid absolute path to my script I get errors:

with the script **poly.mjs**
``` JS
export const polygon = function () {
    return {
        type: "FeatureCollection",
        features: [{
            type: "Feature",
            geometry: { type: "Point", coordinates: [125.6, 10.1] },
            properties: { name: "Dinagat Islands" }
        }]
    }
}
```

``` powershell
mapshaper `
-rectangle bbox="-180,-90,180,90" `
-require "file:///C:/myProj/poly.mjs" `
-run "target.geojson = polygon()"
```
>  Error: [i] File not found (target.geojson)

``` powershell
mapshaper `
-rectangle bbox="-180,-90,180,90" `
-require "file:///C:/myProj/poly.mjs" `
-run "polygon()"
```
> Error: [i] File not found (polygon())

**Comment by mbloch** [comment]
I haven't been able to reproduce the `Unable to load external module` error yet... I tested with mapshaper `0.6.58` on Windows 11 (running in Parallels) using both Node 18 and Node 20 in `cmd.exe`. `-require` works in `0.6.58` and throws the error you first reported in `0.6.57`. Here's a screengrab: 
![image](https://github.com/mbloch/mapshaper/assets/1232222/3bcd903f-68ea-4322-a7f2-52977143ab3e)

Do you have any ideas that might help me reproduce this? Are you using a different shell than `cmd.exe`?

**Comment by mbloch** [comment]
`-require` works in powershell too, in my current setup: 
![image](https://github.com/mbloch/mapshaper/assets/1232222/7693aa0b-1155-4479-94ea-12a0f9bae86f)

**Comment by indus** [comment]
I'm glad you were able to find something positive in it.
But I would prefer to close the issue in shame 😄
