### ISSUE TITLE
Filter lines still create polygons

### ISSUE THREAD

**Issue by atavoidturk** [mbloch/mapshaper#626]
after using -filter on a polyline layer, using -polygons still uses the filtered lines to create polygons

**Comment by atavoidturk** [comment]
this occurs if a layer with the same source is present, which makes it impossible to remove the light blue lines

**Comment by mbloch** [comment]
I see... yes... if another layer is still using the paths that show up as light blue lines, then `-clean` will not remove the lines, that is how mapshaper currently works. If you deleted the other layer and then ran `-clean`, the lines would disappear.

I added the blue lines a long time ago, as a way to see which paths are removed when flitering and dissolving. I've considered removing this feature, it's not essential. 

Meanwhile, there's another way to hide the blue lines, that is to add a style to the layer, for example, by running the command `-style stroke=black`. When you do this, mapshaper switches to a preview view, which shows the layer as it would appear in a map. 

Screenshot: "clean" command doesn't remove blue lines when source layer is still present
![image](https://github.com/mbloch/mapshaper/assets/1232222/6c853bc5-6445-43db-b09d-23841e5958ee)

Screenshot 2: using the "style" command to suppress the blue lines.
![image](https://github.com/mbloch/mapshaper/assets/1232222/fd7743bc-9130-467a-9988-61fcfc5e36a0)

**Comment by atavoidturk** [comment]
-mosaic also creates polygons using filtered lines, and the creation of incorrect polygons persists after -style

**Comment by mbloch** [comment]
noted, thanks

**Comment by mbloch** [comment]
The issues with -polygon and -mosaic are fixed in v0.6.70
