### ISSUE TITLE
Point layers and data layers do not show up

### ISSUE THREAD

**Issue by atavoidturk** [mbloch/mapshaper#628]
When selecting a point/data layer, the map goes blank and the label at the top remains the same as the last non-point/data layer accessed. If there are only point/data layers, then the label will be blank. attempting to use -points on a broken data layer directly caused the console to break and refuse input, so did using the target= option for -points. Doing 
-points target=DataLayer -target PolygonLayer worked though. 
on the Web Version

**Comment by atavoidturk** [comment]
doing -points vertices on a polygon layer shows the point layer initially, but freezes the console. After selecting another layer, going back to the point layer no longer works.

**Comment by mbloch** [comment]
This should be fixed now, thanks
