### ISSUE TITLE
Cannot convert between WGS84 and Webmercator after converting and saving data as EPSG:3857.

### ISSUE THREAD

**Issue by NMC92** [mbloch/mapshaper#630]
Hi. As the title says, once you convert the projection from EPSG:4326 to EPSG:3857, export the data and refresh the browser you lose the ability of converting the same data back to EPSG:4326 and see this error on the console: "[proj] Unable to project -- source coordinate system is unknown", even though it was Mapshaper projecting the data. Shouldn't there be some way for Mapshaper to recognize the projections it does, perhaps like a CRS property or similar?
Thank you.

(Additionally - This doesn't happen if the original file you uploaded was EPSG:4326 to begin with, meaning that then you can go back and forth as many times as you want)

**Comment by mbloch** [comment]
It sounds like you're saving your data as GeoJSON, yes? In 2016, a standards committee removed the `crs` property from GeoJSON and decided that GeoJSON should only use EPSG:4326 coordinates. Mapshaper lets 
you export non-EPSG:4326, but as you pointed out, the CRS information does not get saved.

If you want to use mapshaper to import GeoJSON that uses EPSG:3857 coordinates, you can use the `-proj` command to tell mapshaper what CRS to use, like this:
```
mapshaper webmercator_data.geojson -proj init=EPSG:3857 ...
```

I'm not inclined to add a non-standard CRS property to mapshaper's output, if you really need to include CRS info with the file, then you can export as Shapefile or you can export to mapshaper's "snapshot" format, by saving to a file with the `.msx` suffix.

**Comment by NMC92** [comment]
I understand, thanks for telling me. EPSG:4326 being the standard projection explains a lot of things.
And yes, I mean a GEOJSON. I was mostly just trying to understand why things are the way they are. Thank you!

As a last thing, is there any way to run this batch of commands on the console version of mapshaper? What I'm trying do achieve here is to get rid of polyline and points layers(since exporting data on overpass-turbo.eu is giving me additional stuff other than polygons) and clip to the country layer(I have to reimport the country geojson svg since I can't clip to a specific polygon, in order to get only the country's polygons, without surrounding fluff). Thank you!

Batch:
mapshaper import.geojson
drop (points layer)
drop target=2 (possible polylayer layer)
rename-layers target=1 names=country (layer to clip to, later)
filter 'tags.admin_level == 2' (get country polygon)
mapshaper import.geojson (duplicate layer, with all of country's polygons and possible extra surrounding polygons to get rid of with clip)
drop (remove points layer)
drop target=3 (remove possible polyline layer)
target 2 (set country's polygons' layer as active)
clip country
drop target=country (now that we have only our country's polygons we can get rid of the country polygon layer)
proj webmercator (do the projection conversion from original EPSG:4326 to EPSG:3857)
-o country.geojson format=geojson
-o country.json format=json
-o country.svg format=svg

**Comment by NMC92** [comment]
I got it, after tweaking the code to fit my needs:
mapshaper -i countryCode.geojson -filter 'tags.admin_level == 2' name=country no-replace target=__id_1 -clip country target=__id_1 -proj webmercator -o force countryCode.geojson target=__id_1 format=geojson -o force countryCode-init.json target=__id_1 format=json -o force countryCode.svg target=__id_1 format=svg

As an added note, it would be useful to name your layers individually, should your -i file have multiple layers. Something like "name=(name1,name2,name3)" in the case of 3 layers in your file.
