### ISSUE TITLE
Export failed Export failed for an unknown reason

### ISSUE THREAD

**Issue by attikov** [mbloch/mapshaper#638]
call stack

TypeError: gui.promisify is not a function
    at mapshaper-gui.js:2467:19
    at Object.writeFiles (mapshaper.js:11719:12)
    at exportMenuSelection (mapshaper-gui.js:4755:24)
(anonymous) @ mapshaper-gui.js:4718
Promise.catch (async)
(anonymous) @ mapshaper-gui.js:4713
setTimeout (async)
onExportClick @ mapshaper-gui.js:4712

**Comment by jaspreetsinghchhabra** [comment]
Encountered the same issue. It was working fine till yesterday for me.

mapshaper-gui.js:4718 TypeError: gui.promisify is not a function
at mapshaper-gui.js:2467:19
at Object.writeFiles (mapshaper.js:11719:12)
at exportMenuSelection (mapshaper-gui.js:4755:24)

**Comment by mbloch** [comment]
Should be fixed now, thanks for reporting.
