### ISSUE TITLE
Export to Shape File Not working

### ISSUE THREAD

**Issue by MapUser2024** [mbloch/mapshaper#641]
I import a GeoJson and try to export to SHP (used to work fine) and it has an error. Something to do with .prj and basemap issue?

**Comment by mbloch** [comment]
I'll need some more info to help me troubleshoot this issue. I just tested GeoJSON to Shapefile conversion in the web UI and my simple test worked correctly.

I have a few questions. Can you send me the GeoJSON file that is causing the problem? Are you doing anything other than importing the GeoJSON and then using the Export menu to export as Shapefile? How does the basemap feature seem to be involved? Thanks!

**Comment by MapUser2024** [comment]
Just importing a GeoJSON as I always have before.
[Select_Tax Parcels (2).zip](https://github.com/mbloch/mapshaper/files/15255958/Select_Tax.Parcels.2.zip)

**Comment by MapUser2024** [comment]
![image](https://github.com/mbloch/mapshaper/assets/169288775/f15023ae-115f-4fe0-ae72-26b0c70338f1)

**Comment by mbloch** [comment]
The file I downloaded from the link you pasted (https://github.com/mbloch/mapshaper/files/15255958/Select_Tax.Parcels.2.zip) isn't a valid .zip file, it appears to have size 0. Can you check your data file and try uploading again?

I see you're on Windows -- I develop mapshaper on a Mac, but I can use Windows in an emulator. I tested mapshaper's GeoJSON importing and Shapefile exporting on Windows using both Edge and Chrome browsers, it worked correctly with my sample file.

**Comment by MapUser2024** [comment]
My bad on the zip file.... I could not load the GeoJSON as this platform says that is an invalid file format.

![image](https://github.com/mbloch/mapshaper/assets/169288775/5de1d4bc-9a13-4013-989b-24897933eee9)

**Comment by MapUser2024** [comment]
Tried changing the name to *.JSON. Still the same result. I will upload that file with the changed extension to see if that makes any difference. It may be the file on my end. Not sure.

![image](https://github.com/mbloch/mapshaper/assets/169288775/7c771405-f487-48fe-9868-a7f3faf1f76a)

**Comment by MapUser2024** [comment]
[Select_Tax Parcels (1).json](https://github.com/mbloch/mapshaper/files/15267376/Select_Tax.Parcels.1.json)

**Comment by MapUser2024** [comment]
Thanks for your help. It would not surprise me if something is going on with our GIS database. But it worked fine even just a couple of months ago.

**Comment by mbloch** [comment]
Thanks for posting the data file, now I can see what's happening. If I drop the file into mapshaper and right-click, I get the map coordinates at the mouse position: 
![image](https://github.com/mbloch/mapshaper/assets/1232222/02380532-189d-4ef8-b707-a0ab137b945e)

The size of the coordinates tells me that the GeoJSON file contains projected coordinates, not latitude-longitude coordinates. The GeoJSON standard committee dropped support for projected coordinates in 2016, and Mapshaper does not fully support old-style GeoJSON with projected coordinates, but there is a workaround that will let you use this file.

Looking at the GeoJSON code, I see that the file is using the EPSG:2927 CRS (one of the state plane coordinate systems). After loading the file into mapshaper, you can open the console and type `proj init=EPSG:2927`, like this:

![image](https://github.com/mbloch/mapshaper/assets/1232222/af721454-289f-49be-8c17-f822c339cdd1)

After this, your file is property georeferenced, and you can export it as a Shapefile.

**Comment by MapUser2024** [comment]
That worked, sort of. Now it says,
![image](https://github.com/mbloch/mapshaper/assets/169288775/9b89530d-1b9d-47ed-a6e7-43f678d3bda0)

**Comment by mbloch** [comment]
I can't tell why it is erroring -- your sample file saved correctly for me. I exported to Shapefile both from the Export menu and using the console. Pasted below is a screenshot of the console, showing the commands that I ran. If you want me look into the reason for "Save failed...", you can open the browser's error console, there will be a more detailed error message there that you could screenshot and send to me. 

![image](https://github.com/mbloch/mapshaper/assets/1232222/00ec22ab-58c8-4834-bd30-9a864c81c528)

**Comment by MapUser2024** [comment]
This is resolved. I normally use Opera. I had tried the to get this to work in Edge before as well, but with the command for the console and using Edge, that resolved the problem. Thanks again for your time and attention to detail.
