### ISSUE TITLE
Bug: can't open snapshot file I created on mapshaper.org

### ISSUE THREAD

**Issue by gka** [mbloch/mapshaper#642]
The GUI error says "Unable to use projection +init=epsg:3034 (fs.existsSync is not a function)"

<img width="482" alt="grafik" src="https://github.com/mbloch/mapshaper/assets/617518/d9052fc8-b584-4a3f-a270-e21219595ae5">

here's the snapshot file for debugging purposes (zipped so GitHub would allow me to upload it) 
[em24.msx.zip](https://github.com/mbloch/mapshaper/files/15319871/em24.msx.zip)

btw, is there a quick way to get the layer data out in the meantime?

Thanks so much for mapshaper!!!

**Comment by mbloch** [comment]
Thanks, I'll try to get this fixed asap

**Comment by mbloch** [comment]
Should be fixed now, in v0.6.94

**Comment by gka** [comment]
wow, you're the best! 💯
