### ISSUE TITLE
Bug: copy as GeoJSON doesn't copy GeoJSON

### ISSUE THREAD

**Issue by gka** [mbloch/mapshaper#643]
Hi,

I think copy as GeoJSON isn't working right now.

<img width="329" alt="image" src="https://github.com/mbloch/mapshaper/assets/617518/d3458043-c130-4ba3-a9b6-12d3ef41f5e0">

Steps to reproduce:

1. Upload a TopoJSON map, e.g. [us-states-10m.json](https://github.com/mbloch/mapshaper/files/15362636/us-states-10m.json)
2. Select a polygon feature
3. Right-click and select "copy to GeoJSON"
4. See the clipboard is still empty

There's an error logged in the console:

<img width="803" alt="image" src="https://github.com/mbloch/mapshaper/assets/617518/6f901383-db12-47ca-a2bd-667dd115e57f">

**Comment by mbloch** [comment]
Thanks for reporting this...  the last update broke this because of a careless mistake, should be working again as of v0.6.96.
