### ISSUE TITLE
[join] TypeError in expression [max=max(value)]: max is not a function

### ISSUE THREAD

**Issue by chris3522** [mbloch/mapshaper#647]
Hello,

I have an error with the max() function, this error appears with a disjoint polygon. I am trying to calculate the maximum values ​​of the points included in this polygon. However, this works with the average() and min() functions. Attached are the polygon and value_points layers to reproduce the error.
Here is the code I use in the web interface:
```
join value_points calc='max=max(value)'
```
[value_points.json](https://github.com/user-attachments/files/16096974/value_points.json)
[polygon.json](https://github.com/user-attachments/files/16096978/polygon.json)

Many thanks

**Comment by indus** [comment]
The problem is that your polygon already has a property `max` (with the value `null`), this overwrites the max function you want to use. The same will happen in the join when you overwrite it `max=max(value)`.

This will work:
```
mapshaper value_points.json polygon.json -each "delete this.properties.max" -join value_points.json calc="max_=max(value)" -rename-fields "max=max_" -info
```

**Comment by indus** [comment]
Fo some reason ` -filter-fields max invert ` doesnt work. I think the problem is that `null` is not recogniced as a field but still existing: https://mortoray.com/the-many-faces-of-undefined-in-javascript/

**Comment by chris3522** [comment]
In fact you're right. Thanks!
