### ISSUE TITLE
Cannot use this.geojson in -filter statement

### ISSUE THREAD

**Issue by clindh** [mbloch/mapshaper#649]
I am trying to filter out only features that have polygon geometry. Executing this:

mapshaper 
  -i mixed-types.geojson 
  -each "console.log(this.geojson.geometry.type)"
  -filter 'this.geojson.geometry.type == "Polygon"' 
  -o format=geojson combine-layers polygons-only.geojson

The '-each' works fine, it prints the geometry types, Polygon, Point etc

But the -filter fails with 
    `[filter] TypeError in expression [this.geojson.geometry.type == "Polygon"]: Cannot read properties of undefined (reading 'geometry')`

Why is `this.geojson` not available to -filter?  
According to doc for -filter: _"Uses the same execution context as [-each]"_

**Comment by ThomasG77** [comment]
Could be wrong but the` this.geojson` seems only to be supported in `-each` at the moment as `expressionUsesGeoJSON` only called within files related to `-each` e.g https://github.com/search?q=repo%3Ambloch%2Fmapshaper%20expressionUsesGeoJSON&type=code

Try the following

```
mapshaper \
-i mixed-types.geojson \
-each "geom = this.geojson.geometry.type" \
-filter 'geom == "Polygon"' \
-each 'delete geom' \
-o format=geojson combine-layers polygons-only.geojson
```

The logic is use `-each` to set a new property `geom` that contain the GeoJSON type, filter on the column using usual `-filter` usage and then drop the column before saving to the output. I've attached
[a sample mixed-types.json](https://github.com/user-attachments/files/16200119/mixed-types.json) but you need to rename the file extension to geojson (Github attachment limitation) or change the `-i` option with `mixed-types.json` in the above solution.

**Comment by mbloch** [comment]
@ThomasG77's suggestion is good. Let me also suggest an alternative.

This example hits on one way that working with GeoJSON can be awkward in mapshaper. mapshaper's layers are limited to a single geometry type, while a GeoJSON file can contain points, lines and polygons. You can even have points, lines and polygons in the same GeoJSON Feature if the geometry object is a `GeometryCollection`.

When mapshaper imports a GeoJSON file containing multiple geometry types, it creates a separate layer for each kind of geometry. So another solution to the above problem would be to export only the polygon layer. In mapshaper commands, you would go:

```
mapshaper mixed-types.geojson \
-target type=polygon \
-o polygons-only.geojson
```

I welcome any suggestions for how mapshaper's GeoJSON handling could be improved. Thanks!

**Comment by clindh** [comment]
Thanks! Both solutions solves my problem.

I am not sure if it is possible, but it would be convenient (and consistent) if `-filter` (and control flow commands) also had access to `this.geojson` then.
