### ISSUE TITLE
Progress bar on the Web UI

### ISSUE THREAD

**Issue by mourner** [mbloch/mapshaper#65]
MapShaper works surprisingly well for huge datasets, like 1Gb shapefile data of US streams. One UI problem though is that there's no indication whether anything is happening after you drop the files, or after you click on one of the export buttons. The UI really needs a progressbar.

**Comment by mbloch** [comment]
This is a good suggestion.

The web interface needs major reworking, to support the same feature set as the command line tool. I want to hold off on adding progress bars until the web update is farther along.

**Comment by mourner** [comment]
Cool, thanks for working on this!
I'm pretty fascinated by simplification algorithms, so really great to see this being implemented so well. BTW, congrats on Visvalingam showcasing your work :)

**Comment by mbloch** [comment]
I added a rudimentary progress bar that appears when you import a file larger than 60 MB.

I wasn't able to create a smooth animated effect. Apparently this would require breaking up the most time-consuming tasks into chunks and running each chunk  inside a setTimeout() or requestAnimationCall() call, so the browser could display incremental progress. It could be done, but maybe not worth it. Using WebWorkers is another option, i guess.

So for now we've got a progress bar than lurches from one step to the next ;)

**Comment by mourner** [comment]
I was more concerned about not having any indication at all than having a precise progress bar — now at least user knows that the data is being processed and nothing is broken. :) Thanks! I think this ticket may be closed.

**Comment by mbloch** [comment]
Ok, I'll go ahead and close the ticket...

Some related issues that are still on my TODO-list are:
* Show an error message if processing fails (#73)
* Add a progress indicator when exporting large files... I may put this on hold until I've reworked the exporting interface.
