### ISSUE TITLE
Export question - why is the export file .json and not .geojson?

### ISSUE THREAD

**Issue by elchow** [mbloch/mapshaper#650]
Hi sorry for the beginner question.. why is the file I export a .json file and not .geojson even though I selected that option in the export menu??

<img width="407" alt="Screenshot 2024-07-12 at 10 56 57 AM" src="https://github.com/user-attachments/assets/ac97ca81-6aaf-4b9f-888e-5b375b393f77">

Thanks in advance!

\

**Comment by mbloch** [comment]
First of all, `json` is a valid extension for GeoJSON data, according to the spec. Secondly, it's been that way for years, and it would break backwards compatibility with some people's scripts if I switched to `.geojson` as the default extension.

If you want your output to use `.geojson`, you can pass `extension=geojson` as an option to the output command or name your output file `*.geojson`.

**Comment by elchow** [comment]
That worked! Thank you so much!!
