### ISSUE TITLE
coordinates no longer shown under the mouse pointer

### ISSUE THREAD

**Issue by adisidev** [mbloch/mapshaper#651]
In the past, the bottom left corner of the screen would show the current coordinates of your mouse pointer. However, I can't figure out how to enable this again.

This was a really helpful feature, and saved us days if not weeks. Is there any way I can enable it again?

**Comment by mbloch** [comment]
Hi! I removed the coordinates from the bottom left corner and instead started showing mouse coordinates in a context menu, which should appear if you do a right-click (or equivalent). Does the new popup menu meet your needs? 
![image](https://github.com/user-attachments/assets/2b320cc9-e72c-4a40-b991-f10755197944)

**Comment by adisidev** [comment]
That works really well, thank you! I noticed as you zoom in, the coordinates get more fine-grain, which is a great feature! I'll close this issue, but one other thing that I noticed was changed recently was that intersections are no longer highlighted. Is there any way to get this back?
