### ISSUE TITLE
Simplying by removing overlapping lineparts adjacent polygon features

### ISSUE THREAD

**Issue by sebastiaan6907** [mbloch/mapshaper#657]
Hello, I am looking for a way of simplifying by removing overlapping lineparts between adjacent polygons.
I have a GeoJSON file with polygons of cadastral parcels which, by definition, are all adjacent polygons. Therefore almost every line is defined twice in two different polygons.

![Cadastral parcels](https://github.com/user-attachments/assets/2d13a481-c1b9-410a-9929-e051ab692ab0)

Is there a way to remove one of these overlapping lineparts?

One issue I can imagine is that after the removal of the specific coordinates the polygon is nog longer a closed circular shape. I am not sure what the consequences are. Perhaps those polygons should be redefined als LineString features?

[perceelgrenzen_blokje (geojson file saved as txt file).txt](https://github.com/user-attachments/files/16923718/perceelgrenzen_blokje.geojson.file.saved.as.txt.file.txt)

**Comment by desryisliko** [comment]
hii, can i know how you completed this case? because i have the same problem. Thank you

**Comment by sebastiaan6907** [comment]
Not to be honest. I received no further response and I have no idea how to resolve this.

**Comment by martgnz** [comment]
Did you try either the `clean` or the `snap` commands? Those have been useful for me in the past with similar polygons.

https://github.com/mbloch/mapshaper/wiki/Command-Reference#-clean
https://github.com/mbloch/mapshaper/wiki/Command-Reference#-snap
