### ISSUE TITLE
Shapefile to geojson has a small offset when .prj is present

### ISSUE THREAD

**Issue by cHewN** [mbloch/mapshaper#664]
My data is in CRS 31370 (lambert 72) https://epsg.io/31370

When I convert a shapefile to geojson with .prj present, there is a small offset in the resulting geojson.
When I convert without a .prj, and use `-proj init=EPSG:31370` the offset is not present.

Full command would be
`-i mylocalpath/Gvp42025.shp -proj crs=EPSG:4326 -o format=geojson`

The offset also exists when converting on the mapshaper.org site with the following steps:
- Import with .prj
- Import without .prj but apply `proj init=EPSG:31370` in the console after importing

[Gvp42025.zip](https://github.com/user-attachments/files/17814145/Gvp42025.zip)

**Comment by mbloch** [comment]
Thanks for reporting this, I'll check it out.

**Comment by cHewN** [comment]
That makes sense. Guess we'll have to do some checks then on the content of the prj.

Thanks for the reply!
