### ISSUE TITLE
Clip has some problems with edges

### ISSUE THREAD

**Issue by nspringer** [mbloch/mapshaper#68]
Clip leaves out some polygons that share vertices with the clip poly.
![image](https://cloud.githubusercontent.com/assets/719155/6092864/dd6448f8-aebf-11e4-8cf1-f70308015df2.png)

You can see missing bits of the resulting clipped file (green) along the left edge represented by the yellow squares (original data) that are visible.  The red line is the clip boundary.

The clip poly was created from a dissolve of the original data so the topology should be the same.

The test files can be found here:
[Data to be clipped](https://www.dropbox.com/s/cqq04xqtayz9o0v/SnowAmt_Total_ergrlake.zip?dl=1)
[Clipping polygon](https://www.dropbox.com/s/i6eo6hkyi7cgcnd/ergrlake_clip.zip?dl=1)

**Comment by nspringer** [comment]
Just to confirm QGIS was able to clip correctly using the same data
![image](https://cloud.githubusercontent.com/assets/719155/6092930/795e6864-aec1-11e4-8c22-10d4b831ba19.png)

**Comment by mbloch** [comment]
Thanks for the bug report... I'll look into this.

**Comment by mbloch** [comment]
Just published version 0.2.16, which includes a fix for this issue.

(Before the fix, mapshaper was failing to detect when some clipped shapes contained segments that were collinear with segments in the clipping shape).
