### ISSUE TITLE
Merge-layers help

### ISSUE THREAD

**Issue by nspringer** [mbloch/mapshaper#70]
I'm not totally clear on how -merge-layers works.  Does it merge multiple shape files? Can you provide an example?

**Comment by mbloch** [comment]
Yes, you can use `-merge-layers` to merge multiple Shapefiles. This command doesn't affect feature geometry, it only concatenates features from several layers into a single layer. I updated the command reference with an example, see here:
https://github.com/mbloch/mapshaper/wiki/Command-Reference#-merge-layers
