### ISSUE TITLE
Data doesn't load/mapshaper web broswer non-responsive

### ISSUE THREAD

**Issue by hasolak825** [mbloch/mapshaper#72]
I have been attempting to load in and simplify a shapefile I have using this site. I have tried multiple times to get the site's select tool to even load my data into mapshaper. 90% of the time, nothing happens and the shapefile doesn't load. Occasionally it has shown up in the interface, and from there I have selected to repair line intersections, etc. and simplify (all extremely slow) and then try to click export. When I click export to shapfile nothing happens and the site is again unresponsive. What might be causing this and how can it be fixed?

Thank you

**Comment by mbloch** [comment]
Your Shapefile may contain more data than mapshaper can effectively handle. If you can send me the Shapefile, I'd be happy to take a look.

Also, it would help to know:
How large is the .shp file in megabytes?
How many individual features does it contain?
What browser are you using and what is the version number?
What kind of computer are you using, and how much RAM does it have?

**Comment by hasolak825** [comment]
​
 L2_OD.zip
<https://docs.google.com/file/d/0B6LHic0-pFGdQlp4dnVCRkpkdTA/edit?usp=drive_web>
​
hi Matt,

Thanks for getting back to me so quickly. my shapefile is attached. You are
right, it's pretty huge and detailed so that is probably why things aren't
working properly. I was able to get a subset of these files in by breaking
it up bny continents. Do you recommend just taking subsets? What is the
limit of how much data mapshaper can process?

If the data is too large for mapshaper, do you know of any other likewise
simplification tools? I have used one in ArcGIS but it creates gaps between
polygons even with a very low simplification tolerance.

Thanks!

Hayley

**Comment by mbloch** [comment]
Mapshaper was struggling for a couple of reasons. It's a large Shapefile (676 MB, 42,645 polygon features), and it contains a large number of segment intersections (about 578,000 -- see the [screenshot](http://cl.ly/image/3p1j292D1n0A)).

Mapshaper can clean up most of the intersections for you by snapping together nearby vertices (by selecting the "auto-snap" option). Your Shapefile contains data from many countries, and a few of the country borders are so misaligned that snapping can't fix them. Simplification will increase the gaps between the borders of those few countries.

I was able to simplify and export this in mapshaper's web interface, here's how:
* Use a recent version of Firefox (handles large files better than Chrome)
* Select the "auto-snap" option before importing the Shapefile.
* Import the Shapefile -- it will probably take about 40 seconds for the Shapefile to appear.

**Comment by mbloch** [comment]
Ideally, mapshaper should let users know if processing is going to take a long time or if the file can't be imported for some reason.  A progress bar will help (issue #65). The web interface should show an error message if processing fails for some reason. It would also be nice to give users some guidance in cases like this one, where there's a large number of topology errors that can be fixed by snapping. I'm closing this issue and adding a new issue about errors and warnings.

**Comment by hasolak825** [comment]
thanks for your help matt, i'll see what I can do with this!
