### ISSUE TITLE
Maintain attributes when exporting geometry

### ISSUE THREAD

**Issue by Chaz6** [mbloch/mapshaper#74]
It would be most useful to be able to load a shapefile from a zip file which includes attributes for each polygon, and they should be maintained when exporting the resulting geometry. Otherwise I have to manually join the resulting data to restore the attributes of each feature.

**Comment by mbloch** [comment]
I like your suggestion of accepting .zip files containing all the individual files in a Shapefile.

In my design sketches for an updated GUI interface, I've worked out a simple interface for adding each Shapefile component, either by dragging or selection from the filesystem. Updating the GUI isn't my top priority right now, so it might be a while before this gets implemented.

Meanwhile, you can try just dragging and dropping the .dbf file onto the browser window. You won't get any visual feedback, but the dbf file should be in the exported .zip file, if you export as a Shapefile.

**Comment by mbloch** [comment]
The latest version (v0.2.24) of the web interface supports importing Zip archives containing Shapefiles or other supported files.

**Comment by Chaz6** [comment]
Great! Thank you for your work on this.
