### ISSUE TITLE
option to load file from server 

### ISSUE THREAD

**Issue by piobuilleann** [mbloch/mapshaper#75]
It would be nice, at least in my particular case, to be able to load files from a server. Would their be an implementation so where this could easily be integrated?

**Comment by mbloch** [comment]
I've thought about accepting input from online sources....  I haven't needed to do this yet myself, but it seems like a useful feature, so I'll plan to add it in the near future. In the case of Shapefile input, I think it's fairly common for Shapefiles to be published online as .zip archives, so it might be nice to support importing .zip files from online sources, in addition to loading unzipped files.

**Comment by mbloch** [comment]
I've thought about this a bit more.... Now I'm not sure loading files from online sources is something worth building into mapshaper's command line tool. There are other good tools for downloading files, like curl and wget. Have you considered writing a shell script or Makefile to combine downloading the files you need and processing them with mapshaper?

**Comment by piobuilleann** [comment]
My sole interest in this project is the gui. The fact that the load time on very large geojson files is much quicker compared to other js solutions out there is great! Awesome work. I put down a little side project a few months ago and I think I might pick it back up.  Thanks and I'm looking forward in seeing what becomes of Mapshaper.

**Comment by mbloch** [comment]
Thanks for your suggestions :)
