### ISSUE TITLE
option to scale by width

### ISSUE THREAD

**Issue by piobuilleann** [mbloch/mapshaper#76]
With the ratio of 1 to scale the width of the canvas instead of the height. This is just an enhancement option.

**Comment by mbloch** [comment]
Could you be a bit more specific? Are you referring to TopoJSON quantization, or the way images are displayed in the web interface?

**Comment by piobuilleann** [comment]
Oh, sure.  This is within the way images are displayed within the web interface. The option on having the image positioned by width as an option would be nice.  Just an idea. I like the project. Great job!

**Comment by mbloch** [comment]
The way objects are currently positioned is designed to show the entire extent of the dataset. If the bounding box of a dataset is "tall" relative to the interface (i.e. has a smaller aspect ratio), then the content is scaled to fit vertically and centered horizontally. If the bounding box is "wide", then it is scaled to fit horizontally and centered vertically.

If I were to position by width, then portions of relatively tall datasets would be out of view at full zoom. I'm not in favor of having that as an option.

**Comment by piobuilleann** [comment]
" If the bounding box is "wide", then it is scaled to fit horizontally and centered vertically."  Great! Thanks for the heads up!
