### ISSUE TITLE
Could not filter island

### ISSUE THREAD

**Issue by jun3838** [mbloch/mapshaper#79]
Hi,

I tried using mapshaper to filter out small islands.
```
mapshaper -o ~/downloads/TWN.json -i ~/downloads/TWN.geo.json -filter-islands
```

it seem be to be the same, and nothing has changed... could any one help

i've tried with `-filter-islands remove-rmpty` `-filter-islands min-vertices=10` `-filter-islands min-area=10` all doesn't seem to make any differents

**Comment by mbloch** [comment]
Hi, can you send me your data file so I can try to duplicate the issue? you can email the file to masiyou@gmail.com
--mbloch

**Comment by mbloch** [comment]
I responded to @jun3838 via email with help using the -filter-islands command. This case turned up a bug where -filter-islands would remove polygons inside donut holes in addition to detached islands. The new 0.3.0 release changes the behavior of -filter-islands so that donut holes are retained.
