### ISSUE TITLE
keep-shapes not always working

### ISSUE THREAD

**Issue by KeiSamara** [mbloch/mapshaper#80]
I've launched this command over a shapefile:
mapshaper shapefiles/country.shp -simplify 5% keep-shapes -o format=geojson

You can see on attached screenshot that some of small parts of the shape has been removed:
![qgis-keep-shapes](https://cloud.githubusercontent.com/assets/466991/8607562/64bb4294-269c-11e5-8ce1-3f31892f698b.jpg)

**Comment by mbloch** [comment]
`keep-shapes` actually only retains the largest part of multi-part polygon feature. The smaller parts will disappear as simplification increases.

One way to retain each polygon ring is to use the `-explode` option before simplifying with `keep-shapes`. `-explode` converts multi-part features into single-part features.

There are a couple of reasons for the current behavior of `keep-shapes`, although I should probably have picked a less confusing name.

**Comment by mbloch** [comment]
I'll consider adding an option to retain all of the rings of multi-part polygons if someone explains why this feature would be useful... meanwhile i'm closing this issue.

**Comment by KeiSamara** [comment]
@mbloch For example, we are simplifying shape of some country. Retaining all of the rings prevent losing data about islands.

**Comment by JoshMcCullough** [comment]
Makes sense that `keep-shapes` or some other option would keep all individual parts of a shape ("rings", as they were called here previously).

**Comment by mbloch** [comment]
There's a workaround if you want to preserve all of the individual rings. You can use `-explode` to convert multipart shapes to single-part shapes before running `-simplify keep-shapes`. 

I'll think about adding another flag to `-simplify`, maybe `keep-parts`, that would retain all parts of a polygon or polyline feature. I don't see this as a good option if you're using simplification for cartographic generalization.

**Comment by JoshMcCullough** [comment]
Ah, thank you for that info!

**Comment by tonythebest** [comment]
Indonesia lost tens of islands using `keep-shapes`
