### ISSUE TITLE
Shapefile to geojson conversion

### ISSUE THREAD

**Issue by id047** [mbloch/mapshaper#82]
Hi,

I'm trying to convert from a shapefile to geojson using 
mapshaper inputfile.shp -o format=geojson 

Now, I do get an output file and I can load it into the mapshaper web gui and see that it looks fine but I can't load the geojson file into any other viewers; the shapefile to shapefile conversion and also simplification works fine with mapshaper-if that is relevant. The conversion to geojson works fine with ogr2ogr using
ogr2ogr -f "GeoJSON" "output_ogr.geojson" "inputfile.shp" -t_srs EPSG:4326 -overwrite

I'm including the first few lines of the geojson outputs from both mapshaper and ogr2ogr below. One obvious difference is the inclusion of crs info in the ogr2ogr generated file. Also, in the ogr2ogr file, I can recognize the lat and lng points for my file but I am not sure what the numbers in the mapshaper generated file represent. 

Am I missing something here in terms of the conversion with mapshaper? Are there any additional flags that need to be included?

Thank you.

Mapshaper generated geojson:

{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"LOWER":-108,"UPPER":-32.965},"geometry":{"type":"Polygon","coordinates":[[[538738.65115839,4766310.00013473],[538739.99988453,4766311.6843041],[538741.68398523,4766310.00013473],[538739.99988453,4766308.651283265],[538738.65115839,4766310.00013473]]]}},
{"type":"Feature","properties":{"LOWER":-108,"UPPER":-32.965},"geometry":{"type":"Polygon","coordinates":[[[458908.22168091004,4718070.000108135],[458910.000105705,4718072.41158168],[458911.124766945,4718070.000108135],[458910.000105705,4718068.65125667],[458908.22168091004,4718070.000108135]]]}},

ogr2ogr generated geojson:

{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "LOWER": -108.000000, "UPPER": -32.965000 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -80.52435396137399, 43.048496174704589, 0.0 ], [ -80.524337284638861, 43.04851127132433, 0.0 ], [ -80.524316724573538, 43.048496019936124, 0.0 ], [ -80.524337495678381, 43.04848395987208, 0.0 ], [ -80.52435396137399, 43.048496174704589, 0.0 ] ] ] } },
{ "type": "Feature", "properties": { "LOWER": -108.000000, "UPPER": -32.965000 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -81.501016371437672, 42.613970776937769, 0.0 ], [ -81.500994862654082, 42.613992587931371, 0.0 ], [ -81.500980976534919, 42.613970931716068, 0.0 ], [ -81.500994591227638, 42.613958724869583, 0.0 ], [ -81.501016371437672, 42.613970776937769, 0.0 ] ] ] } },

**Comment by mbloch** [comment]
the ogr2ogr command that you used converted the projected coordinates in
your Shapefile to lat long. Mapshaper does not do this conversion...

**Comment by mbloch** [comment]
.. I've thought about adding support for coordinate transformations using the proj4js library, but I've decided not to go there for now. ogr2ogr is already a good tool for projections and datum transformations.

**Comment by id047** [comment]
Ah I see. Thank you.
