### ISSUE TITLE
Save as Geojson loses local formatting

### ISSUE THREAD

**Issue by Monduiz** [mbloch/mapshaper#83]
I imported a shapefile and dbf with attributes that have comma for a decimal separator to mapshaper online and when I save as geojson, all the values have a dot instead of a comma. Is there something I'm missing?

**Comment by mbloch** [comment]
Hi, thanks for reporting this.

Currently mapshaper assumes a dot as decimal separator. According to the [JSON spec](http://www.json.org/), numbers in JSON should use a dot. I'm curious whether you know of any software that accepts GeoJSON containing comma-separated decimal numbers.

If a .dbf contains numeric fields with comma-separated decimals, I think that mapshaper will fail to import the numbers correctly. Mapshaper uses the JavaScript parseFloat() function to import numeric data from a DBF, which will truncate numbers that use a comma separator (so "4,12" would get imported as the integer 4). I'll try to fix this very soon!

Also, mapshaper will incorrectly parse csv files that contain comma-separated numbers.

Here's what I propose:
* Fix .dbf importing to correctly import numbers with comma-separated decimals.
* Add a command line option named "decimal-separator", which will affect importing and exporting of csv files and exporting of dbf files. (You can enter command line options for importing and exporting in the web UI.)
* GeoJSON and TopoJSON will continue to use the dot separator.

Would this meet your need?

**Comment by Monduiz** [comment]
These sounds like great improvements but I'm trying to find a way to display data on my leaflet maps, which are based on geojson, with comma-separated decimals.

**Comment by mbloch** [comment]
So do you want to display data in a table or popup, when the user clicks on a shape, for example?

If this is the case, one approach would be to store the values as formatted strings in your GeoJSON file. If the values are coming from numerical fields in the Shapefile dbf file, then mapshaper doesn't have a good way to format the values the way you want to display them.

A second approach would be to store the values as numeric data in your GeoJSON file, then format them on the client using a JavaScript function, before showing them to the user.

Please correct me if I've misunderstood your use case.

**Comment by mbloch** [comment]
One quick suggestion for using mapshaper to format numbers for various locales. Say your dataset has a numeric field named "foo", you could type the following in mapshaper's browser console:

```
each "foo_str = foo.toLocaleString('de')"
```

This would create a new field called "foo_str" with German-style numbers. toLocaleString() has other formatting options as well, if you need something fancier.

**Comment by Monduiz** [comment]
Yes, this is what I'm working. Basically, I am developing a web app to show a large body of work on small areas. Values that are displayed as numbers from the geojson appear in popups, legends for the layers or D3 charts inside popups. For the D3 charts, I believe I can use functions from D3 to format the values. The problem is really with those that have to be shown in popups and legends. 

This is why I was trying to get a geojson with the correct local settings format for the values. Mapshaper is important in my workflow because I use it to convert shapefiles and simplify the geometries. I have tried using a geojson with strings but the charts in d3 were not all working as a result. I have also tried with R but RGDAL is finicky with geojson and I dont think it will use comma seperated values. You mentioned that there might be a way to format the values with javascript and that gives me hope. Im not sure how I would go about it though.

The command you are suggesting for mapsaper, would it allow me to save as geojson with that format?

**Comment by mbloch** [comment]
I have a clearer picture of your project now. I would suggest using d3's support for locales (https://github.com/mbostock/d3/wiki/Localization) to do all of your formatting on the client, including legends, popups, tables, etc.. The code snippet I gave you would let you add formatted numbers to your GeoJSON file alongside your numeric data -- so each value would be represented twice in the GeoJSON file, once as a number and once as a string containing a formatted number. But you can use d3 for formatting, so there's no need to pre-format your numeric data.

**Comment by Monduiz** [comment]
Thank you Matthew, I really appreciate your advice. I have a jsfiddle up if you have suggestions. I'm trying to figure out how to implement your suggestions. Best regards!

**Comment by mbloch** [comment]
For now, I'm going to suggest that people use a different library for locale-specific string formatting.
