### ISSUE TITLE
Feature suggestion: Produce SVG

### ISSUE THREAD

**Issue by rotsee** [mbloch/mapshaper#84]
Now that [Kartograph.py](https://github.com/kartograph/kartograph.py) is no longer maintained, it would be beautiful if Mapshaper could produce SVG from geodata and [projection](http://kartograph.org/showcase/projections/).

**Comment by gagan-bansal** [comment]
I don't know if this is in the scope of mapshaper. Well I have created a module [geojson2svg](/gagan-bansal/geojson2svg) for converting GeoJSON to SVG map at client side using JavaScript. You need to reproject your data first in the required projection first. For projection these modules can be used:  [proj4js](https://github.com/proj4js/proj4js) or [reproject](https://github.com/perliedman/reproject) or [reproject-spherical-mercator](https://github.com/geosquare/reproject-spherical-mercator).

**Comment by rotsee** [comment]
Thanks for the links. Guess it's out of scope, so closing this again.

**Comment by gagan-bansal** [comment]
Small clarification, I am not the authorized person to decide if this requirement is in the scope or not. This was my personal view. If required geojson2svg can be integrated with mapshaper as geojson2svg perfectly works on node.js.

**Comment by mbloch** [comment]
I would like to support SVG output. Converting vector data to SVG is the easy part. For SVG layers to be very useful, it seems to me that you would want the ability to add fill and stroke styles. You'd also want to be able to convert point data into symbol layers, like graduated circles, or labels. Adding interfaces for all of this would take a bit of work, so we should probably think of SVG support a as a long term goal.

I'm reopening the issue, I think it fits mapshaper's overall goal to be an alternative to GIS software for essential map making tasks.

**Comment by mbloch** [comment]
I just added basic SVG output. When I have time, I'll work on adding the ability to style SVG shapes and also display labels.

**Comment by mbloch** [comment]
Basic SVG creation and styling seems to be working well, closing.
