### ISSUE TITLE
mapshaper as a R htmlwidget

### ISSUE THREAD

**Issue by timelyportfolio** [mbloch/mapshaper#85]
Thanks so much for the amazing `mapshaper`.  Even after using it and thoroughly inspecting the code, I am shocked that so much can be done client-side and even in the browser.  I wanted to make you aware that I'm trying to integrate `mapshaper` into `R` as an [`htmlwidget`](http://htmlwidgets.org) to allow a seamless experience.  Here is a post [Week 32|mapshaperWidget](http://www.buildingwidgets.com/blog/2015/8/14/week-32-mapshaperwidget) that explains the repo [mapshaper_htmlwidget](https://github.com/timelyportfolio/mapshaper_htmlwidget).

Thanks again!

**Comment by mbloch** [comment]
Cool project!

**Comment by timelyportfolio** [comment]
I need to circle back and include all the new features that you have added.  Please know that I really, really appreciate all your work on this incredible project. As a side note, I'm trying to think through if adding [topogram](https://github.com/shawnbot/topogram)/cartogram functionality would be helpful.

Thanks again!
