### ISSUE TITLE
Spatial join

### ISSUE THREAD

**Issue by mbloch** [mbloch/mapshaper#87]
Mapshaper should be able to join attributes from a points layer to a layer of polygons based on point-in-polygon tests. Options would include rules for how to aggregate data values when more than one point matches the same polygon, and the option for points that fall outside of every polygon to be assigned to the nearest polygon, up to a certain maximum distance.

There should be a way to identify points and polygons that can't be joined. One option is to create additional output layers containing unjoined shapes. (This might be a good idea for the current -join command as well).

**Comment by nvkelso** [comment]
+1

**Comment by mbloch** [comment]
I just published v0.3.8, which adds point-to-polygon and polygon-to-point spatial joins to the `-join` command. The `-join` command also got a new option, `sum-fields=`, for summing certain fields when multiple source records are joined to the same target record.

ArcGIS has very many options for performing spatial joins. I'll think about adding more options to Mapshaper's spatial join as the need arises.

**Comment by mbloch** [comment]
The current spatial join implementation seems to work well, as far as it goes. Closing this ticket.
