### ISSUE TITLE
Interactive box tool

### ISSUE THREAD

**Issue by mbloch** [mbloch/mapshaper#91]
It would be nice to be able to select a subset of features interactively by clicking or dragging a box. Selected features could then be deleted, or they could be moved or copied to a new layer. Features could also be selectable via a JS expression, similar to the current `filter` command.

**Comment by mbloch** [comment]
v0.4.156 adds a box tool, which is activated using shift-drag.

**Comment by 1wheel** [comment]
Is this still enabled? When I shift drag on v0.5.6 it just zooms in.

**Comment by mbloch** [comment]
Hi! It should work, but now you have to select the box tool from a menu by clicking the arrow button and then selecting "shift-drag box tool". I added this menu as a way to display the various interaction modes more clearly. Let me know if you have any suggestions for improving this interface, I feel like it could be improved, but I'm not sure how.

![image](https://user-images.githubusercontent.com/1232222/81672659-73bb4480-9418-11ea-990e-a42e3627ffe5.png)

**Comment by 1wheel** [comment]
oooh. I think my eyes glazed over the pointer because it is under the zoom controls I never use. 

Not sure how to make it more prominent, you really just want it to be noticeable once and then keep the focus on the map.
