### ISSUE TITLE
Connection with OpenLayers 3

### ISSUE THREAD

**Issue by krzbor** [mbloch/mapshaper#98]
How to get the shp import and export functions. I would like to use them to import / export data into OpenLayers 3

**Comment by mbloch** [comment]
I haven't used OpenLayers...  that's a web mapping library, right? Mapshaper has functions for importing and exporting data, but they're designed to be used in a Node.js application, not in the context of a web map.

To build mapshaper's web UI, I use [browserify](http://browserify.org/) to bundle mapshaper's data processing code together with the UI code into one rather large JS file.

There's probably a way to browserify just the parts of mapshaper that you want to use. Could you tell me a bit about how you want to use mapshaper in your OpenLayers project?

**Comment by krzbor** [comment]
We prepare Map Viewer based on OpenLayers. We want to add functionality to read and 
write SHP. OpenLayers can display vector data GeoJSON: 
http://openlayers.org/en/v3.6.0/examples/geojson.html
but there is no read-write SHP functionality. Hence my idea to use part of Mapshapera as a 
converter SHP-> GeoJSON (to read) and geoJson-> SHP (to write)
> 
> I haven't used OpenLayers... that's a web mapping library, right? Mapshaper has functions for 
> importing and exporting data, but they're designed to be used in a Node.js application, not in the 
> context of a web map.
> To build mapshaper's web UI, I use browserify to bundle mapshaper's data processing code 
> together with the UI code into one rather large JS file.
> There's probably a way to browserify just the parts of mapshaper that you want to use. Could you 
> tell me a bit about how you want to use mapshaper in your OpenLayers project?
> -
> Reply to this email directly or view it on GitHub.


Krzysztof Borys

**Comment by mbloch** [comment]
You could use [browserify](http://browserify.org) to convert the `mapshaper.js` Node module to make it loadable in a web browser. Then you could use Mapshaper's functions for importing and exporting Shapefile and GeoJSON formats.

The browserified module is pretty huge, though -- 850KB unminified -- and it includes a lot of code that you wouldn't need just for converting between the two formats. So Mapshaper might not be your best option for converting between Shapefile and GeoJSON formats on the client.

**Comment by krzbor** [comment]
The web folder (mapshaper\www) contains a file mapshaper.js. What functions should be 
used to convert shp to GeoJSON and vice versa?

> 
> You could use browserify to convert the mapshaper.js Node module to make it loadable in a web 
> browser. Then you could use Mapshaper's functions for importing and exporting Shapefile and 
> GeoJSON formats.
> The browserified module is pretty huge, though -- 850KB unminified -- and it includes a lot of code 
> that you wouldn't need just for converting between the two formats. So Mapshaper might not be 
> your best option for converting between Shapefile and GeoJSON formats on the client.
> -
> Reply to this email directly or view it on GitHub.


Krzysztof Borys

**Comment by mbloch** [comment]
To convert GeoJSON to Shapefile in the browser, you first need to browserify the `mapshaper.js` Node module in the root directory of the project (not the Web UI file in the web directory), like this:

```
$ browserify -r ./mapshaper.js:mapshaper > mapshaper-lib.js
```
The above command creates a client-side library that you can add to a web page using a `<script>` tag and require using `require("mapshaper")`.

The following code shows how you could use the library to convert a GeoJSON object to an array containing Shapefile files. I didn't have your use case in mind when I wrote these functions, so the interface might seem a bit strange... 

```
var mapshaper = require('mapshaper');
var geojson = {type: "Point", coordinates: [0, 0]};
var opts = {no_topology: true};
var dataset = mapshaper.internal.importContent({json: {content: geojson}}, opts);
var output = mapshaper.internal.exportFileContent(dataset, {format: 'shapefile'});
console.log(output);
```

Converting Shapefile to GeoJSON is similar

```
var mapshaper = require('mapshaper');
var shp = <ArrayBuffer>; // ArrayBuffer containing contents of .shp file
var dbf = <ArrayBuffer>; // ArrayBuffer containing contents of .dbf
var opts = {no_topology: true};
var dataset = mapshaper.internal.importContent({shp: {content: shp}, dbf: {content: dbf}}, opts);
var output = mapshaper.internal.exportFileContent(dataset, {format: 'geojson'});
```

**Comment by krzbor** [comment]
Thank you for your response. Inside the folder mapshaper\www is the index.html file. The file 
contains a line : <script src="mapshaper.js" type="text/javascript"></script>. It seems to me 
that I can use directly file mapshaper.js.

> 
> To convert GeoJSON to Shapefile in the browser, you first need to browserify the mapshaper.js 
> Node module in the root directory of the project (not the Web UI file in the web directory), like this:
> 
> $ browserify -r ./mapshaper.js:mapshaper > mapshaper-lib.js
> 
> 
> The above command creates a client-side library that you can add to a web page using a 
> <script> tag and require using require("mapshaper").
> The following code shows how you could use the library to convert a GeoJSON object to an array 
> containing Shapefile files. I didn't have your use case in mind when I wrote these functions, so the 
> interface might seem a bit strange...
> 
> var mapshaper = require('mapshaper');
> var geojson = {type: "Point", coordinates: [0, 0]};
> var opts = {no_topology: true};
> var dataset = mapshaper.internal.importContent({json: {content: geojson}}, opts);
> var output = mapshaper.internal.exportFileContent(dataset, {format: 'shapefile'});
> console.log(output);
> 
> 
> Converting Shapefile to GeoJSON is similar
> 
> var mapshaper = require('mapshaper');
> var shp = <ArrayBuffer>; // ArrayBuffer containing contents of .shp file
> var dbf = <ArrayBuffer>; // ArrayBuffer containing contents of .dbf
> var opts = {no_topology: true};
> var dataset = mapshaper.internal.importContent({shp: {content: shp}, dbf: {content: dbf}}, opts);
> var output = mapshaper.internal.exportFileContent(dataset, {format: 'geojson'});
> 
> 
> -
> Reply to this email directly or view it on GitHub.



Krzysztof Borys

**Comment by mbloch** [comment]
Feel free to experiment with using `www/mapshaper.js`. That file includes all of the code for mapshaper's web UI in addition to mapshaper's data processing functions, but if you can use it, great.

**Comment by mbloch** [comment]
I think this issue can be closed...

At present, I'm not assigning a high priority to developing mapshaper as a library for other applications to use.
