### ISSUE TITLE
GeometryCollection wrapper on simplify json file causing load failure on Qgis

### ISSUE THREAD

**Issue by ete-west3** [mbloch/mapshaper#99]
When taking a json file with simplification to write a smaller json file the resulting file has {"type":"GeometryCollection","geometries":[  wrapped round the resulting contents. Qgis does not recognise this and ignores the geometry. 

Very simple script only using the simplify parameter.

How can I suppress this happening. Currently having to filter this out.

**Comment by mbloch** [comment]
I see... QGIS is unable to import GeometryCollection objects, but it can import a single GeoJSON geometry (e.g. Point or MultiPolygon).

Currently, mapshaper exports a FeatureCollection if a data layer contains one or more data attributes, and a GeometryCollection if a layer is missing attribute data.

I had considered having mapshaper export individual feature or geometry objects if the output dataset contains just one object, but decided for simplicity's sake to always export a collection, regardless of whether there were zero, one or multiple objects to export.

I'm open to suggestions for making GeoJSON output more flexible.

Meanwhile, if you just want to be able to open your output file in QGIS, you can output a FeatureCollection by adding a single data property to your geometry. You could add an id property with the following command:
```
-each 'FID = $.id'
```

**Comment by mbloch** [comment]
Version v0.4.46 adds the `-o geojson-type=` option. You can specify "FeatureCollection", "GeometryCollection", or "Feature" (if outputting a single feature). If this option is unset, mapshaper will output a FeatureCollection if the output contains attribute data values or feature ids, or else a GeometryCollection.
